### ISSUE TITLE
请增加ffmpeg 相关的包

### ISSUE THREAD

**Issue by vivopcz** [xmake-io/xmake-repo#1]
如， libavcodec， libavformat 等

**Comment by waruqi** [comment]
好的，我之后会考虑添加进来，请耐心等待。

**Comment by waruqi** [comment]
目前虽然加进去了，但是还不支持win，我正在尝试改进ffmpeg配置选项的支持，以及win, android, ios的支持。。xmake下个版本会完整支持ffmpeg的包。

**Comment by ccsnake** [comment]
@waruqi 大佬 现在支持了么？谢谢

**Comment by waruqi** [comment]
> @waruqi 大佬 现在支持了么？谢谢

你试下不就知道了
