### ISSUE TITLE
Packages depend on glfw are affected by `package:add("cxflags", "/MD")`

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#100]
### 描述问题

https://github.com/xmake-io/xmake-repo/blame/master/packages/g/glfw/xmake.lua#L45

glfw/xmake.lua中的这个设置被传递给了依赖它的包，导致依赖它的包在检测snippets的时候会在编译时不恰当地加上"/MD"选项然后链接报错（静态库不匹配动态库）

### 期待的结果

这个选项应仅在构建glfw时生效，不影响依赖glfw的包

### 错误信息

error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(_427CC362A91C4F008FB8F5226EA01A30.o 中)

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.3.8
- xmake运行平台：Windows 10
- xmake目标平台：windows

**Comment by waruqi** [comment]
这个主要原因还是因为win上直接拉取的bin包，所以依赖的vs runtime 定死了 /MD，没法根据 package:config("vs_runtime") 来切换，导致的冲突

我稍微改了下，将/MD限制在它自身的 on_test内部，但我感觉依赖这个库的其他程序，在最终/MT模式下link可能还是会有冲突。。你先试试吧

如果要完全搞定，除非 glfw 在 windows下 如果package:config("vs_runtime")是 MT，就走源码编译才能完全适配。
