### ISSUE TITLE
script/test.lua report conflict on testing multiple packages

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#102]
### 描述问题

测试多个包时，比如同时测试A和B，而B依赖A的一个早期版本，test.lua会报错

### 期待的结果

先测试A，然后再安装A的旧版本并测试B

### 错误信息

error: @programdir/core/main.lua:284: @programdir/actions/require/impl/package.lua:333: package(blosc): version conflict, '1.20.1' does not satisfy '~1.5.0'!

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.3.8
- xmake运行平台：all（ci中的报错）
- xmake目标平台：all

### 其他信息

https://github.com/xq114/xmake-repo/actions

**Comment by waruqi** [comment]
dev上改了，自己rebase下
