### ISSUE TITLE
libcurl 低版本编译选项在 Windows 上处理不正确

### ISSUE THREAD

**Issue by Ocrosoft** [xmake-io/xmake-repo#1042]
### Xmake 版本

2.6.3

### 操作系统版本和架构

Windows 11 x64

### 描述问题

libcurl 于 7.81 版本调整了部分开关的名称，如 CMAKE_USE_OPENSSL 更改为 CURL_USE_OPENSSL。
目前仓库中的 libcurl 已经更新到适用于 7.81 版本的开关名称，但没有维持对旧版本的兼容，导致部分开关无效。
@xq

### 期待的结果

7.80 及以下版本的配置也能正常生效。

### 工程配置

add_requires("libcurl 7.81.0", {configs={openssl=true, zstd=true, zlib=true, debug=false}})

**Comment by waruqi** [comment]
这种，你直接来个 pr 过来帮忙改下就好了

**Comment by waruqi** [comment]
可以了
