### ISSUE TITLE
请求添加apr工具包

### ISSUE THREAD

**Issue by linhuikui** [xmake-io/xmake-repo#1127]
### Is your feature request related to a problem? Please describe.

希望能够添加Apache Portable Runtime (APR)软件包：https://apr.apache.org/

### Describe the solution you'd like

希望实现跨平台编译，如果不方便下载软件包，也可以从这里拉取源码https://gitee.com/apache/apr.git；
可以的话，这三个软件包希望都可以跨平台编译：APR、APR-util 、APR-iconv

**Comment by waruqi** [comment]
现在人力有限，目前大部分包都是用户自己维护，建议直接提 pr 过来。。

**Comment by waruqi** [comment]
done https://github.com/xmake-io/xmake-repo/blob/master/packages/a/apr/xmake.lua
