### ISSUE TITLE
Unable to install google/benchmark with clang toolchain

### ISSUE THREAD

**Issue by L-Sun** [xmake-io/xmake-repo#1152]
### Xmake Version

xmake v2.6.4+master.8dfd4c9

### Operating System Version and Architecture

Linux L 5.10.102.1-microsoft-standard-WSL2

### Describe Bug

When I use clang toolchain,  compilation of the `benchmark` failed because the compile command contains an argument: `-wd654` which is not recognized by the clang compiler.

According to the homepage of [google/benchmark,](https://github.com/google/benchmark) it may be that we did not set the following cmake cache variables when using clang.

> If you are using clang, you may need to set `LLVMAR_EXECUTABLE`, `LLVMNM_EXECUTABLE` and `LLVMRANLIB_EXECUTABLE` cmake cache variables.

### Expected Behavior

When using the clang toolset, the compile command should not contain any unrecognized arguments. Then, it might compile successfully.

### Project Configuration

```sh
xmake l scripts/test.lua -v --toolchain=clang benchmark
```

### Additional Information and Error Logs

CMakeError.log
```log
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WD654 failed with the following output:
Change Dir: /home/l-sun/.xmake/cache/packages/2204/b/benchmark/1.6.1/source/benchmark-1.6.1/build_f398c618/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_f0676/fast && /usr/bin/make  -f CMakeFiles/cmTC_f0676.dir/build.make CMakeFiles/cmTC_f0676.dir/build
make[1]: Entering directory '/home/l-sun/.xmake/cache/packages/2204/b/benchmark/1.6.1/source/benchmark-1.6.1/build_f398c618/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_f0676.dir/src.cxx.o
/usr/bin/clang -DHAVE_CXX_FLAG_WD654  -m64  -std=c++11  -Wall  -Wextra  -Wshadow  -Wsuggest-override  -pedantic  -pedantic-errors  -Wshorten-64-to-32  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing  -wd654   -wd654 -MD -MT CMakeFiles/cmTC_f0676.dir/src.cxx.o -MF CMakeFiles/cmTC_f0676.dir/src.cxx.o.d -o CMakeFiles/cmTC_f0676.dir/src.cxx.o -c /home/l-sun/.xmake/cache/packages/2204/b/benchmark/1.6.1/source/benchmark-1.6.1/build_f398c618/CMakeFiles/CMakeTmp/src.cxx
clang-13: error: unknown argument: '-wd654'
clang-13: error: unknown argument: '-wd654'
make[1]: *** [CMakeFiles/cmTC_f0676.dir/build.make:79: CMakeFiles/cmTC_f0676.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/l-sun/.xmake/cache/packages/2204/b/benchmark/1.6.1/source/benchmark-1.6.1/build_f398c618/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_f0676/fast] Error 2


Source file was:
int main() { return 0; }
```

**Comment by L-Sun** [comment]
It may be fixed when set those cmake cache variable in the `benchmark/xmake.lua`. But I don't know how to detect the toolchain here.
https://github.com/xmake-io/xmake-repo/blob/ee5a280779ec1b7fc61815ee936de1586b8a52e1/packages/b/benchmark/xmake.lua#L32-L37

**Comment by waruqi** [comment]
```lua
if package:has_tool("cxx", "clang", "clangxx") then
end
```

**Comment by L-Sun** [comment]
应该是上游的原因
