### ISSUE TITLE
自定义grpc仓库安装失败

### ISSUE THREAD

**Issue by nqf** [xmake-io/xmake-repo#1157]
### Xmake 版本

xmake v2.6.4+202204081556

### 操作系统版本和架构

centos7

### 描述问题

```
-- Installing: /home/qingfeng.nan/.xmake/packages/g/grpc/master/4e0143c97b65425b855ad5fd03038b6a/lib/cmake/protobuf/protobuf-targets-release.cmake
CMake Error at third_party/protobuf/cmake_install.cmake:728 (file):
  file INSTALL cannot find
  "/home/xxx/.xmake/cache/packages/2204/g/grpc/master/source/grpc/build_4e0143c9/third_party/protobuf//home/xxx/.xmake/packages/g/grpc/master/4e0143c97b65425b855ad5fd03038b6a/lib/cmake/protobuf".
Call Stack (most recent call first):
  cmake_install.cmake:2145 (include)


make: *** [Makefile:62: install] Error 1
error: execv(make install) failed(2)
  => install grpc master .. failed
error: install failed!
```

### 期待的结果

安装成功

### 工程配置

```
package("grpc")
set_homepage("https://github.com/grpc/grpc.git")
set_description("The C based gRPC (C++, Python, Ruby, Objective-C, PHP, C#)")
set_license("Apache-2.0 License")

add_urls("https://github.com/grpc/grpc.git")
add_deps("cmake")

on_install(function (package)
    local configs = {}
    table.insert(configs, "-DgRPC_INSTALL=ON")
    table.insert(configs, "-DCMAKE_BUILD_TYPE=Release")
    table.insert(configs, "-DgRPC_BUILD_TESTS=OFF")
    import("package.tools.cmake").install(package, configs)
end)
```

**Comment by xq114** [comment]
configs = {"-DCMAKE_INSTALL_LIBDIR=lib"}

**Comment by waruqi** [comment]
可以提个pr过来

**Comment by xq114** [comment]
这里默认内置CMAKE_INSTALL_LIBDIR为绝对路径这一行为虽然方便了个别几个包，但影响的面太广而且和主流用法不兼容，对后面贡献包的开发者会造成太多困扰了。我建议长痛不如短痛，把默认这个选项去掉，跑一遍ci，我记得当时加这个选项的时候xmake-repo里面还基本是空的，去掉影响面不会很大，我估计最多5个包。 @waruqi

**Comment by waruqi** [comment]
但是现在里面已经有上百个包了，后面进来的包也有可能被影响，改了影响太大，要重跑上百个包的ci 搞不动

而现在需要显式设置 CMAKE_INSTALL_LIBDIR=lib 去修复的包目前却没几个，说明也就百分之几的概率

先还是手动加上好了，而且加了后期真对xmake去掉那个改动加上的这些包也没啥影响

**Comment by xq114** [comment]
> 但是现在里面已经有上百个包了，后面进来的包也有可能被影响，改了影响太大，要重跑上百个包的ci 搞不动
> 
> 而现在需要显式设置 CMAKE_INSTALL_LIBDIR=lib 去修复的包目前却没几个，说明也就百分之几的概率
> 
> 先还是手动加上好了，而且加了后期真对xmake去掉那个改动加上的这些包也没啥影响

我记得有些包引入了cmake内置的GNUInstallDirs，CMAKE_INSTALL_LIBDIR如果没设置的话会自动设置成lib64，从而让xmake找不到。虽说CMAKE_INSTALL_LIBDIR设置为绝对路径可以解决，但直接设置CMAKE_INSTALL_LIBDIR=lib相对路径也能解决，而且在Kitware自己的项目里面他们都是这么用的。

折中的处理办法可以是默认设置CMAKE_INSTALL_LIBDIR=lib而不是绝对路径。我没遇到过任何强制要求CMAKE_INSTALL_LIBDIR设置为绝对路径的包，但遇到过很多强制要求 CMAKE_INSTALL_LIBDIR=lib 为相对路径或者不设置的包，理论上这一改动不会造成什么影响，但对新的包贡献者而言会减轻很多负担；xmake-repo里面比较大的项目、对cmake自定义程度非常高的项目，几乎都要求CMAKE_INSTALL_LIBDIR为相对路径的

**Comment by waruqi** [comment]
> 我记得有些包引入了cmake内置的GNUInstallDirs，CMAKE_INSTALL_LIBDIR如果没设置的话会自动设置成lib64，从而让xmake找不到。虽说CMAKE_INSTALL_LIBDIR设置为绝对路径可以解决，但直接设置CMAKE_INSTALL_LIBDIR=lib相对路径也能解决，而且在Kitware自己的项目里面他们都是这么用的。

最好是先挑出一批  不设置出问题，设置了绝对路径解决的库存包，开个 pr 到ci 上跑下，如果设置到 lib 也能解，我就改下。

**Comment by nqf** [comment]
目前设置 CMAKE_INSTALL_LIBDIR=lib 虽然安装成功了， 但是链接时候出现一堆 undefined reference 错误
```
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: log_linux.cc:(.text+0x1ac): undefined reference to `bool absl::lts_20211102::str_format_internal::FormatArgImpl::Dispatch<int>(absl::lts_20211102::str_format_internal::FormatArgImpl::Data, absl::lts_20211102::str_format_internal::FormatConversionSpecImpl, void*)'
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: log_linux.cc:(.text+0x23a): undefined reference to `bool absl::lts_20211102::str_format_internal::FormatArgImpl::Dispatch<long>(absl::lts_20211102::str_format_internal::FormatArgImpl::Data, absl::lts_20211102::str_format_internal::FormatConversionSpecImpl, void*)'
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: log_linux.cc:(.text+0x251): undefined reference to `absl::lts_20211102::str_format_internal::FormatPack(absl::lts_20211102::str_format_internal::UntypedFormatSpecImpl, absl::lts_20211102::Span<absl::lts_20211102::str_format_internal::FormatArgImpl const>)'
```

**Comment by xq114** [comment]
> 目前设置 CMAKE_INSTALL_LIBDIR=lib 虽然安装成功了， 但是链接时候出现一堆 undefined reference 错误， 我怀疑是链接顺序的问题
> 
> ```
> /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: log_linux.cc:(.text+0x1ac): undefined reference to `bool absl::lts_20211102::str_format_internal::FormatArgImpl::Dispatch<int>(absl::lts_20211102::str_format_internal::FormatArgImpl::Data, absl::lts_20211102::str_format_internal::FormatConversionSpecImpl, void*)'
> /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: log_linux.cc:(.text+0x23a): undefined reference to `bool absl::lts_20211102::str_format_internal::FormatArgImpl::Dispatch<long>(absl::lts_20211102::str_format_internal::FormatArgImpl::Data, absl::lts_20211102::str_format_internal::FormatConversionSpecImpl, void*)'
> /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: log_linux.cc:(.text+0x251): undefined reference to `absl::lts_20211102::str_format_internal::FormatPack(absl::lts_20211102::str_format_internal::UntypedFormatSpecImpl, absl::lts_20211102::Span<absl::lts_20211102::str_format_internal::FormatArgImpl const>)'
> ```

依赖abseil没写，add_deps("abseil")

**Comment by nqf** [comment]
https://github.com/grpc/grpc/blob/master/.gitmodules#L32

**Comment by nqf** [comment]
他会自动下载，因为grpc会编译出好几十个静态库，现在都被安装到lib中，我怀疑生成的那个链接顺序是不对的，所以导致出现错误，xmake有办法调用cmake find_pack 那个东西吗

**Comment by waruqi** [comment]
尽量使用 add_deps("abseil") 让库自己去找了使用，没找到，有些库才会自动切到内置的3rd源码上去编译。

如果非要使用内置的 3rd 库源码编译，那就 add_links 写明所有库的依赖顺序

**Comment by waruqi** [comment]
没看到有多复杂，既然它有链接依赖，那就要走 add_links 配置顺序，又要简单使用，又要顺序对，不配置这些，xmake 又不可能凭空猜出这些库的顺序

**Comment by nqf** [comment]
尝试了一下， 并没有按照预期工作， 可能是我不够了解xmake， 不过grpc 是一个很重要开源库， 我认为xmake 官方仓库应该要支持它

**Comment by xq114** [comment]
> 他会自动下载，因为grpc会编译出好几十个静态库，现在都被安装到lib中，我怀疑生成的那个链接顺序是不对的，所以导致出现错误，xmake有办法调用cmake find_package 那个东西吗

可以，在on_fetch里面写return find_package("cmake::grpc")不过目前xmake-repo中还没有这样写的包，可能需要调一下，你可以先提个pr过来，在pr里面给他调work，这样这个包也能作为后来的包的示例

**Comment by xq114** [comment]
https://github.com/grpc/grpc/blob/master/BUILDING.md#install-after-build

根据这个你得声明gRPC_ABSL_PROVIDER=package等，这样可以让grpc去用xmake已经安装的包

**Comment by waruqi** [comment]
> 尝试了一下， 并没有按照预期工作， 可能是我不够了解xmake， 不过grpc 是一个很重要开源库， 我认为xmake 官方仓库应该要支持它

目前没人力支持，仓库包都是用户按需自己提交 pr 进来

**Comment by xq114** [comment]
> 最好是先挑出一批 不设置出问题，设置了绝对路径解决的库存包，开个 pr 到ci 上跑下，如果设置到 lib 也能解，我就改下。xmake test 分支，我已经改了，可以 ci 上切过去做测试

https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

这个我也不好挑，记不清哪些包用了这个的。不过现在有官方文档了，我们跟官方文档保持一致不会是什么大问题的

**Comment by waruqi** [comment]
> > 最好是先挑出一批 不设置出问题，设置了绝对路径解决的库存包，开个 pr 到ci 上跑下，如果设置到 lib 也能解，我就改下。xmake test 分支，我已经改了，可以 ci 上切过去做测试
> 
> https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
> 
> 这个我也不好挑，记不清哪些包用了这个的。不过现在有官方文档了，我们跟官方文档保持一致不会是什么大问题的

我改了，可以先关注下自己项目包的安装是否有影响

**Comment by nqf** [comment]
> https://github.com/grpc/grpc/blob/master/BUILDING.md#install-after-build
> 
> 根据这个你得声明gRPC_ABSL_PROVIDER=package等，这样可以让grpc去用xmake已经安装的包

 我已经改成用xmake 仓库中有的包了，很遗憾问题仍旧没有解决， 问题出现在 链接顺序， grpc 这个工程会编译出多个 .a 他们之间 有 链接顺序, 我并不熟悉他们之间依赖关系 并且我也不是 lua 经验者， 所以目前只能暂时放下了

**Comment by nqf** [comment]
> 目前没人力支持，仓库包都是用户按需自己提交 pr 进来

非常理解，  但是我认为一些比较常用包还是应该维护一下， 这样有利于你项目的推广， 我虽然也想解决这个问题， 但是无奈能力有限， 搞了两天也没成功， 尽力了， 希望以后有人会添加进来吧
