### ISSUE TITLE
cannot recognize version string of 4 segments

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#118]
### 描述讨论详情

https://github.com/g-truc/glm/releases

这个版本号是0.9.9.8有4位，xmake无法识别

报错信息：

<details>
<summary>Details</summary>

error: @programdir\core\main.lua:284: ...gramdir\core\sandbox\modules\import\core\base\semver.lua:88: unable to select version 
for range 'latest'
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:792]: in function 'raise'
    [...gramdir\core\sandbox\modules\import\core\base\semver.lua:88]: in function 'select'
    [@programdir\actions\require\impl\package.lua:260]: in function '_select_package_version'
    [@programdir\actions\require\impl\package.lua:353]: in function '_load_package'
    [@programdir\actions\require\impl\package.lua:395]: in function '_load_packages'
    [@programdir\actions\require\impl\package.lua:741]: in function 'load_packages'
    [@programdir\actions\require\impl\package.lua:759]: in function 'install_packages'
    [@programdir\actions\require\install.lua:162]: in function 'install'
    [@programdir\actions\require\main.lua:111]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:282]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:792: in function 'raise'
        @programdir\core\main.lua:284: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

</details>

**Comment by waruqi** [comment]
目前用的 https://github.com/uael/sv 这个 语义版本库，也是人家帮忙贡献的，人家基于 那个语义版本规范做的解析。

1.0.0+334
1.2.3-alpha.3

这种可以，major minor alter build/patch 这几个分段，但四位数 1.0.0.3 这种不支持

你可以给这个库提issues，我这边暂时没精力改动这块

**Comment by xq114** [comment]
> 目前用的 [uael/sv](https://github.com/uael/sv) 这个 语义版本库，也是人家帮忙贡献的，人家基于 那个语义版本规范做的解析。
> 
> 1.0.0+334
> 1.2.3-alpha.3
> 
> 这种可以，major minor alter build/patch 这几个分段，但四位数 1.0.0.3 这种不支持
> 
> 你可以给这个库提issues，我这边暂时没精力改动这块

这种四位的版本号不是semantic versioning，感觉不太适合放到sv里面去。这个issue可以先放着吧，现在还有折中的办法，可能这个库以后迁移到semantic versioning了就不需要改现有代码了

**Comment by waruqi** [comment]
可以在package定义里面的版本列表改成语义版本，然后自己处理下版本后 再传给add_urls的version 就行了，具体可以参考sqilte3这个包定义的配置
