### ISSUE TITLE
Support for packages for iphoneos and android

### ISSUE THREAD

**Issue by mwik** [xmake-io/xmake-repo#12]
There are currently no packages that support any other platforms than linux, macos and windows. Is there anything that prevents other platforms to be supported or how would one go about to add support? I tried adding on_install("iphoneos", ... but then I need a way for xmake to pass on the detected compiler and SDK to the sub-make. Is there a way to do that already? I can not find any documentation about that.

Thanks for your effort on xmake. It is truly brilliant. And I think iphone and android package support would be a killer feature :)

**Comment by waruqi** [comment]
Currently only the tbox package is supported on all platforms. As long as the package is maintained with xmake.lua, it can easily support other platforms, including cross toolchain. Of course, the source code itself needs to support these platforms.

I will add support for iphoneos/android in the next xmake version, passing the build environment for these platforms to autoconf/cmake..

If you are interested, you can pay attention to https://github.com/xmake-io/xmake/tree/master/xmake/modules/package/tools, or help me improve them to pass iphoneos/android build environment

**Comment by waruqi** [comment]
I will support it, you can see https://github.com/xmake-io/xmake/issues/399 to know lastest progress.

**Comment by waruqi** [comment]
Done
