### ISSUE TITLE
Extend 3rd party packages with an xrepo package / add to a target that is requiring it?

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake-repo#122]
I notice when using `sfml` from conan or vcpkg that using it statically means we need to link some libraries to our own targets.

Instead of that, can we write a small xmake-repo package that does this for the user?

ie create a package that just: 
1. Installs a package from another package manager
2. Adds links (or anything else) to the target requiring this new package

So users can do this....
#### app/xmake.lua
```
add_requires("sfml")

target("test")
    set_kind("binary")
    add_packages("sfml")
```
.... instead of this:
#### app/xmake.lua
```
add_requires("conan::sfml/2.5.1@bincrafters/stable", { alias = "sfml" })

target("test")
    set_kind("binary")
    add_packages("sfml")
    if is_plat("windows") then 
        add_links("opengl32", "winmm", "gdi32", "user32", "Advapi32") 
    elseif is_plat("linux") then
        add_links("blah", "blah", "blah")
    elseif if_plat("macosx") then
        add_links("blah", "blah", "blah") 
        -- etc etc
    end
```

**Comment by waruqi** [comment]
This small package definition may be unstable. It depends on whether the user has installed conan/vcpkg/homebrew. It may only be solved by creating multiple repositories, for example: xmake-repo-conan, xmake-repo-vcpkg  . .

In addition, for the same package, the conan/vcpkg and xmake built-in packages may have different extended configuration options, for example: ʻadd_requires("sfml", {conan_configs={}, xmake_configs={}})`?

Although this seems to be a very good feature, it can slightly simplify the user's use of dependent libraries, but it will increase our maintenance cost of the repository.

Now that there are a lot of third-party package repositories, maybe xmake will support other package management tools such as pacman/apt/pkg/dnf later, which will cause us to be unable to maintain more package definitions

**Comment by paul-reilly** [comment]
Ah yes, by not choosing an "official" package manager this would be a maintenance burden for multiple package managers. Good point.

I think there could be room to do this a different way:

eg
- when using `sfml` statically we always need to link our targets against certain libs
- when using `wxwidgets` shared libs on Windows we always need to define "WX_USING_DLL"

#### Rule: when using X on platform Y we *always* need Z

Since these requirements are independent of any package manager, they could be implemented in a more universal way, eg using something like the xmake rules system:

#### somewhere.lua
```
rule("package.sfml.static")
    on_build(function(target)
      if is_plat("windows") then 
          target:add("links", "opengl32", "winmm", "gdi32", "user32", "Advapi32") 
      elseif is_plat("linux") then
          target:add("links", "blah", "blah", "blah")
      elseif is_plat("linux") then
          target:add("links", "blah", "blah", "blah")
      end    
    end)

rule("package.wxwidgets.shared")
    on_build(function(target)
      if is_plat("windows") then 
          target:add("defines", "WX_USING_DLL") 
      end
    end)
```

#### app/xmake.lua
```
target("myexe")
    add_packages("sfml", "wxwidgets")
    add_package_rules("sfml") --<-- can use all, some or omit for none. Continue with warning where no rule found
```

So users could contribute these general rulesets and xmake can become even easier to use for new C++ users!

**Comment by waruqi** [comment]
> add_package_rules("sfml")

If xmake maintains configuration rules for each package, this will increase xmake's own lua script files, more and more. It will no longer be light enough. Although most packages may have general rules, there are still many packages whose rules are different, so it is not limited and not general enough.

And it will make us disperse our time and energy from maintaining xmake-repo. If our xmake-repo has maintained enough c++ packages so that users no longer need to rely on conan/vcpkg to satisfy most dependent libraries, this problem will not exist.

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake-repo/blob/228d09c04abfc7d84782e2a87eee1c81940396ef/packages/s/sfml/xmake.lua#L43-L45

This line prevented user to use static linking, which is similar to the case in https://github.com/xmake-io/xmake-repo/issues/100. A rewrite to sfml/xmake.lua could work, once that is finished we can use built-in static sfml library without resorting to 3rd party conan/vcpkg install.
