### ISSUE TITLE
How can I specify a package with detect.find_package or detect.find_tool?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#125]
### 描述讨论详情

比如一个包依赖一个比较大的sdk（例如qt等）或者tool（例如gfortran/perl等），这时需要用到`find_package`或者`find_tool`，如果探测不到安装就会失败。这个时候需要输出提示信息，有没有办法只输出提示不输出错误信息呢？

ci上面肯定是没有预先安装这些包的，这个需要如何处理呢？

另外，在用户自定义detect_path的情况下，这个包还需要提供一个config接收用户设置的detect_path，这样用户用的时候就要声明两遍detect_path。请问xmake有没有一种缓存机制，在第一次find_package成功之后后续再次使用find_package时不再需要声明detect_path？

**Comment by waruqi** [comment]
> 比如一个包依赖一个比较大的sdk（例如qt等）或者tool（例如gfortran/perl等），这时需要用到find_package或者find_tool，如果探测不到安装就会失败。这个时候需要输出提示信息，有没有办法只输出提示不输出错误信息呢？

？没明白。。就是只提示 不报错？就算不报错，之后的安装不是还是会报错失败。。

> ci上面肯定是没有预先安装这些包的，这个需要如何处理呢？

一个包依赖了 qt sdk，ci上又没去装，那肯定会失败，要么ci上装上qt sdk，要么不要装这个包

> 另外，在用户自定义detect_path的情况下，这个包还需要提供一个config接收用户设置的detect_path，这样用户用的时候就要声明两遍detect_path。请问xmake有没有一种缓存机制，在第一次find_package成功之后后续再次使用find_package时不再需要声明detect_path？

find_package 原本就会缓存结果，我不知道你说的缓存是啥，detect_path是啥

**Comment by xq114** [comment]
不好意思，缓存我之前没仔细看文档不知道有，第三条现在看可以忽略；第二条看起来好像解决不了。

这里第一条的意思是因为缺少必要的包失败的时候会显示一长串stacktrace而不是类似"package xxx is not supported on your os"这样的比较简单的信息，不过这个似乎也并不是一个很重要的问题，可以暂时忽略

**Comment by waruqi** [comment]
> 这里第一条的意思是因为缺少必要的包失败的时候会显示一长串stacktrace而不是类似"package xxx is not supported on your os"这样的比较简单的信息，不过这个似乎也并不是一个很重要的问题，可以暂时忽略

只有 on_install("macosx") 没指定的平台，才能够预先在 on_install 开始之前有简短的 not support 提示，其他复杂环境导致的不支持，只能在 on_install 过程中报错失败了，顶多是在 on_install 开头加 assert find_xxx 检测，提前报错，

**Comment by waruqi** [comment]
> 第二条看起来好像解决不了。

ci上自己装上不就好了，既然包用到。。
