### ISSUE TITLE
LuaJIT package test failing on Manjaro + WSL|Ubuntu

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake-repo#1264]
### Xmake Version

xmake v2.6.7+dev.2132430

### Operating System Version and Architecture

Manjaro x64 21.2.6 | Ubuntu 20.04.4 (in Win 10.0.19044 WSL)

### Describe Bug

The test for the package is failing on the `os.vrun` command:
```lua
    on_test(function (package)
        if package:is_plat(os.host()) then
            os.vrun("luajit -e \"print('hello xmake!')\"")
        end
        assert(package:has_cfuncs("lua_pcall", {includes = "luajit.h"}))
    end)
```

### Expected Behavior

The test passes. 

### Additional Information and Error Logs

```
error: exec(luajit -e "print('hello xmake!')") failed(-1)
```
The package works in Windows 10. Does not work in Manjaro and WSL|Ubuntu.

The problem appears to be the last commit to the package: 8a83cee02dcbe385b8921a89d22e943223754baa

Reverting to the previous commit fixes. I don't know LuaJIT internals so don't want to make an uneducated PR to revert the previous commit, which must have been made for a reason.

**Comment by waruqi** [comment]
@see [1121](https://github.com/xmake-io/xmake-repo/pull/1121)

This is also intended to fix crashes under x86.

**Comment by shuax** [comment]
我这边是64位就要用vm_x64.dasc，要不多用github actions测试吧。

**Comment by waruqi** [comment]
> 我这边是64位就要用vm_x64.dasc，要不多用github actions测试吧。

我测试了下，那个 patch 确实会导致 linux x64 下 崩溃。

I've tested it and the patch does crash under linux x64.

**Comment by shuax** [comment]
> > 我这边是64位就要用vm_x64.dasc，要不多用github actions测试吧。
> 
> 你这里是什么系统，如果不是 linux ，可以根据系统做下区分

我好像是在pve还是ubuntu测试的，以及win11。

**Comment by waruqi** [comment]
> > > 我这边是64位就要用vm_x64.dasc，要不多用github actions测试吧。
> > 
> > 
> > 你这里是什么系统，如果不是 linux ，可以根据系统做下区分
> 
> 我好像是在pve还是ubuntu测试的，以及win11。

我这 ubuntu 也是必崩的，回退你那个 patch 就正常了。

**Comment by waruqi** [comment]
I have reverted it.
