### ISSUE TITLE
Apply multiple local patches to multiple versions simoutaneously

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#132]
### 你在什么场景下需要该功能？

安装一个包需要很多patch（大概10个，来自vcpkg，已预先下载到本地），按文档中讲的方法一个一个加，首先是每一个都要算一遍sha256十分麻烦（git其实已经可以保证filehash了不需要再算。或许xmake可以类似vcpkg提供一个接口xmake hash <file>/<filelist>算一下sha256？），其次是xmake.lua十分冗长，再次从上游更新新的patch还要修改xmake.lua可维护性不好，最后一个patch可以在多个版本反复利用不需要在声明patch时一定要某个确定版本。

其中有些功能可能已经有了，但文档中没有提到，因此不太清楚该怎么写

### 描述可能的解决方案

```lua
add_patches("*",             -- 作用于所有版本，"> 5.0"这种能有就更好了
			{"patches/**"})  -- 接收一个table，应用匹配的所有patch，自动加os.scriptdir()
```

考虑到前向兼容，可以不动原接口，加一个新接口`add_localpatches`?

### 其他信息

vcpkg里面给很多库本来只支持linux的扩展到全平台，还有一些停止维护的库也焕发新生了，中间就是大量的patch，简化patch的使用可以方便很多库直接移植过来。

**Comment by waruqi** [comment]
> git其实已经可以保证filehash了不需要再算。或许xmake可以类似vcpkg提供一个接口xmake hash /算一下sha256？

hash还是要算的，patch又不一定是从git 下载下来的，很多都是curl下载的，怎么保证完整性？

直接用命令 `shasum -a 256 xxx` 算，或者用xmake提供的 `xmake l hash.sha256 file` 算

> 次是xmake.lua十分冗长，再次从上游更新新的patch还要修改xmake.lua可维护性不好，最后一个patch可以在多个版本反复利用不需要在声明patch时一定要某个确定版本。

这个反而是必须的，否则上游一改动patch，居然还能直接验证就用，非常不安全。相当于用户的包安装，完全可以被上游直接的改动所影响，而不用经过xmake-repo的review
如果上游的patch搞了bug，就全用户跪，更极端点，上游的域名劫持导致下载了恶意patch，都不需要验证，导致恶意控制用户的机器都是可能的，便利性很重要，但安全性和可靠性更重要，不能以损失安全性为代价来提高便利性。


如果确实有太多的patches导致单个xmake.lua过长，可以用includes吧patches隔离到单独patches/xmake.lua 去独立维护，可以参考 curl包的versions维护，https://github.com/xmake-io/xmake-repo/blob/master/packages/l/libcurl/xmake.lua


> patch可以在多个版本反复利用不需要在声明patch时一定要某个确定版本。

如果patches不多，单独声明几次也没啥，如果确实很多需要复用，可以用刚说的方式，includes独立维护patches列表，里面弄个function去wrap下就好了，比如 add_patch_for_versions(patchfile, sha256, versions_list) 里面for each versions加一下就好了，也就几行代码

**Comment by waruqi** [comment]
至于 add_patches 的版本语义 比配多个，确实能一定程度上简化下配置，我之后会考虑加上，不过需要等等了，看这边的时间安排

如果是内置的patches文件，也可以考虑lua模式匹配的方式一次应用多个，我之后也会考虑

**Comment by xq114** [comment]
这里指的是手动把patch下载下来传到xmake-repo里面，而不在用的时候去下载，这样就不用验证了，更新新版本的时候手动去更新维护

**Comment by waruqi** [comment]
> patch可以在多个版本反复利用不需要在声明patch时一定要某个确定版本。

这个我dev改进过了，支持语义版本

```lua
add_patches("1.1.x", url, sha256)
add_patches(">1.1.0 <=1.8.0", url, sha256)
add_patches("~1.2.3", url, sha256)
```

> 这里指的是手动把patch下载下来传到xmake-repo里面，而不在用的时候去下载，这样就不用验证了，更新新版本的时候手动去更新维护

针对本地patch file，不设置sha256就行了，原本就可以。

```lua
add_patches("1.1.x", patchfile)
```

**Comment by xq114** [comment]
> 但本地patch不要太多，否则xmake-repo会更臃肿，能用remote patch尽量用远程的 + sha256，否则都塞xmake-repo会 导致整体拉取变慢。

万一上游把文件改了一下，sha256验证不过，所有用户都无法安装这个包了，也不是一件好事。除非先把patch存到网盘或者另一个github repo，然后按需下载？

**Comment by waruqi** [comment]
目前原始包，都是走的上游url，通常是官方的一般不会改，否则homebrew的模式也不会能正常运行到现在

如果到时候真有不稳定的上游，导致部分包跪了，肯定会有用户保障，到时候修复下，或者切到xmake-mirror镜像组维护都可以

一些包和补丁如果上游下载不稳定，我都会在 https://github.com/xmake-mirror 开镜像维护，gitee/gitlab也有
