### ISSUE TITLE
xrepo 通过 cmake vs2019 构建 x86平台 出错

### ISSUE THREAD

**Issue by yecate** [xmake-io/xmake-repo#133]
### 描述问题
xrepo 通过 cmake vs2019  构建 x86平台出错.
例如:
xrepo install -p windows -a x86 mhook

### 错误信息
log:
> C:\Users\yecate>xrepo install -p windows -a x86 mhook
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> mhook 2.5.1
please input: y (y/n)
 => install mhook 2.5.1 .. failed
if you want to get verbose errors, please see:
  -> C:\Users\yecate\AppData\Local\.xmake\cache\packages\2011\m\mhook\2.5.1\installdir.failed\logs\install.txt
error: install failed!
error: execv(xmake require --extra={system=false} mhook) failed(-1)

install.txt:
> 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
生成启动时间为 2020/11/14 22:02:26。
项目“C:\Users\yecate\AppData\Local\.xmake\cache\packages\2011\m\mhook\2.5.1\source\mhook-2.5.1\build_F71F0975\mhook.sln”在节点 1 上(Rebuild 个目标)。
C:\Users\yecate\AppData\Local\.xmake\cache\packages\2011\m\mhook\2.5.1\source\mhook-2.5.1\build_F71F0975\mhook.sln.metaproj : error MSB4126: 指定的解决方案配置“Release|Win32”无效。请使用 Configuration 和 Platform 属性指定有效的解决方案配置(例如 MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU")，或者将这些属性保留为空，以使用默认的解决方案配置。 [C:\Users\yecate\AppData\Local\.xmake\cache\packages\2011\m\mhook\2.5.1\source\mhook-2.5.1\build_F71F0975\mhook.sln]
已完成生成项目“C:\Users\yecate\AppData\Local\.xmake\cache\packages\2011\m\mhook\2.5.1\source\mhook-2.5.1\build_F71F0975\mhook.sln”(Rebuild 个目标)的操作 - 失败。
生成失败。
>“C:\Users\yecate\AppData\Local\.xmake\cache\packages\2011\m\mhook\2.5.1\source\mhook-2.5.1\build_F71F0975\mhook.sln”(Rebuild 目标) (1) ->
(ValidateSolutionConfiguration 目标) -> 
  C:\Users\yecate\AppData\Local\.xmake\cache\packages\2011\m\mhook\2.5.1\source\mhook-2.5.1\build_F71F0975\mhook.sln.metaproj : error MSB4126: 指定的解决方案配置“Release|Win32”无效。请使用 Configuration 和 Platform 属性指定有效的解决方案配置(例如 MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU")，或者将这些属性保留为空，以使用默认的解决方案配置。 [C:\Users\yecate\AppData\Local\.xmake\cache\packages\2011\m\mhook\2.5.1\source\mhook-2.5.1\build_F71F0975\mhook.sln]

cmake生成的工程文件:
>	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Release|x64 = Release|x64
		MinSizeRel|x64 = MinSizeRel|x64
		RelWithDebInfo|x64 = RelWithDebInfo|x64
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{8ADFB526-F225-37E2-AB6F-744C54131AF2}.Debug|x64.ActiveCfg = Debug|x64
		{8ADFB526-F225-37E2-AB6F-744C54131AF2}.Debug|x64.Build.0 = Debug|x64
		{8ADFB526-F225-37E2-AB6F-744C54131AF2}.Release|x64.ActiveCfg = Release|x64
		{8ADFB526-F225-37E2-AB6F-744C54131AF2}.Release|x64.Build.0 = Release|x64
		{8ADFB526-F225-37E2-AB6F-744C54131AF2}.MinSizeRel|x64.ActiveCfg = MinSizeRel|x64
		{8ADFB526-F225-37E2-AB6F-744C54131AF2}.MinSizeRel|x64.Build.0 = MinSizeRel|x64
		{8ADFB526-F225-37E2-AB6F-744C54131AF2}.RelWithDebInfo|x64.ActiveCfg = RelWithDebInfo|x64
		{8ADFB526-F225-37E2-AB6F-744C54131AF2}.RelWithDebInfo|x64.Build.0 = RelWithDebInfo|x64
		{87934FAE-C16A-3B01-B5C3-9232B0A84FF9}.Debug|x64.ActiveCfg = Debug|x64
		{87934FAE-C16A-3B01-B5C3-9232B0A84FF9}.Release|x64.ActiveCfg = Release|x64
		{87934FAE-C16A-3B01-B5C3-9232B0A84FF9}.MinSizeRel|x64.ActiveCfg = MinSizeRel|x64
		{87934FAE-C16A-3B01-B5C3-9232B0A84FF9}.RelWithDebInfo|x64.ActiveCfg = RelWithDebInfo|x64
		{275F5E21-D275-31F0-9F0F-6632A12ACD18}.Debug|x64.ActiveCfg = Debug|x64
		{275F5E21-D275-31F0-9F0F-6632A12ACD18}.Debug|x64.Build.0 = Debug|x64
		{275F5E21-D275-31F0-9F0F-6632A12ACD18}.Release|x64.ActiveCfg = Release|x64
		{275F5E21-D275-31F0-9F0F-6632A12ACD18}.Release|x64.Build.0 = Release|x64
		{275F5E21-D275-31F0-9F0F-6632A12ACD18}.MinSizeRel|x64.ActiveCfg = MinSizeRel|x64
		{275F5E21-D275-31F0-9F0F-6632A12ACD18}.MinSizeRel|x64.Build.0 = MinSizeRel|x64
		{275F5E21-D275-31F0-9F0F-6632A12ACD18}.RelWithDebInfo|x64.ActiveCfg = RelWithDebInfo|x64
		{275F5E21-D275-31F0-9F0F-6632A12ACD18}.RelWithDebInfo|x64.Build.0 = RelWithDebInfo|x64
		{C8724E0F-2D19-399C-BAF5-BC050FFE7006}.Debug|x64.ActiveCfg = Debug|x64
		{C8724E0F-2D19-399C-BAF5-BC050FFE7006}.Debug|x64.Build.0 = Debug|x64
		{C8724E0F-2D19-399C-BAF5-BC050FFE7006}.Release|x64.ActiveCfg = Release|x64
		{C8724E0F-2D19-399C-BAF5-BC050FFE7006}.Release|x64.Build.0 = Release|x64
		{C8724E0F-2D19-399C-BAF5-BC050FFE7006}.MinSizeRel|x64.ActiveCfg = MinSizeRel|x64
		{C8724E0F-2D19-399C-BAF5-BC050FFE7006}.MinSizeRel|x64.Build.0 = MinSizeRel|x64
		{C8724E0F-2D19-399C-BAF5-BC050FFE7006}.RelWithDebInfo|x64.ActiveCfg = RelWithDebInfo|x64
		{C8724E0F-2D19-399C-BAF5-BC050FFE7006}.RelWithDebInfo|x64.Build.0 = RelWithDebInfo|x64
	EndGlobalSection
### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：v2.3.8
- xmake运行平台：windows
- xmake目标平台：windows
- vs版本: 2019

### 其他信息
cmake 使用 vs2019 构建项目的时候 arch 需要通过 -A 指定
>* Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".

通过 修改 package.tools.cmake 添加 -A Win32 测试成功
>  table.insert(argv, '-A')
    table.insert(argv, 'Win32')    
    table.insert(argv, '..')
    -- generate build file
    os.vrunv("cmake", argv, {envs = opt.envs or buildenvs(package)})

log:
>C:\Users\yecate>xrepo install -p windows -a x86 mhook
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> mhook 2.5.1
please input: y (y/n)
  => install mhook 2.5.1 .. ok

**Comment by waruqi** [comment]
更新到xmake dev版本再试下

**Comment by yecate** [comment]
dev 可以了
