### ISSUE TITLE
提升 openssl 的安装速度、体验

### ISSUE THREAD

**Issue by idealvin** [xmake-io/xmake-repo#1355]
### 你在什么场景下需要该功能？

xrepo 安装 openssl 时，默认安装了 openssl 的文档 (man pages)，导致安装非常慢，对于绝大部分用户而言，在本机安装 openssl 文档是没有用处的。

### 描述可能的解决方案

安装openssl时不安装其文档，[这里](https://stackoverflow.com/questions/47136654/is-there-a-way-to-install-openssl-without-installing-man-pages)有个解决方案，用 `make install_sw` 取代 `make install`。

```sh
make install_sw
```

**Comment by waruqi** [comment]
改进过了
