### ISSUE TITLE
Mariadb-connector-c shared/static not working properly

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake-repo#1363]
### Xmake Version

2.6.9

### Operating System Version and Architecture

Windows 11

### Describe Bug

When using mariadb-connector-c in static, it links fine but launching the program fails because it's missing "libmariadb.dll". The same behavior occurs when setting shared to true.

### Expected Behavior

Static linking doesn't require a dll.
Shared linking copies libmariadb.dll to the bin directory.

**Comment by waruqi** [comment]
you can open a pr to improve it. https://github.com/xmake-io/xmake-repo/blob/master/packages/m/mariadb-connector-c/xmake.lua

**Comment by waruqi** [comment]
see https://github.com/xmake-io/xmake-repo/pull/1365
