### ISSUE TITLE
Imguizmo issues since xmake.lua modification

### ISSUE THREAD

**Issue by TNtube** [xmake-io/xmake-repo#1384]
### Xmake Version

v2.6.9+HEAD.22ecc0156

### Operating System Version and Architecture

Windows 11

### Describe Bug

I'm using the ImGuizmo for a personnal project with xmake, and the module worked so far, until #1305 where it seems to get broked. Everything install, compile and run well, but i'm getting a runtime bug that only appear when ImGuizmo is getting compiled with a differents ImGui's binaries that are used on the project. I didn't changed anything on my xmake.lua before and after the bug, so I suppose that is because of #1305.

Here is my xmake.lua : [link](https://github.com/TNtube/Cardia/blob/69f0ead017e247069227738eda4d16358d7c48cd/xmake.lua#L24)

Am I doing something wrong ?

Thanks

### Expected Behavior

ImGuizmo should compile using same binaries as the imgui used in the project (since imgui is required to use ImGuizmo)

**Comment by waruqi** [comment]
Can you add -vD argument and reinstall them, then let me see the logs.

you can also check imgui version.

**Comment by waruqi** [comment]
Also, if possible. Please provide a reproducible minimal example

**Comment by waruqi** [comment]
The patch for #1305 is to improve the consistency of the versions of imguizmo and imgui and should not cause problems.

**Comment by TNtube** [comment]
Sorry for the delay. I fixed it by updating both imgui and imguizmo.
