### ISSUE TITLE
Integrate python launcher for windows in python package

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#139]
### 你在什么场景下需要该功能？

新版icu库在windows上依赖python launcher（py.exe）才能安装

### 描述可能的解决方案

在xmake-mirror打包的python版本里面加入py.exe（3.3以上版本提供）

### 其他信息

xmake-mirror的python版本也可以升级一下，2.7.18是python2最后一个版本，3.8.x（目前3.8.6）是最后一个支持Windows 7的版本

**Comment by waruqi** [comment]
> 在xmake-mirror打包的python版本里面加入py.exe（3.3以上版本提供）

3.3 话，不是现有 3.7 版本应该也带着的吧？

**Comment by waruqi** [comment]
我开了两分支，2.7.18/3.8.6 你可以帮忙直接提pr到这两分支上
https://github.com/xmake-mirror/python-releases

**Comment by xq114** [comment]
> 3.3 话，不是现有 3.7 版本应该也带着的吧？

然而现有的3.7里面没有，我也很困惑。官网上面只有installer（还有一个embedded版本，功能不全并且不带python launcher）可以下载，tar.gz的版本是怎么下载的呢

**Comment by waruqi** [comment]
> > 3.3 话，不是现有 3.7 版本应该也带着的吧？
> 
> 然而现有的3.7里面没有，我也很困惑。官网上面只有installer（还有一个embedded版本，功能不全并且不带python launcher）可以下载，tar.gz的版本是怎么下载的呢

用installer装完手动提取的，然后打成tar.gz

**Comment by xq114** [comment]
是这样，python launcher默认和python没有装在一起，需要手动复制一下。另外，xmake.lua中为什么需要重新装一遍pip和setuptools呢，这两个已经内置在安装包里了，重新装一遍有特殊用意吗

**Comment by waruqi** [comment]
> 是这样，python launcher默认和python没有装在一起，需要手动复制一下

那就在新版本python的tar.gz包中 直接一起打进去就好

> 另外，xmake.lua中为什么需要重新装一遍pip和setuptools呢，这两个已经内置在安装包里了，重新装一遍有特殊用意吗

之前没怎么细看，如果已经有 那就忽略掉吧

**Comment by xq114** [comment]
`add_resources()`这个接口也支持semver吗？这里2和3可以共用一个resource其实

**Comment by waruqi** [comment]
> `add_resources()`这个接口也支持semver吗？这里2和3可以共用一个resource其实

暂时还不支持

**Comment by waruqi** [comment]
> `add_resources()`这个接口也支持semver吗？这里2和3可以共用一个resource其实

我刚加上支持了，不过没测试过，按理问题不大，你可以试试
