### ISSUE TITLE
Copying folder 'share' on tools.cmake install

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#148]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
很多时候一个包A用cmake安装，装完之后除了bin、include、lib之外还有一个share文件夹；包B也用cmake且依赖A，需要指定A的位置然后引用shared里面的文件。现有cmake安装默认不带share，就需要手动copy share文件夹，比较麻烦，是否可以考虑在cmake安装中默认加入share？

**Comment by waruqi** [comment]
这个可以加上

**Comment by waruqi** [comment]
我加上了
