### ISSUE TITLE
测试本地包的命令不能用相对路径

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake-repo#1480]
### Xmake 版本

2.7.1

### 操作系统版本和架构

windows 11

### 描述问题

![image](https://user-images.githubusercontent.com/97490782/190041383-1f2fbbb5-0bf3-4f1f-961d-a420ded26ffb.png)
如图，按照readme里面写的指定scripts/test.lua。直接提示无法导入模块

### 期待的结果

不应该提示无法导入吧

**Comment by waruqi** [comment]
xmake-repo 放到独立目录，确保上层没任何 xmake.lua 干扰。。
