### ISSUE TITLE
用readme的命令创建包时生成的目录不对

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake-repo#1481]
### Xmake 版本

2.7.1

### 操作系统版本和架构

windows 11

### 描述问题

![image](https://user-images.githubusercontent.com/97490782/190042857-91836fd4-a2c4-4d94-8b9e-346b46159468.png)
如图，生成之后，packages 咋出现在上一级目录了，是bug还是有意这样设计的呢？

### 期待的结果

packages 应该是在当前目录吧

**Comment by waruqi** [comment]
切到 xmake-repo 执行
