### ISSUE TITLE
xrepo install ffmpeg failed

### ISSUE THREAD

**Issue by iujakchu** [xmake-io/xmake-repo#1528]
### Xmake 版本

xmake v2.7.2+HEAD.d881936

### 操作系统版本和架构

Arch 5.15.68.1-microsoft-standard-WSL2

### 描述问题

```xrepo install ffmpeg``` 
失败
在windows平台运行没有问题，并且没有编译行为
```
updating repositories .. ok
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> yasm 1.3.0 [from:ffmpeg]
  -> ffmpeg 5.1.2
please input: y (y/n/m)

  => install yasm 1.3.0 .. ok
  => install ffmpeg 5.1.2 .. failed

/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode_h264.o): in function `vaapi_encode_h264_configure':
vaapi_encode_h264.c:(.text.unlikely+0x350): undefined reference to `vaQueryVendorString'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode_h265.o): in function `vaapi_encode_h265_get_encoder_caps':
vaapi_encode_h265.c:(.text.unlikely+0x234): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode_h265.c:(.text.unlikely+0x2a1): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `vaapi_encode_wait':
vaapi_encode.c:(.text+0x6c): undefined reference to `vaSyncBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x9f): undefined reference to `vaSyncSurface'
/usr/sbin/ld: vaapi_encode.c:(.text+0xad): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0xda): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `vaapi_encode_free_output_buffer':
vaapi_encode.c:(.text+0x14a): undefined reference to `vaDestroyBuffer'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `vaapi_encode_make_packed_header':
vaapi_encode.c:(.text+0x215): undefined reference to `vaCreateBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x26b): undefined reference to `vaCreateBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x2e7): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0x31b): undefined reference to `vaErrorStr'
if you want to get more verbose errors, please see:
  -> /home/yann/.xmake/cache/packages/2210/f/ffmpeg/5.1.2/installdir.failed/logs/install.txt
error: install failed!
error: execv(xmake require -j 14 --extra={system=false} ffmpeg) failed(255)
```

### 期待的结果

可以运行

### 附加信息和错误日志

/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode_h264.o): in function `vaapi_encode_h264_configure':
vaapi_encode_h264.c:(.text.unlikely+0x350): undefined reference to `vaQueryVendorString'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode_h265.o): in function `vaapi_encode_h265_get_encoder_caps':
vaapi_encode_h265.c:(.text.unlikely+0x234): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode_h265.c:(.text.unlikely+0x2a1): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `vaapi_encode_wait':
vaapi_encode.c:(.text+0x6c): undefined reference to `vaSyncBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x9f): undefined reference to `vaSyncSurface'
/usr/sbin/ld: vaapi_encode.c:(.text+0xad): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0xda): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `vaapi_encode_free_output_buffer':
vaapi_encode.c:(.text+0x14a): undefined reference to `vaDestroyBuffer'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `vaapi_encode_make_packed_header':
vaapi_encode.c:(.text+0x215): undefined reference to `vaCreateBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x26b): undefined reference to `vaCreateBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x2e7): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0x31b): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `vaapi_encode_make_param_buffer':
vaapi_encode.c:(.text+0x3cf): undefined reference to `vaCreateBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x433): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `vaapi_encode_alloc_output_buffer':
vaapi_encode.c:(.text+0x4c2): undefined reference to `vaCreateBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x52e): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0x567): undefined reference to `vaDestroyBuffer'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `vaapi_encode_issue':
vaapi_encode.c:(.text+0xa16): undefined reference to `vaDestroyBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x1052): undefined reference to `vaBeginPicture'
/usr/sbin/ld: vaapi_encode.c:(.text+0x107a): undefined reference to `vaRenderPicture'
/usr/sbin/ld: vaapi_encode.c:(.text+0x109a): undefined reference to `vaEndPicture'
/usr/sbin/ld: vaapi_encode.c:(.text+0x10c7): undefined reference to `vaDestroyBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x14fc): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0x1607): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0x1638): undefined reference to `vaEndPicture'
/usr/sbin/ld: vaapi_encode.c:(.text+0x164a): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0x17ff): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `ff_vaapi_encode_receive_packet':
vaapi_encode.c:(.text+0x3e3d): undefined reference to `vaMapBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x3f0a): undefined reference to `vaUnmapBuffer'
/usr/sbin/ld: vaapi_encode.c:(.text+0x44f8): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0x45a5): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text+0x45e6): undefined reference to `vaUnmapBuffer'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `ff_vaapi_encode_init':
vaapi_encode.c:(.text.unlikely+0x1f3): undefined reference to `vaMaxNumProfiles'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x24e): undefined reference to `vaQueryConfigProfiles'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x25c): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x324): undefined reference to `vaProfileStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x3f8): undefined reference to `vaMaxNumEntrypoints'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x432): undefined reference to `vaQueryConfigEntrypoints'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x44d): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x501): undefined reference to `vaEntrypointStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x5db): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x5ea): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x77e): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x78c): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1028): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1037): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x10cd): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x10de): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1478): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x148b): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1885): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1893): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x19ec): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x19fa): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1a94): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1aa3): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1ba9): undefined reference to `vaGetConfigAttributes'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1bbf): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1c9c): undefined reference to `vaCreateConfig'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1caa): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1ed7): undefined reference to `vaCreateContext'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x1ee9): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x208d): undefined reference to `vaSyncBuffer'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_encode.o): in function `ff_vaapi_encode_close':
vaapi_encode.c:(.text.unlikely+0x2154): undefined reference to `vaDestroyContext'
/usr/sbin/ld: vaapi_encode.c:(.text.unlikely+0x2178): undefined reference to `vaDestroyConfig'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_decode.o): in function `ff_vaapi_decode_destroy_buffers':
vaapi_decode.c:(.text+0x3e): undefined reference to `vaDestroyBuffer'
/usr/sbin/ld: vaapi_decode.c:(.text+0x8f): undefined reference to `vaDestroyBuffer'
/usr/sbin/ld: vaapi_decode.c:(.text+0x9c): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0xe3): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_decode.o): in function `vaapi_decode_make_config':
vaapi_decode.c:(.text+0x198): undefined reference to `vaMaxNumProfiles'
/usr/sbin/ld: vaapi_decode.c:(.text+0x1c7): undefined reference to `vaQueryConfigProfiles'
/usr/sbin/ld: vaapi_decode.c:(.text+0x33a): undefined reference to `vaCreateConfig'
/usr/sbin/ld: vaapi_decode.c:(.text+0x431): undefined reference to `vaQuerySurfaceAttributes'
/usr/sbin/ld: vaapi_decode.c:(.text+0x475): undefined reference to `vaQuerySurfaceAttributes'
/usr/sbin/ld: vaapi_decode.c:(.text+0x5dc): undefined reference to `vaDestroyConfig'
/usr/sbin/ld: vaapi_decode.c:(.text+0x643): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0x674): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0x8d0): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0x936): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_decode.o): in function `ff_vaapi_decode_make_param_buffer':
vaapi_decode.c:(.text+0xa09): undefined reference to `vaCreateBuffer'
/usr/sbin/ld: vaapi_decode.c:(.text+0xa6b): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_decode.o): in function `ff_vaapi_decode_make_slice_buffer':
vaapi_decode.c:(.text+0xb3c): undefined reference to `vaCreateBuffer'
/usr/sbin/ld: vaapi_decode.c:(.text+0xba2): undefined reference to `vaCreateBuffer'
/usr/sbin/ld: vaapi_decode.c:(.text+0xc63): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0xc94): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0xcc7): undefined reference to `vaDestroyBuffer'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_decode.o): in function `ff_vaapi_decode_issue':
vaapi_decode.c:(.text+0xd3a): undefined reference to `vaBeginPicture'
/usr/sbin/ld: vaapi_decode.c:(.text+0xd58): undefined reference to `vaRenderPicture'
/usr/sbin/ld: vaapi_decode.c:(.text+0xd7c): undefined reference to `vaRenderPicture'
/usr/sbin/ld: vaapi_decode.c:(.text+0xd96): undefined reference to `vaEndPicture'
/usr/sbin/ld: vaapi_decode.c:(.text+0xde3): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0xe1e): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0xe49): undefined reference to `vaEndPicture'
/usr/sbin/ld: vaapi_decode.c:(.text+0xe56): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0xe83): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0xeab): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_decode.o): in function `ff_vaapi_common_frame_params':
vaapi_decode.c:(.text+0xf75): undefined reference to `vaDestroyConfig'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_decode.o): in function `ff_vaapi_decode_uninit':
vaapi_decode.c:(.text+0xfc8): undefined reference to `vaDestroyContext'
/usr/sbin/ld: vaapi_decode.c:(.text+0xfd6): undefined reference to `vaErrorStr'
/usr/sbin/ld: vaapi_decode.c:(.text+0x1010): undefined reference to `vaDestroyConfig'
/usr/sbin/ld: vaapi_decode.c:(.text+0x101e): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavcodec.a(vaapi_decode.o): in function `ff_vaapi_decode_init':
vaapi_decode.c:(.text+0x1100): undefined reference to `vaCreateContext'
/usr/sbin/ld: vaapi_decode.c:(.text+0x113b): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_map_frame':
hwcontext_vaapi.c:(.text+0x158): undefined reference to `vaSyncSurface'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x194): undefined reference to `vaCreateImage'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1b9): undefined reference to `vaMapBuffer'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x2e3): undefined reference to `vaErrorStr'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x31c): undefined reference to `vaUnmapBuffer'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x32d): undefined reference to `vaDestroyImage'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x35a): undefined reference to `vaGetImage'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x38d): undefined reference to `vaDeriveImage'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x3c7): undefined reference to `vaErrorStr'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x3f5): undefined reference to `vaErrorStr'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x421): undefined reference to `vaErrorStr'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x46f): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_unmap_frame':
hwcontext_vaapi.c:(.text+0x57b): undefined reference to `vaUnmapBuffer'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x599): undefined reference to `vaDestroyImage'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x5be): undefined reference to `vaErrorStr'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x5eb): undefined reference to `vaErrorStr'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x63e): undefined reference to `vaPutImage'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x663): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_frames_init':
hwcontext_vaapi.c:(.text+0xa9b): undefined reference to `vaDeriveImage'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0xada): undefined reference to `vaDestroyImage'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0xbc3): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_pool_alloc':
hwcontext_vaapi.c:(.text+0xed6): undefined reference to `vaCreateSurfaces'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0xf63): undefined reference to `vaErrorStr'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0xf9d): undefined reference to `vaDestroySurfaces'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_buffer_free':
hwcontext_vaapi.c:(.text+0x1011): undefined reference to `vaDestroySurfaces'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1035): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_frames_get_constraints':
hwcontext_vaapi.c:(.text+0x11c2): undefined reference to `vaQuerySurfaceAttributes'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x11ff): undefined reference to `vaQuerySurfaceAttributes'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x13af): undefined reference to `vaErrorStr'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x13e5): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_device_init':
hwcontext_vaapi.c:(.text+0x141f): undefined reference to `vaMaxNumImageFormats'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1456): undefined reference to `vaQueryImageFormats'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x15bb): undefined reference to `vaQueryVendorString'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_device_free':
hwcontext_vaapi.c:(.text+0x1759): undefined reference to `vaTerminate'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x176a): undefined reference to `XCloseDisplay'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_device_connect':
hwcontext_vaapi.c:(.text+0x17d0): undefined reference to `vaSetErrorCallback'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x17e2): undefined reference to `vaSetInfoCallback'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x17f6): undefined reference to `vaInitialize'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1843): undefined reference to `vaErrorStr'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_device_derive':
hwcontext_vaapi.c:(.text+0x18bd): undefined reference to `vaGetDisplayDRM'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vaapi.o): in function `vaapi_device_create':
hwcontext_vaapi.c:(.text+0x19d5): undefined reference to `XOpenDisplay'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x19e9): undefined reference to `vaGetDisplay'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x19fd): undefined reference to `XDisplayName'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1a3d): undefined reference to `vaSetDriverName'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1aaf): undefined reference to `vaGetDisplayDRM'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1b74): undefined reference to `XDisplayName'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1be0): undefined reference to `XOpenDisplay'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1bf7): undefined reference to `XDisplayName'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1c3e): undefined reference to `vaErrorStr'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1c66): undefined reference to `vaTerminate'
/usr/sbin/ld: hwcontext_vaapi.c:(.text+0x1caa): undefined reference to `XDisplayName'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vdpau.o): in function `vdpau_device_create':
hwcontext_vdpau.c:(.text+0x721): undefined reference to `XOpenDisplay'
/usr/sbin/ld: hwcontext_vdpau.c:(.text+0x736): undefined reference to `XDisplayString'
/usr/sbin/ld: hwcontext_vdpau.c:(.text+0x742): undefined reference to `XDefaultScreen'
/usr/sbin/ld: hwcontext_vdpau.c:(.text+0x755): undefined reference to `vdp_device_create_x11'
/usr/sbin/ld: hwcontext_vdpau.c:(.text+0x839): undefined reference to `XDisplayName'
/usr/sbin/ld: /home/yann/.xmake/packages/f/ffmpeg/5.1.2/79a4b6207c10432e87adadcd4a309f6d/lib/libavutil.a(hwcontext_vdpau.o): in function `vdpau_device_free':
hwcontext_vdpau.c:(.text+0x8aa): undefined reference to `XCloseDisplay'
collect2: error: ld returned 1 exit status

**Comment by waruqi** [comment]
那是因为 ffmpeg 自动探测到了 vaapi 和 vdpac 加速，启用了相关模块，但是 link 时候，没 link 上对应的库导致。

具体是 ffmpeg 内 bin link 还是 on_test 里面 link 失败，我看不到，你没给全 logs 。

目前我暂时禁用了这两模块，等 merge 后可以再试试

https://github.com/xmake-io/xmake-repo/pull/1529

如果要更好地处理，得在 xmake-repo 加上 vaapi 和 vdpau 包，以及实现 on_fetch 返回 links 信息，然后在 ffmpeg 包里去 add_deps 它们才行，有兴趣可以提 pr 过来改进，不行就暂时禁用这两先凑活着用

**Comment by waruqi** [comment]
merge了，再试试，xrepo update-repo

**Comment by iujakchu** [comment]
感谢，问题解决了
