### ISSUE TITLE
windows上用libhv，带mbedtls时有些链接符号找不到

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake-repo#1535]
### Xmake 版本

2.7.2

### 操作系统版本和架构

windows 11

### 描述问题

```
xrepo install -f "mbedtls=true" libhv
```
![image](https://user-images.githubusercontent.com/97490782/196016945-c985e0df-a09b-402b-b0ad-19b6e542f9bf.png)
网上搜了下貌似是需要链接advapi32.lib
```
https://blog.csdn.net/caoshangpa/article/details/52814706
```
![image](https://user-images.githubusercontent.com/97490782/196016976-91f6eed4-22ee-45ab-ab7c-b5dc1994d871.png)

### 期待的结果

正确地链接mbedtls

**Comment by waruqi** [comment]
提个pr过来，改下包
