### ISSUE TITLE
SFML unmatched checksum

### ISSUE THREAD

**Issue by SFGrenade** [xmake-io/xmake-repo#1557]
### Xmake Version

v2.7.1+master.5d982b979

### Operating System Version and Architecture

Windows 10 Enterprise LTSC 21H2

### Describe Bug

When trying to build a project, i get an error while trying to install the sfml library.

### Expected Behavior

I expect the sfml library to be installed.

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")

set_project("Game-Of-Life")

if is_plat("windows") then
    set_languages("cxxlatest")

    -- bruh
    add_cxflags("/Zc:__cplusplus")
    add_cxflags("/Zc:preprocessor")
else
    set_languages("cxx20")
end

add_requires("fmt")
add_requires("spdlog")
add_requires("sfml")

set_warnings("allextra")

if is_mode("debug") then
    add_defines("DEBUG")

    set_symbols("debug")

    set_optimize("fastest")
end

if is_mode("release") then
    add_defines("NDEBUG")

    add_cxflags("-fomit-frame-pointer")

    set_optimize("fastest")
end

target("Game-Of-Life")
    set_kind("binary")

    add_files("src/**.cpp")
    add_headerfiles("src/**.h")

    add_packages("fmt")
    add_packages("spdlog")
    add_packages("sfml")

    after_build(function (target)
        import("core.project.config")
        os.cp("Resources", path.join(config.buildir(), config.plat(), config.arch(), config.mode()))
    end)
    after_install(function (target)
        import("core.project.config")
        os.cp("Resources", target.installdir())
    end)

```

### Additional Information and Error Logs

```
PS E:\Documents\Projects\Game-Of-Life> xmake  
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.33.31630
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> sfml 2.5.1 [vs_runtime:"MT"]
please input: y (y/n/m)

  => download https://github.com/xmake-mirror/build-artifacts/releases/download/sfml-2.5.1/windows-x64-vc143-9a922774ed0f414bb9efd13bbcfe36fe.7z .. failed

we can also download these packages manually:
  - https://github.com/xmake-mirror/build-artifacts/releases/download/sfml-2.5.1/windows-x64-vc143-9a922774ed0f414bb9efd13bbcfe36fe.7z
to the local search directories: 
  - windows-x64-vc143-9a922774ed0f414bb9efd13bbcfe36fe.7z
and we can run `xmake g --pkg_searchdirs=/xxx` to set the search directories.
error: unmatched checksum!
```

**Comment by waruqi** [comment]
can you try `xrepo update-repo`?

**Comment by SFGrenade** [comment]
works, probably should've just used the windows installer instead of powershell script.
thanks!

**Comment by waruqi** [comment]
Today I updated the sfml package and it automatically triggered an update to the pre-build repository binary. But your local repository hasn't been updated yet, so you'll need to update it manually.

**Comment by SirLynix** [comment]
Didn't you make it so xmake would install the package manually (build it) if precompiled download fail?

**Comment by waruqi** [comment]
> Didn't you make it so xmake would install the package manually (build it) if precompiled download fail?

I also remember adding this feature, but I don't know why it didn't take effect.

**Comment by waruqi** [comment]
oh, it only for installation stage, not for download stage.

**Comment by SFGrenade** [comment]
from what i gather of the error log, it couldn't verify the source download

**Comment by waruqi** [comment]
> from what i gather of the error log, it couldn't verify the source download

The upstream binary artifacts have been updated causing this problem. Its sha256 does not match the sha256 saved in the package manifest file of your local repository.

> Today I updated the sfml package and it automatically triggered an update to the pre-build repository binary. But your local repository hasn't been updated yet, so you'll need to update it manually.
