### ISSUE TITLE
包catch2在linux上无法运行

### ISSUE THREAD

**Issue by Aizaixyq** [xmake-io/xmake-repo#1565]
### Xmake 版本

v2.7.2+202210100435

### 操作系统版本和架构

5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

使用时报错：~/code/catch2$ xmake
[ 25%]: cache compiling.release src/lc779.cpp
[ 50%]: linking.release catch2
error: /usr/bin/ld: /home/fei-chen/.xmake/packages/c/catch2/3.1.0/d31f6498c47d4e55b3f4b18fdc8d053b/lib/libCatch2Main.a(catch_main.cpp.o): in function `main.cold':
catch_main.cpp:(.text.unlikely+0x4): undefined reference to `Catch::Session::~Session()'
/usr/bin/ld: /home/fei-chen/.xmake/packages/c/catch2/3.1.0/d31f6498c47d4e55b3f4b18fdc8d053b/lib/libCatch2Main.a(catch_main.cpp.o): in function `main':
catch_main.cpp:(.text.startup+0x38): undefined reference to `Catch::Session::Session()'
/usr/bin/ld: catch_main.cpp:(.text.startup+0x4a): undefined reference to `Catch::Session::~Session()'
/usr/bin/ld: catch_main.cpp:(.text.startup+0x7d): undefined reference to `Catch::Session::applyCommandLine(int, char const* const*)'
/usr/bin/ld: catch_main.cpp:(.text.startup+0x8c): undefined reference to `Catch::Session::run()'
/usr/bin/ld: /home/fei-chen/.xmake/packages/c/catch2/3.1.0/d31f6498c47d4e55b3f4b18fdc8d053b/lib/libCatch2Main.a(catch_main.cpp.o): in function `_GLOBAL__sub_I_catch_main.cpp':
catch_main.cpp:(.text.startup+0xc0): undefined reference to `Catch::LeakDetector::LeakDetector()'
/usr/bin/ld: catch_main.cpp:(.text.startup+0xc7): undefined reference to `Catch::LeakDetector::~LeakDetector()'
collect2: error: ld returned 1 exit status

### 期待的结果

其实catch2提供了两种使用方式，还有一种直接下载release中的cpp和hpp文件导入就可以运行

**Comment by waruqi** [comment]
贴下 代码 和 配置，或者给个可复现的 example 工程

**Comment by Aizaixyq** [comment]
> 贴下 代码 和 配置，或者给个可复现的 example 工程

就是官方给的第一个例子: https://github.com/catchorg/Catch2

其他的我没动，用xmake create后把给的例子贴在mian.cpp，在lua文件中add_requires 还有add_package后，在构建过程中报的错，看错误内容应该是缺东西

后来下载了release里面的hpp和cpp，放到工程目录下就能用了

**Comment by waruqi** [comment]
我这里可以，没什么问题，可以自己 -vD 编译检查下 link flags，或者贴下

**Comment by Aizaixyq** [comment]
[test.txt](https://github.com/xmake-io/xmake-repo/files/9847008/test.txt)

好的，这是加 -vD后输出的信息

**Comment by waruqi** [comment]
更新下仓库再试试

```console
xrepo update-repo
xrepo remove --all -y catch2
xmake f -c
xmake -rv
```

**Comment by Aizaixyq** [comment]
按照你给的操作，现在已经可以了，成功构建
