### ISSUE TITLE
failed to install vulkansdk

### ISSUE THREAD

**Issue by RnMss** [xmake-io/xmake-repo#1660]
### Xmake Version

2.5.4+202105160132

### Operating System Version and Architecture

Darwin Kernel Version 21.6.0

### Describe Bug

cannot install package "vulkansdk"
error: cannot import module: detect.sdks.find_vulkansdk, not found!

### Expected Behavior

should install package "vulkansdk"

### Project Configuration

run `xrepo install vulkansdk`

### Additional Information and Error Logs

```
error: cannot import module: detect.sdks.find_vulkansdk, not found!
error: execv(xmake require -j 12 --extra={system=false} vulkansdk) failed(255)
```

**Comment by xq114** [comment]
Your xmake installation is outdated. Try `xmake update`

**Comment by xq114** [comment]
Btw vulkansdk requires a manual installation (with environment variable `VULKAN_SDK` set), xmake just finds it from your system.
