### ISSUE TITLE
MNN 编译通过后，使用时提示 libmnn.a: No such file or directory

### ISSUE THREAD

**Issue by yflin1** [xmake-io/xmake-repo#1665]
### Xmake 版本

2.6.9

### 操作系统版本和架构

Ubuntu18.04 LTS

### 描述问题

在项目里加入 xmake-repo 里的 MNN，指定版本 2.2.2，在 xmake f 时MNN编译正常，但在 xmake -j 18 xxx 来编译项目时提示：
```
/home/xxx/.xmake/packages/m/mnn/2.2.2/e28ccab85c9c494fa320891dbfa6da78/lib/libmnn.a: No such file or directory
```

发现 MNN 编译出来的库是 libMNN.a，而非 libmnn.a

### 期待的结果

MNN 编译出来的库改为 libMNN.a

**Comment by waruqi** [comment]
```console
xrepo update-repo
xrepo remove --all mnn
xmake f -c
xmake
```

更新仓库重装下试试

**Comment by yflin1** [comment]
可以了, 谢谢
