### ISSUE TITLE
System libraries

### ISSUE THREAD

**Issue by MoAlyousef** [xmake-io/xmake-repo#167]
### Is your feature request related to a problem? Please describe.

Xmake package management currently tries to build the world. For example, pulling fltk currently requires pulling a whole lot of x11 libraries and building them from source. This makes building fltk which should take about a minute take around 10 minutes on linux systems. And this also requires some significant disk space. On a clean instance of docker, this currently amount to about a gigabyte of dependencies and build/intermediate artifacts. It also redownloads python, cmake, make etc even when these are already installed and in system paths. 

### Describe the solution you'd like

Builds depending on system libraries like X11 for example should be acquired by users from the system’s package manager. Also many distros already have most devel packages preinstalled. 

### Describe alternatives you've considered

Vcpkg for example provides messages to the user when system packages are required.
This is from the sfml port for example: 
```cmak
if(VCPKG_TARGET_IS_LINUX)
    message(STATUS "SFML currently requires the following libraries from the system package manager:\n    libudev\n    libx11\n    libxrandr\n    opengl\n\nThese can be installed on Ubuntu systems via apt-get install libx11-dev libxrandr-dev libxi-dev libudev-dev libgl1-mesa-dev")
endif()

```

### Additional context

This makes building any non-significant package quite time consuming and with more points of failure.

**Comment by waruqi** [comment]
By default, xmake tries to use the system library first, and will compile and install it itself if it cannot be found.

If libx11 is already installed on your system, but it is not detected. There should be other problems, we need to improve it.


You can run `xmake l find_package libx11` in non-project directory and let me see the output.

In addition, please tell me your linux system version and the contents of `pkg-config --cflags --ldflags x11`

**Comment by MoAlyousef** [comment]
Currently xmake works well. However since Ubuntu 20.04 doesn’t ship development headers by default, unlike other distros, xmake will try to download from source and build. 
I’m suggesting changing the default behavior. 
In my opinion I think it should either fail early or xmake could automatically call the system package manager.
Something like add_deps("libxinerama") should (if it didn’t find the library) either call the system package manager automatically or fail with a message saying “libXinerama is needed by ... package".  
The idea is that building those libraries doesn’t really make sense for xmake, they already have distro maintainers, they’re already built and are available in the distro repositories and are easily downloadable via the systems package manager. 
This makes the build significantly faster.

**Comment by waruqi** [comment]
> Currently xmake works well. However since Ubuntu 20.04 doesn’t ship development headers by default, unlike other distros, xmake will try to download from source and build.

We only need to improve find_package so that the system libx11 library can be found normally on ubuntu20.04, even if there is no header file.

> I’m suggesting changing the default behavior.

The default behavior cannot be changed arbitrarily, otherwise it will affect other users. In addition, I think there is no problem with the default behavior of checking system libraries by default.

> In my opinion I think it should either fail early or xmake could automatically call the system package manager.

We can add `add_requires("libx11",{system = true})` to force the use of the system library. If the system library is not found, xmake will directly prompt failure

```lua
add_requires("fltk")
add_requires("libx11", {system = true}) -- Override the internal package dependency configuration
...
```

**Comment by MoAlyousef** [comment]
The `{ system = true }` is already implemented?

**Comment by waruqi** [comment]
> The `{ system = true }` is already implemented?

Yes, this configuration has always been provided.

https://xmake.io/#/package/remote_package?id=disable-system-library

**Comment by MoAlyousef** [comment]
Thank you
