### ISSUE TITLE
Add mirror for google gn (generate ninja)

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#168]
### 描述讨论详情
google的skia依赖gn，然而gn的官方下载地址（ https://chrome-infra-packages.appspot.com/dl/gn/gn/windows-amd64/+/git_revision:e55664a01f6ee92762210d0c01b13552f8117e11 , https://chrome-infra-packages.appspot.com/dl/gn/gn/mac-amd64/+/git_revision:e55664a01f6ee92762210d0c01b13552f8117e11 等）被墙了，xmake-mirror能否提供一份备份？

**Comment by waruqi** [comment]
我把你加到 xmake-mirror 里面了，你可以直接提交新repo进去
