### ISSUE TITLE
Adding more backend options for imgui

### ISSUE THREAD

**Issue by AidanSun05** [xmake-io/xmake-repo#1687]
### Is your feature request related to a problem? Please describe.

I have a project that I am thinking about converting to use Xmake, and it uses the Dear ImGui library. However, it uses the SDL2+OpenGL3 backends, which I cannot seem to install through xrepo.

The imgui package offers a few set configurations, like GLFW+OpenGL3 and SDL2+SDL Renderer, but these may not work for all projects (such as mine).

### Describe the solution you'd like

The imgui package should provide additional backend config options (such as SDL2+OpenGL3).

**Comment by waruqi** [comment]
It has GLFW + vulkan too. https://github.com/xmake-io/xmake-repo/blob/a54337a96d3aa2e6b9fbfd5f71aacbd59e02f27a/packages/i/imgui/xmake.lua#L30

If you want to get more backend, you can open a pr to add them.
