### ISSUE TITLE
Crypto++ version 8.7.0

### ISSUE THREAD

**Issue by IanBullard** [xmake-io/xmake-repo#1697]
### Xmake Version

2.7.4

### Operating System Version and Architecture

Windows 10

### Describe Bug

Crypto++ version 8.7.0 is now available but not included in xrepo.

It's not an easy update because [Crypto++ CMake](https://github.com/noloader/cryptopp-cmake/) is used to create the package, but it is no longer maintained past 8.6.0.,

### Expected Behavior

Crypto++ version 8.7.0 should be available.

**Comment by waruqi** [comment]
maybe it need be ported xmake.lua in xmake-repo.

**Comment by IanBullard** [comment]
I'll take a shot it, maybe I can figure it out.
