### ISSUE TITLE
build protobuf error

### ISSUE THREAD

**Issue by jason-fan** [xmake-io/xmake-repo#17]
### 描述问题

尝试构建protobuf的package,内容如下：
package("protobuf")

    set_kind("binary")
    set_homepage("https://developers.google.com/protocol-buffers/")
    set_description("Google's data interchange format")

    if is_host("macosx", "linux", "windows") then
        add_urls("https://github.com/protocolbuffers/protobuf/releases/download/v$(version)/protobuf-cpp-$(version).zip")

        add_versions("3.8.0", "91ea92a8c37825bd502d96af9054064694899c5c7ecea21b8d11b1b5e7e993b5")
    end
    on_install("windows", function (package)
        os.cd("cmake")
        import("package.tools.cmake").install(package)
    end)
 
    on_install("linux", "macosx", function (package)
        import("package.tools.autoconf").install(package)
    end)

### 错误信息
放到相应的 xmake-repo位置，然后执行:
 xmake l -v -D scripts/test.lua protobuf  

出现错误：
!fetch protobuf-3.8.0 failed!
### 相关环境

xmake version 2.2.7
win10
vs2017
zlib 1.2.11

请帮忙看看是那里写的不对，谢谢！

**Comment by waruqi** [comment]
protobuf-cpp 和 protoc 我加进去了dev里面，不过还在跑ci，还没完善好。。后期在这两里面跟进吧。。等ci上完全跑通后，再用。

等有时间，我会改进下。。你也可以尝试改进下，提个pr进来，on_test我已经加进去了。。
https://github.com/xmake-io/xmake-repo/blob/dev/packages/p/protobuf-cpp/xmake.lua
https://github.com/xmake-io/xmake-repo/blob/dev/packages/p/protoc/xmake.lua

**Comment by jason-fan** [comment]
感谢！还是需要抽空把文档梳理下，比如这个我不明白为什么需要加个add_links("protobuf"),package的规则还不太明白。

另外，如果不是安装package,而是制作基于某个third library建的xmake.lua，用户可以按自己的项目需要，动态地集成编译，这样不会“污染”系统环境，这会不会是另一种思路？

    再次感谢waruqi百忙中的回复。

**Comment by waruqi** [comment]
刚改进了下 on_test，现在 这边初步测了下 linux/ mac/ win都可以了，ci上也基本过了，你可以`xmake repo update`更新下repo后试试。。

然后项目里面写法大概如下：

```lua
add_requires("protobuf-cpp")
target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("protobuf-cpp")
```

接着执行编译：xmake

> 还是需要抽空把文档梳理下，比如这个我不明白为什么需要加个add_links("protobuf"),package的规则还不太明白。

因为protobuf装完，lib下有多个库，libprotobuf.a libprotobuf-lite.a，如果不加add_links，就会自动检测链接所有lib库，但这两个是只需要选择其中一个link就行了，那么就手动设置下这个，指定集成protobuf时候(`add_packages("")`的时候)需要实际链接的库名。  也可以用于调整link的依赖顺序。


> 另外，如果不是安装package,而是制作基于某个third library建的xmake.lua，用户可以按自己的项目需要，动态地集成编译，这样不会“污染”系统环境，这会不会是另一种思路？

现在你在xmake-repo里面集成的protobuf，就是动态下载编译和集成的。。

**Comment by jason-fan** [comment]
太棒了，我试了一下，原来是类似运行在sandbox里，对系统的安装包和依赖库不会造成污染，类似放在~/.xmake/packages，在~.xmake/cache对下载的包也进行了加速，如果是需要选择动态库和静态库的支持，就要完善这个package文件了吧？

**Comment by waruqi** [comment]
是的，通过add_configs添加配置参数，在外面的add_requires里面传参控制，可以看下 
https://github.com/xmake-io/xmake/issues/284

**Comment by waruqi** [comment]
包的制作文档我写了下，有兴趣的话，可以看下：https://xmake.io/#/zh-cn/package/remote_package?id=%e6%b7%bb%e5%8a%a0%e5%8c%85%e5%88%b0%e4%bb%93%e5%ba%93
