### ISSUE TITLE
vk-bootstrap依赖的vulkan-headers与本地安装的vulkansdk似乎存在冲突

### ISSUE THREAD

**Issue by freestriker** [xmake-io/xmake-repo#1733]
### Xmake 版本

2.7.5

### 操作系统版本和架构

Windows 10 专业版22H2 19045.2364

### 描述问题

使用xmake project -k vsxmake -v -a x64可以生成vs解决方案，但似乎指向的vulkansdk头文件路径有问题。
在vs22中编译会出现C1083无法打开包括文件: “vulkan/vulkan_core.h”: No such file or directory，但是在ide内可以通过转到文档<vulkan/vulkan_core.h>(F12)转到自行安装的vulkansdk下的头文件。在引入vulkan/vulkan_core.h时智能提示会提示两个目录，一个是自行安装的sdk头文件目录，一个是xmake的packages文件夹内的vulkan-headers的包，可能产生了冲突。vulkan-headers包似乎是被vk-bootstrap包所依赖，尝试修改vk-bootstrap的manifest.txt，去除vulkan-headers依赖：
{
    mode = "release",
    license = "MIT",
    envs = {
        PATH = {
            "bin"
        }
    },
    configs = {
        vs_runtime = "MT",
        shared = false,
        pic = true,
        debug = false
    },
    arch = "x64",
    deps = {
        cmake = {
            version = "3.24.2",
            buildhash = "5430022e3acc47008f94857b498c53c6"
        }
    },
    plat = "windows",
    repo = {
        name = "xmake-repo",
        url = "https://gitee.com/tboox/xmake-repo.git",
        branch = "master",
        commit = "ff9a90c83a7a2e97c9217c44ed4bfaf840564ca5"
    },
    artifacts = {
        installdir = [[D:\Data\Xmake\Data\.xmake\packages\v\vk-bootstrap\v0.5\3ce9d4f627ff43cda300acdca638953c]],
        remotedir = [[C:\Users\runneradmin\AppData\Local\.xmake\packages\v\vk-bootstrap\v0.5\3ce9d4f627ff43cda300acdca638953c]]
    },
    description = "Vulkan Bootstrapping Iibrary.",
    name = "vk-bootstrap",
    version = "v0.5"
}
并删除项目文件夹下的.xmake文件夹并重新生成解决方案，报错依旧。
查阅https://github.com/charles-lunarg/vk-bootstrap/issues/141  发现可以通过VK_BOOTSTRAP_VULKAN_HEADER_DIR 指定vk-bootstrap的vulkan头目录。并检查其cmake发现它在构建时似乎会先检查本机vulkansdk头目录和VK_BOOTSTRAP_VULKAN_HEADER_DIR ，否则就使用vulkan-headers，我不确定xmake仓库中的vk-bootstrap是否是类似流程。

### 期待的结果

在引入vk-bootstrap时自动检测本地vulkansdk头文件，决定是否依赖vulkan-headers；或手动选择：依赖vulkan-headers或指定VK_BOOTSTRAP_VULKAN_HEADER_DIR或使用本地vulkansdk头文件

### 工程配置

AirEngine
--xmake.lua
--Runtime
----xmake.lua
--Demo
----xmake.lua

AirEngine下lua：
set_project("AirEngine")

add_rules("mode.debug", "mode.release")

add_requires("boost", {configs = {all = true}})

add_packages("boost")

set_languages("cxx17")
add_cxxflags("cl::/Zc:__cplusplus /permissive-")
add_defines("NOMINMAX")

includes("Runtime", "Demo")

Runtime下lua：
add_requires("vulkansdk", {system = true})
add_requires("vk-bootstrap")

target("Runtime")
    add_rules("qt.shared")
    add_files("**.cpp")
    add_headerfiles(("**.hpp"))
    add_packages("vulkansdk")
    add_packages("vk-bootstrap")
    add_defines("DLL_EXPORTS")

Demo下lua：
target("Demo")
    add_rules("qt.widgetapp")
    add_files("**.cpp")
    add_headerfiles(("**.hpp"))
    add_deps("Runtime")

**Comment by waruqi** [comment]
先不要在 vs 里面测，直接命令行编译 带上 -vD 给我一份完整 logs

**Comment by waruqi** [comment]
> 查阅https://github.com/charles-lunarg/vk-bootstrap/issues/141 发现可以通过VK_BOOTSTRAP_VULKAN_HEADER_DIR 指定vk-bootstrap的vulkan头目录。并检查其cmake发现它在构建时似乎会先检查本机vulkansdk头目录和VK_BOOTSTRAP_VULKAN_HEADER_DIR ，否则就使用vulkan-headers，我不确定xmake仓库中的vk-bootstrap是否是类似流程。

只要在包里加上 on_fetch 优先找你系统的版本就行了。。https://github.com/xmake-io/xmake-repo/blob/73e9b8786a982a0c7175485c518e5a3a76b710d6/packages/v/vulkan-headers/xmake.lua#L22

你可以提个 pr 过来，改进下查找。

参考 https://github.com/xmake-io/xmake-repo/blob/73e9b8786a982a0c7175485c518e5a3a76b710d6/packages/g/glu/xmake.lua#L6

加上 {includedirs = ""} 返回

**Comment by waruqi** [comment]
> 直接编译：
PS D:\Projects\AirEngine> xmake f --qt=C:\Software\QT -c -vD

这不叫编译，这只是配置，编译都没跑 `xmake -vD`

**Comment by waruqi** [comment]
> -external:ID:\Data\Xmake\Data.xmake\packages\v\vulkan-headers\1.3.231+1\0f4cca7c08ae41efa25d8d31c27328a8\include

我看编译里面，路径已经在了的，可以看下这个路径下 有没有 vulkan/vulkan_core.h，有点的应该能找到才对

**Comment by waruqi** [comment]
还有既然你装了 vulkansdk 了，，不是有专门的 `add_requires("vulkansdk")` 包么，干嘛不用。

**Comment by waruqi** [comment]
> 同时用vk-bootstrap和vulkansdk时就有两份头文件的问题

就算有两份，顶多也是找错一份头文件而已，导致头文件版本不匹配，不应该出现 vulkan/vulkan_core.h not found

**Comment by waruqi** [comment]
> "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe" -c -nologo -O2 -fp:fast -std:c++17 -ID:\Projects\AirEngine\build.gens\Demo\windows\x64\release\rules\qt\ui -DNOMINMAX -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -D_WINDOWS -DBOOST_ALL_NO_LIB /EHsc -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include\QtGui -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include\QtGui\6.2.4 -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include\QtGui\6.2.4\QtGui -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include\QtWidgets -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include\QtWidgets\6.2.4 -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include\QtWidgets\6.2.4\QtWidgets -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include\QtCore -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include\QtCore\6.2.4 -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include\QtCore\6.2.4\QtCore -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\include -external:W0 -external:IC:\Sofiware\QT6.2.4\6.2.4\msvc2019_64\mkspecs\win32-msvc -external:W0 -external:ID:\Data\Xmake\Data.xmake\packages\b\boost\1.81.0\d0477794ba584a25a469eb3aa7232fc8\include /Zc:__cplusplus /permissive- /Zc:__cplusplus /permissive- -DNDEBUG -Fobuild.objs\Demo\windows\x64\release\Demo\main.cpp.obj Demo\main.cpp
checking for flags (cl_sourceDependencies) ... ok
cl.exe "/sourceDependencies" "D:\Data\Xmake\Temp.xmake\230111_6AC68E04B9674550845C1123091BB060.json"
error: @programdir\modules\private\async\runjobs.lua:256: @programdir\modules\private\action\build\object.lua:91: @programdir\modules\core\tools\cl.lua:648: main.cpp
D:\Projects\AirEngine\Demo../Runtime/Core/Manager/GraphicDeviceManager.hpp(3): fatal error C1083: 无法打开包括文件: “vulkan/vulkan_core.h”: No such file or directory


你这个是 main.cpp 里面报错的，而编译 main.cpp ，你的 flags 里面完全没有 vulkan 相关的 includedirs 。。

你确定 add_packages vulkan 相关的包，设置到 main.cpp 对应的 target 了？

**Comment by waruqi** [comment]
当然不会，默认继承，会污染子 target，导出各种用不到的 includedirs ，导致各种冲突。

想集成，自己配置 `add_packages("vulkansdk", {public = true})`
