### ISSUE TITLE
Developing packages: how to force detect changes and rebuild?

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake-repo#177]
So if I have:

```lua
add_repositories("./foo foo")
```

And I am developing a package locally, what is the correct way to get the changes in the package detected for a rebuild every time after a change? Is it...

```lua
xmake repo update
xmake f -cv
```

?

**Comment by waruqi** [comment]
Sorry, I forgot to reply. For issues related to xmake, please report to xmake/issues as much as possible.

You need uninstall the previous installed package and clean cache.

```console
xmake repo -u
xmake require --uninstall your_package
xmake f -c 
```

**Comment by paul-reilly** [comment]
No worries, thanks for the info! I'll post non-package issues in the main xmake repo in future.
