### ISSUE TITLE
Add a way to test on_fetch snippet within a package

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#1782]
### 你在什么场景下需要该功能？

在编写package的on_install时可以利用 `xmake l scripts/test.lua xxx` 来测试，但 on_fetch 没有好的测试方法

### 描述可能的解决方案

添加一个 `xmake l scripts/test.lua --fetch xxx`，仅测试能否从系统查找到包

**Comment by waruqi** [comment]
好了
