### ISSUE TITLE
添加package：rlottie

### ISSUE THREAD

**Issue by DreamOfIce** [xmake-io/xmake-repo#1830]
### 你在什么场景下需要该功能？

最近项目用到了这个包，希望能添加进xmake的存储库中
简介：一个开源的跨平台lottie渲染库
源码：https://github.com/Samsung/rlottie

### 描述可能的解决方案

将rlottie添加到存储库中

### 描述你认为的候选方案

看了下cmakefile并不复杂，写一份纯xmake构建文件应该不太难？
另外rlottie的依赖freetype pixman rapidjson stb都已经收录，要不考虑改为引用现有包？

**Comment by waruqi** [comment]
> 看了下cmakefile并不复杂，写一份纯xmake构建文件应该不太难？

既然不复杂，能复用 cmakelists 的就复用（自动安装了 xxx.cmake 导入文件，也便于其他cmake包能找到），只能搞不定的包，最后才走 xmake port

可以参考这个 https://github.com/xmake-io/xmake-repo#create-a-package-template-from-github

快速创建一个包，修修改改下。。

> 
另外rlottie的依赖freetype pixman rapidjson stb都已经收录，要不考虑改为引用现有包？

尽量全用 xmake-repo 的依赖

**Comment by DreamOfIce** [comment]
好的，晚点我研究一下

**Comment by DreamOfIce** [comment]
> 尽量全用 xmake-repo 的依赖
具体怎么实现不编译cmake原本包含的依赖，并链接上xmake安装的依赖？

**Comment by waruqi** [comment]
用 add_deps 在外面加上，正常情况下 cmake 会自动找到，如果 cmake 里面强行编译了，找下有没有 option 可以禁用，或者通过 io.replace 或者 add_patches 打 patch 禁用

可以参考其他包

**Comment by DreamOfIce** [comment]
> 尽量全用 xmake-repo 的依赖
不过rlottie比较特殊，对这些包都只是引用了一小部分，使用xmake的完整包会不会导致很多不必要的浪费？
另外我也难以确认这些依赖的版本

**Comment by waruqi** [comment]
做成 add_configs ，可选依赖，可以默认禁用，尽可能最小编译。。

**Comment by DreamOfIce** [comment]
> 做成 add_configs ，可选依赖，可以默认禁用，尽可能最小编译。。

这些依赖都是必须的……

**Comment by DreamOfIce** [comment]
还有一点，使用rlottie自带的pixman构建可以使安装过程不用py/meson

**Comment by waruqi** [comment]
> 还有一点，使用rlottie自带的pixman构建可以使安装过程不用py/meson

尽可能使用外置依赖，用内置的依赖，会存在一些问题。。如果 rlottie 和 其他依赖了 pixman 的库一起 link，就会存在多个 pixman 版本链接冲突。。

**Comment by DreamOfIce** [comment]
基本上搞好了，晚点我锁一下依赖的版本就pr
