### ISSUE TITLE
对于同时支持多个构建工具的项目，xmake.lua中能否同时存在多个构建方式，并根据安装时的环境自动选择最合适的一个

### ISSUE THREAD

**Issue by DreamOfIce** [xmake-io/xmake-repo#1842]
### 你在什么场景下需要该功能？

最近在使用xmake repo的包的时候，有时会遇到在下载/安装构建工具时花费大量时间（甚至远远超过了下载和编译依赖所花费的时间）
以下以[pixman](https://gitlab.freedesktop.org/pixman/pixman)为例：
这个包同时支持autoconf和meson，目前xmake-repo中使用meson构建(查历史发现以前是autoconf，换成meson的原因不明 https://github.com/xmake-io/xmake-repo/pull/797)

最近我在尝试添加rlottie，它的其它几个依赖都基于cmake，只有pixman基于meson
运行测试脚本时，发现安装pixman会占用大量的时间，大大超出了其它步骤的总和。甚至有几次还因为网络问题导致编译失败
_（我知道可以通过参数缓存已下载的内容，但每次在新环境安装都要经历这个过程）_

### 描述可能的解决方案

一个大概思路：为on_install()新增一个重载，允许使用第一个参数指定构建工具名称：
```lua
on_install("cmake|meson|autoconf|…",["system1",…],function(package))
```
在安装时，依照以下逻辑选择最终使用的构建工具：
1. 本地是否已经存在某个构建工具？
2. 是否有某个同时安装的包使用同一个构建工具？
3. 同时安装的包的构建工具取交集，推断出要下载的构建工具数量最少的方案
4. 按照默认顺序选择

### 描述你认为的候选方案

另一个临时方案：在README中添加一个优先级，建议编写者在编写xmake.lua时按照优先级选择构建系统

**Comment by waruqi** [comment]
> 这个包同时支持autoconf和meson，目前xmake-repo中使用meson构建(查历史发现以前是autoconf，换成meson的原因不明 https://github.com/xmake-io/xmake-repo/pull/797)

autoconf 不支持 win ，平台受限制，win上装不了。

而且 cairo/pixman 现在 meson 构建支持的反而更加即使和完善了， autoconf 下坑反而多了 ，当初移植 cairo 新版本时候，切的，autoconf 下遇到很多的坑，不太好维护了。。迫不得已切的。。

> 对于同时支持多个构建工具的项目，xmake.lua中能否同时存在多个构建方式，并根据安装时的环境自动选择最合适的一个 

不考虑，光维护一个 打通全平台编译。。一个包有的都要折腾一个礼拜，现在还要同时支持这么多。。没时间、没人力维护。。。

而且包的配置描述也会更加复杂臃肿。
