### ISSUE TITLE
[spdlog] Some issues

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake-repo#1849]
### Xmake Version

v2.7.6+HEAD.f00d2ed0a

### Operating System Version and Architecture

Windows 11

### Describe Bug

The `spdlog` package has some issues.
1. The option `header_only` is set to true by default despite cmake always having it as OFF in the main target. I'm unsure if this can be changed at this point without affecting existing consumers.
   - Setting the option `header_only` to false doesn't actually work because of a define typo: `SPDLOG_COMPILE_LIB` should be `SPDLOG_COMPILED_LIB`. This can be fixed easily.

3. The option `fmt_external` adds fmt as a dependency but sets it to `header_only` despite the cmake having a separate option `FMT_EXTERNAL_HO` for this. Unsure if this can be changed without affecting existing consumers.

With some feedback I can prepare a pr to fix these issues if possible.

### Expected Behavior

Without these fixes there is no way to prevent `Windows.h` from infecting consumers.

**Comment by waruqi** [comment]
you can open a pr.

**Comment by waruqi** [comment]
> The option fmt_external adds fmt as a dependency but sets it to header_only despite the cmake having a separate option FMT_EXTERNAL_HO for this. Unsure if this can be changed without affecting existing consumers.

any idea? @xq114

**Comment by Qudix** [comment]
PR: https://github.com/xmake-io/xmake-repo/pull/1850
