### ISSUE TITLE
Zlib on mingw, unsupported on Windows?

### ISSUE THREAD

**Issue by RussellHaley** [xmake-io/xmake-repo#185]
> Note: If it is a 'bug report' or 'feature request', please select the corresponding issue template, otherwise this issue will be not replied. 

### Describe the problem details

Hello, 
I am just testing out the xrepo functionality on Windows 10. I am using my own binary installation so I don't have the shell script (powershell or otherwise) at the moment. 

None the less, I tried the example on the website and got these errors:

```
C:\Users\russh\xrepo-test> xmake lua private.xrepo install -a i386 -p mingw zlib
updating repositories .. ok
note: the following packages are unsupported for mingw/i386!
  -> zlib 1.2.11
C:\Users\russh\xrepo-test> xmake lua private.xrepo install -a i686 -p mingw zlib
note: the following packages are unsupported for mingw/i686!
  -> zlib 1.2.11
C:\Users\russh\xrepo-test> xmake lua private.xrepo install -a x86_64 -p mingw zlib
note: the following packages are unsupported for mingw/x86_64!
  -> zlib 1.2.11
C:\Users\russh\xrepo-test>
```

Have I done something wrong or is this really unsupported? Thanks Ruki!

OH!!!! By the way, I have posted my first WinLua article on the LuaForum and xmake is a prominent subject: https://luaforum.com/threads/part-1-lua-sol-3-and-c-oh-my.196/

Let me know what you think.

**Comment by waruqi** [comment]
At present, the zlib package does not support mingw on msys, It only supports mingw on macOS/linux.

But after I have time, I will also support it for mingw on msys.

https://github.com/xmake-io/xmake-repo/blob/master/packages/z/zlib/xmake.lua#L37

```lua
    on_install("iphoneos", "android@linux,macosx", "mingw@linux,macosx", "cross", function (package)
        import("package.tools.autoconf").configure(package, {host = "", "--static"})
        io.gsub("Makefile", "\nAR=.-\n",      "\nAR=" .. (package:build_getenv("ar") or "") .. "\n")
        io.gsub("Makefile", "\nARFLAGS=.-\n", "\nARFLAGS=cr\n")
        io.gsub("Makefile", "\nRANLIB=.-\n",  "\nRANLIB=\n")
        os.vrun("make install -j4")
    end)
```

But now there are many packages that fully support mingw on macos/linux/msys. for example: libplist. ..

```lua
package("libplist")
    on_install("macosx", "linux", "mingw", "iphoneos", "cross", function (package)
...
```

https://xrepo.xmake.io/#/packages/mingw

**Comment by waruqi** [comment]
> OH!!!! By the way, I have posted my first WinLua article on the LuaForum and xmake is a prominent subject: https://luaforum.com/threads/part-1-lua-sol-3-and-c-oh-my.196/

Oh, It's great, thank your very much.

**Comment by RussellHaley** [comment]
> At present, the zlib package does not support mingw on msys, It only supports mingw on macOS/linux.
> 
> But after I have time, I will also support it for mingw on msys.
> 
> https://github.com/xmake-io/xmake-repo/blob/master/packages/z/zlib/xmake.lua#L37
> 
> ```lua
>     on_install("iphoneos", "android@linux,macosx", "mingw@linux,macosx", "cross", function (package)
>         import("package.tools.autoconf").configure(package, {host = "", "--static"})
>         io.gsub("Makefile", "\nAR=.-\n",      "\nAR=" .. (package:build_getenv("ar") or "") .. "\n")
>         io.gsub("Makefile", "\nARFLAGS=.-\n", "\nARFLAGS=cr\n")
>         io.gsub("Makefile", "\nRANLIB=.-\n",  "\nRANLIB=\n")
>         os.vrun("make install -j4")
>     end)
> ```
> 
> But now there are many packages that fully support mingw on macos/linux/msys. for example: libplist. ..
> 
> ```lua
> package("libplist")
>     on_install("macosx", "linux", "mingw", "iphoneos", "cross", function (package)
> ...
> ```
> 
> https://xrepo.xmake.io/#/packages/mingw

Damn you autoconf! I assume that's also why PCRE and many others aren't supported? So it sounds like I need to create my own packages for Windows/mingw?

**Comment by waruqi** [comment]
> Damn you autoconf! I assume that's also why PCRE and many others aren't supported? So it sounds like I need to create my own packages for Windows/mingw?

No, pcre/pcre2 package should already support mingw on msys. Just because I don't have time to test zlib's mingw on msys. 

Maybe it is not a big problem to support zlib for mingw/msys, because autoconf can also be installed on msys.

**Comment by waruqi** [comment]
> 
>     add_includedirs("C:\\Program Files (x86)\\WinLua\\Lua\\5.3\\include")
>     add_linkdirs("C:\\Program Files (x86)\\WinLua\\Lua\\5.3\\bin")
>     add_links("lua53")

Maybe your winlua can also be added to xmake-repo as a dependency package. for example

```lua
add_requires("winlua 5.3")
target("main")
    set_kind("binary")
    add_files("main.cpp")
    add_packages("winlua")
```

**Comment by waruqi** [comment]
Oh, zlib actually already supports mingw on msys. It just doesn't support mingw on windows (without msys).

```lua
    on_install("mingw@msys", function (package)
        io.gsub("win32/Makefile.gcc", "\nCC =.-\n",      "\nCC=" .. (package:build_getenv("cc") or "") .. "\n")
        io.gsub("win32/Makefile.gcc", "\nAR =.-\n",      "\nAR=" .. (package:build_getenv("ar") or "") .. "\n")
        import("package.tools.make").build(package, {"-f", "win32/Makefile.gcc", "libz.a"})
        os.cp("libz.a", package:installdir("lib"))
        os.cp("*.h", package:installdir("include"))
    end)
```

Because I have not deployed mingw without msys on the ci of xmake-repo. Therefore, all packages have not been tested with mingw without msys. Because, without autotools, supporting them may be more troublesome.

**Comment by RussellHaley** [comment]
> Oh, zlib actually already supports mingw on msys. It just doesn't support mingw on windows (without msys).
> 
> ```lua
>     on_install("mingw@msys", function (package)
>         io.gsub("win32/Makefile.gcc", "\nCC =.-\n",      "\nCC=" .. (package:build_getenv("cc") or "") .. "\n")
>         io.gsub("win32/Makefile.gcc", "\nAR =.-\n",      "\nAR=" .. (package:build_getenv("ar") or "") .. "\n")
>         import("package.tools.make").build(package, {"-f", "win32/Makefile.gcc", "libz.a"})
>         os.cp("libz.a", package:installdir("lib"))
>         os.cp("*.h", package:installdir("include"))
>     end)
> ```
> 
> Because I have not deployed mingw without msys on the ci of xmake-repo. Therefore, all packages have not been tested with mingw without msys. Because, without autotools, supporting them may be more troublesome.

Yes, that's my point. I don't want to support msys, just straight up windows with mingw, but many of the libraries require autoconf, bash and the usual tools. I don't want that. I've found many places where important libraries like zlib are supported in other build languages or as sub packages CMake and the like. I also noted that often when building for windows, the configuration is ignored. There are many options, but If you look at the configure file for zlib, mingw mostly just defaults to a makefile.  So given all that, I'm looking forward to adding packages with straight up xmake. I shall start with zlib. I'm a little suprised there is not an xmake.lua file for xmake.

> > ```
> > add_includedirs("C:\\Program Files (x86)\\WinLua\\Lua\\5.3\\include")
> > add_linkdirs("C:\\Program Files (x86)\\WinLua\\Lua\\5.3\\bin")
> > add_links("lua53")
> > ```
> 
> Maybe your winlua can also be added to xmake-repo as a dependency package. for example
> 
> ```lua
> add_requires("winlua 5.3")
> target("main")
>     set_kind("binary")
>     add_files("main.cpp")
>     add_packages("winlua")
> ```

Sorry, I am very tired and my understanding of packages is still weak. Does that require adding it to xrepo first? Let me digest this tomorrow night. Regardless, the answer is yes, I would like to do that instead of the manual steps I specified. :-)

Good night!

**Comment by waruqi** [comment]
> Yes, that's my point. I don't want to support msys, just straight up windows with mingw, but many of the libraries require autoconf, bash and the usual tools. I don't want that. I've found many places where important libraries like zlib are supported in other build languages or as sub packages CMake and the like. I also noted that often when building for windows, the configuration is ignored. There are many options, but If you look at the configure file for zlib, mingw mostly just defaults to a makefile. So given all that, I'm looking forward to adding packages with straight up xmake. I shall start with zlib. I'm a little suprised there is not an xmake.lua file for xmake.

I will also consider adding support for mingw (without msys) in xmake-repo. Of course, I may need to deploy the ci (mingw without msys) first to test it

> Sorry, I am very tired and my understanding of packages is still weak. Does that require adding it to xrepo first? Let me digest this tomorrow night. Regardless, the answer is yes, I would like to do that instead of the manual steps I specified. :-)

This is just a suggestion, and the way it is used now is no problem.

**Comment by RussellHaley** [comment]
Sorry Ruki, I can't find the documentation for creating packages?

**Comment by waruqi** [comment]
> Sorry Ruki, I can't find the documentation for creating packages?

You can see https://xmake.io/#/package/remote_package?id=submit-packages-to-the-official-repository

**Comment by waruqi** [comment]
I have supported zlib on mingw@windows.
