### ISSUE TITLE
Assimp 

### ISSUE THREAD

**Issue by cydthe** [xmake-io/xmake-repo#1855]
### Xmake Version

2.6.4

### Operating System Version and Architecture

Windows 11 Home version 22H2, Microsoft Visual Studio (x64) 2022 version 19.34.31937

### Describe Bug

![assimp_download_error](https://user-images.githubusercontent.com/68164694/220770676-d288bf70-5076-4dfb-a920-add343c874b9.png)
After adding assimp to the xmake.lua both inside add_requires("assimp"), and add_packages("assimp") I build my program on VsCode using the x64 configuration. I am then prompted to install the packages in my terminal, and after inputting yes (y) i get the message 
                                                                => install assimp v5.2.5 . . failed
                                                                => download https://github.com/assimp/assimp/archive/v5.2.5.zip ..ok  
                                                                => install assimp v5.2.5 .. failed
After this I get a warning "cl : Command line warning D9002 : ignoring unknown option '-std:c++11'
_9FBCAB64B619410AA5B53DAE28D84EC2.cpp", and an error. The error I get is "fatal error C1083: Cannot open include file: 'assimp/Importer.hpp': No such file or directory". I am then prompted to access a install.txt to get verbose errors. Inside my install.txt I get the errors "cl : Command line warning D9002 : ignoring unknown option '-std:c++11'
_9FBCAB64B619410AA5B53DAE28D84EC2.cpp
C:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_9FBCAB64B619410AA5B53DAE28D84EC2.cpp(2): fatal error C1083: Cannot open include file: 'assimp/Importer.hpp': No such file or directory
  ${yellow}> in ${bright}C:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_9FBCAB64B619410AA5B53DAE28D84EC2.cpp"
So the file needed to import assimp seems to be missing

### Expected Behavior

I expected for my installation of Assimp to be successful

### Project Configuration

`-- project
set_project("ogl-template")

-- version
set_version("0.1")
set_xmakever("2.6.4")

-- set warning all as error
set_warnings("all")

-- rules
add_rules("mode.debug", "mode.release")
set_languages("cxx17")

-- ext
add_requires("glfw", "glew", "assimp")

-- target
target("ogl-template")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("glfw", "glew", "assimp")`

**Comment by waruqi** [comment]
It works for me.

![image](https://user-images.githubusercontent.com/151335/220799997-dfc74315-a17a-431c-a7d3-2a0afff83f31.png)

Can you run `-vD` and provide verbose logs? 

```
xmake f -c -vD
```

**Comment by cydthe** [comment]
C:\Users\Cindy Guzman\Desktop\Coding\ogl-template>xmake f -c -vD
checking for platform ... windows
checking for architecture ... x64
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.34.31937
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... C:\Program Files\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
checking for cmake ... C:\Program Files\CMake\bin\cmake
checking for cmake ... C:\Program Files\CMake\bin\cmake
checking for xmake-repo::opengl ... opengl
finding glfw from xmake ..
checking for xmake::glfw ... glfw 3.3.8
finding glew from xmake ..
checking for xmake::glew ... glew 2.2.0
finding zlib from xmake ..
checking for xmake::zlib ... no
finding zlib from find_zlib ..
finding zlib from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding zlib from conan ..
finding zlib from pkgconfig ..
checking for pkg-config ... ok
checking for zlib ... pkgconfig::zlib 1.2.11
finding assimp from xmake ..
checking for xmake::assimp ... no
finding assimp from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding assimp from conan ..
finding assimp from pkgconfig ..
finding assimp from system ..
checking for assimp ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> assimp v5.2.5 [vs_runtime:"MT"]
please input: y (y/n/m)
y
checking for ping ... ok
pinging for the host([github.com](http://github.com/)) ... 65 ms
C:\Program Files\xmake\winenv\bin\7z x -y windows-x64-vc143-5428fc7ba30140e390565669b6cddb45.7z -osource.tmp
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
Scanning the drive for archives:
1 file, 19239296 bytes (19 MiB)
Extracting archive: windows-x64-vc143-5428fc7ba30140e390565669b6cddb45.7z
--
Path = windows-x64-vc143-5428fc7ba30140e390565669b6cddb45.7z
Type = 7z
Physical Size = 19239296
Headers Size = 1723
Method = LZMA2:24
Solid = +
Blocks = 1
Everything is Ok
Folders: 11
Files: 97
Size:       191178213
Compressed: 19239296
finding assimp from xmake ..
checking for xmake::assimp ... assimp v5.2.5
{
  libfiles = {
    "C:\Users\Cindy Guzman\AppData\Local\.xmake\packages\a\assimp\v5.2.5\5428fc7ba30140e390565669b6cddb45\lib\assimp-vc143-mt.lib",
    "C:\Users\Cindy Guzman\AppData\Local\.xmake\packages\a\assimp\v5.2.5\5428fc7ba30140e390565669b6cddb45\lib\zlibstatic.lib"
  },
  linkdirs = {
    "C:\Users\Cindy Guzman\AppData\Local\.xmake\packages\a\assimp\v5.2.5\5428fc7ba30140e390565669b6cddb45\lib"
  },
  version = "v5.2.5",
  sysincludedirs = {
    "C:\Users\Cindy Guzman\AppData\Local\.xmake\packages\a\assimp\v5.2.5\5428fc7ba30140e390565669b6cddb45\include"
  },
  license = "BSD-3-Clause",
  links = {
    "assimp-vc143-mt",
    "zlibstatic"
  },
  syslinks = "advapi32",
  static = true
}
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe ... ok
checking for flags (/MT) ... ok
> cl.exe "/MT"
checking for flags (cl_external_includedir) ... ok
> cl.exe "-external:W0" "-external:IC:\Users\Cindy Guzman\AppData\Local\.xmake\packages\a\assimp\v5.2.5\5428fc7ba30140e390565669b6cddb45\include"
> "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\cl.exe" -c -nologo /MT -std:c++11 /EHsc -external:W0 "-external:IC:\\Users\\Cindy Guzman\\AppData\\Local\\.xmake\\packages\\a\\assimp\\v5.2.5\\5428fc7ba30140e390565669b6cddb45\\include" -external:W0 -external:IC:\msys64\mingw64\bin\..\include -FoC:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_0CB7A025EA8B4B7087FCF38CA38075D0.o C:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_9FBCAB64B619410AA5B53DAE28D84EC2.cpp
cl : Command line warning D9002 : ignoring unknown option '-std:c++11'
> "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -nodefaultlib:msvcrt.lib "-libpath:C:\\Users\\Cindy Guzman\\AppData\\Local\\.xmake\\packages\\a\\assimp\\v5.2.5\\5428fc7ba30140e390565669b6cddb45\\lib" -libpath:C:\msys64\mingw64\bin\..\lib assimp-vc143-mt.lib zlibstatic.lib z.lib advapi32.lib -out:C:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_0CB7A025EA8B4B7087FCF38CA38075D0.b C:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_0CB7A025EA8B4B7087FCF38CA38075D0.o
> checking for c++ includes(assimp/Importer.hpp)
> checking for c++ links(assimp-vc143-mt, zlibstatic, z, advapi32)
> checking for c++ snippet(test)
checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:75: @programdir\modules\core\tools\link.lua:164: LINK : fatal error LNK1181: cannot open input file 'z.lib'
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:898]:
    [@programdir\modules\core\tools\link.lua:164]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\link.lua:139]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [...gramdir\core\sandbox\modules\import\core\tool\linker.lua:73]: in function 'link'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:223]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:212]:
    [...make\repositories\xmake-repo\packages\a\assimp\xmake.lua:114]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...dir\modules\private\action\require\impl\actions\test.lua:41]:
    [...\modules\private\action\require\impl\actions\install.lua:347]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:268]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:218]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:
error: ...make\repositories\xmake-repo\packages\a\assimp\xmake.lua:114: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:75: @programdir\modules\core\tools\link.lua:164: LINK : fatal error LNK1181: cannot open input file 'z.lib'
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:898]:
    [@programdir\modules\core\tools\link.lua:164]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\link.lua:139]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [...gramdir\core\sandbox\modules\import\core\tool\linker.lua:73]: in function 'link'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:223]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:212]:
    [...make\repositories\xmake-repo\packages\a\assimp\xmake.lua:114]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...dir\modules\private\action\require\impl\actions\test.lua:41]:
    [...\modules\private\action\require\impl\actions\install.lua:347]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:268]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:218]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:
  => install assimp v5.2.5 .. failed
checking for curl ... C:\Program Files\xmake\winenv\bin\curl
C:\Program Files\xmake\winenv\bin\curl -SL -A "Xmake/2.7.6+master.90959a037 (Windows;) curl/7.85.0" https://github.com/assimp/assimp/archive/v5.2.5.zip -o v5.2.5.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
white_check_mark
eyes
raised_hands





[6:32](https://ucsb-ersp22.slack.com/archives/D044ZMBUHV0/p1677119562850049)
Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 48.9M    0 12833    0     0   8438      0  1:41:18  0:00:01  1:41:17    1 48.9M    1  966k    0     0   390k      0  0:02:08  0:00:02  0:02:06    3 48.9M    3 2000k    0     0   575k      0  0:01:27  0:00:03  0:01:24 1  6 48.9M    6 3076k    0     0   681k      0  0:01:13  0:00:04  0:01:09 1  7 48.9M    7 3772k    0     0   680k      0  0:01:13  0:00:05  0:01:08    9 48.9M    9 4896k    0     0   755k      0  0:01:06  0:00:06  0:01:00   12 48.9M   12 6166k    0     0   823k      0  0:01:00  0:00:07  0:00:53 1 14 48.9M   14 7469k    0     0   881k      0  0:00:56  0:00:08  0:00:48 1 17 48.9M   17 8977k    0     0   947k      0  0:00:52  0:00:09  0:00:43 1 21 48.9M   21 10.2M    0     0  1002k      0  0:00:49  0:00:10  0:00:39 1 24 48.9M   24 12.0M    0     0  1074k      0  0:00:46  0:00:11  0:00:35 1 28 48.9M   28 13.9M    0     0  1143k      0  0:00:43  0:00:12  0:00:31 1 30 48.9M   30 15.1M    0     0  1146k      0  0:00:43  0:00:13  0:00:30 1 33 48.9M   33 16.2M    0     0  1145k      0  0:00:43  0:00:14  0:00:29 1 35 48.9M   35 17.2M    0     0  1138k      0  0:00:44  0:00:15  0:00:29 1 37 48.9M   37 18.1M    0     0  1102k      0  0:00:45  0:00:16  0:00:29 1 38 48.9M   38 18.7M    0     0  1094k      0  0:00:45  0:00:17  0:00:28   39 48.9M   39 19.4M    0     0  1076k      0  0:00:46  0:00:18  0:00:28   41 48.9M   41 20.2M    0     0  1062k      0  0:00:47  0:00:19  0:00:28   42 48.9M   42 20.8M    0     0  1041k      0  0:00:48  0:00:20  0:00:28   43 48.9M   43 21.4M    0     0  1021k      0  0:00:49  0:00:21  0:00:28   45 48.9M   45 22.1M    0     0  1005k      0  0:00:49  0:00:22  0:00:27   46 48.9M   46 22.6M    0     0   986k      0  0:00:50  0:00:23  0:00:27   47 48.9M   47 23.4M    0     0   978k      0  0:00:51  0:00:24  0:00:27   49 48.9M   49 24.4M    0     0   974k      0  0:00:51  0:00:25  0:00:26   51 48.9M   51 24.9M    0     0   965k      0  0:00:51  0:00:26  0:00:25   52 48.9M   52 25.6M    0     0   955k      0  0:00:52  0:00:27  0:00:25   53 48.9M   53 26.1M    0     0   935k      0  0:00:53  0:00:28  0:00:25   56 48.9M   56 27.7M    0     0   963k      0  0:00:51  0:00:29  0:00:22   61 48.9M   61 30.3M    0     0  1015k      0  0:00:49  0:00:30  0:00:19 1 65 48.9M   65 31.9M    0     0  1039k      0  0:00:48  0:00:31  0:00:17 1 67 48.9M   67 33.2M    0     0  1043k      0  0:00:48  0:00:32  0:00:16 1 69 48.9M   69 34.1M    0     0  1042k      0  0:00:48  0:00:33  0:00:15 1 71 48.9M   71 35.0M    0     0  1039k      0  0:00:48  0:00:34  0:00:14 1 73 48.9M   73 35.9M    0     0  1035k      0  0:00:48  0:00:35  0:00:13 1 75 48.9M   75 36.7M    0     0  1029k      0  0:00:48  0:00:36  0:00:12   76 48.9M   76 37.4M    0     0  1020k      0  0:00:49  0:00:37  0:00:12   77 48.9M   77 38.0M    0     0  1012k      0  0:00:49  0:00:38  0:00:11   79 48.9M   79 38.8M    0     0  1006k      0  0:00:49  0:00:39  0:00:10   81 48.9M   81 39.7M    0     0  1003k      0  0:00:49  0:00:40  0:00:09   82 48.9M   82 40.3M    0     0   993k      0  0:00:50  0:00:41  0:00:09   83 48.9M   83 40.9M    0     0   986k      0  0:00:50  0:00:42  0:00:08   84 48.9M   84 41.5M    0     0   977k      0  0:00:51  0:00:43  0:00:08   85 48.9M   85 41.9M    0     0   964k      0  0:00:51  0:00:44  0:00:07   87 48.9M   87 42.6M    0     0   960k      0  0:00:52  0:00:45  0:00:07   88 48.9M   88 43.5M    0     0   958k      0  0:00:52  0:00:46  0:00:06   90 48.9M   90 44.1M    0     0   952k      0  0:00:52  0:00:47  0:00:05   91 48.9M   91 44.7M    0     0   945k      0  0:00:52  0:00:48  0:00:04   93 48.9M   93 45.5M    0     0   941k      0  0:00:53  0:00:49  0:00:04   94 48.9M   94 46.2M    0     0   938k      0  0:00:53  0:00:50  0:00:03   96 48.9M   96 46.9M    0     0   934k      0  0:00:53  0:00:51  0:00:02   97 48.9M   97 47.7M    0     0   930k      0  0:00:53  0:00:52  0:00:01   98 48.9M   98 48.3M    0     0   925k      0  0:00:54  0:00:53  0:00:01   99 48.9M   99 48.7M    0     0   915k      0  0:00:54  0:00:54 --:--:--  100 48.9M  100 48.9M    0     0   908k      0  0:00:55  0:00:55 --:--:--  584k
C:\Program Files\xmake\winenv\bin\7z x -y v5.2.5.zip -osource.tmp
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
Scanning the drive for archives:
1 file, 51288329 bytes (49 MiB)
Extracting archive: v5.2.5.zip
--
Path = v5.2.5.zip
Type = zip
Physical Size = 51288329
Comment = 9519a62dd20799c5493c638d1ef5a6f484e5faf1
Everything is Ok
Folders: 416
Files: 2676
Size:       133420659
Compressed: 51288329
  => download https://github.com/assimp/assimp/archive/v5.2.5.zip .. ok
finding assimp from xmake ..
checking for xmake::assimp ... assimp v5.2.5
{
  license = "BSD-3-Clause",
  syslinks = "advapi32",
  version = "v5.2.5"
}
patching C:\Users\Cindy Guzman\AppData\Local\.xmake\packages\a\assimp\v5.2.5\5428fc7ba30140e390565669b6cddb45\lib\pkgconfig\assimp.pc ..
> "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\cl.exe" -c -nologo /MT -std:c++11 /EHsc -external:W0 -external:IC:\msys64\mingw64\bin\..\include -FoC:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_7981B6448CDF453082268FB529EEE840.o C:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_9FBCAB64B619410AA5B53DAE28D84EC2.cpp
> checking for c++ includes(assimp/Importer.hpp)
> checking for c++ links(z, advapi32)
> checking for c++ snippet(test)
checkinfo: ...amdir\core\sandbox\modules\import\core\tool\compiler.lua:84: @programdir\modules\core\tools\cl.lua:648: cl : Command line warning D9002 : ignoring unknown option '-std:c++11'
_9FBCAB64B619410AA5B53DAE28D84EC2.cpp
C:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_9FBCAB64B619410AA5B53DAE28D84EC2.cpp(2): fatal error C1083: Cannot open include file: 'assimp/Importer.hpp': No such file or directory
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:898]:
    [@programdir\modules\core\tools\cl.lua:648]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\cl.lua:587]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [...amdir\core\sandbox\modules\import\core\tool\compiler.lua:82]: in function 'compile'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:218]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:212]:
    [...make\repositories\xmake-repo\packages\a\assimp\xmake.lua:114]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...dir\modules\private\action\require\impl\actions\test.lua:41]:
    [...\modules\private\action\require\impl\actions\install.lua:347]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:268]:
    [...modules\private\action\require\impl\install_packages.lua:484]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:218]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:
error: ...make\repositories\xmake-repo\packages\a\assimp\xmake.lua:114: ...amdir\core\sandbox\modules\import\core\tool\compiler.lua:84: @programdir\modules\core\tools\cl.lua:648: cl : Command line warning D9002 : ignoring unknown option '-std:c++11'
_9FBCAB64B619410AA5B53DAE28D84EC2.cpp
C:\Users\CINDYG~1\AppData\Local\Temp\.xmake\230222\_9FBCAB64B619410AA5B53DAE28D84EC2.cpp(2): fatal error C1083: Cannot open include file: 'assimp/Importer.hpp': No such file or directory
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:898]:
    [@programdir\modules\core\tools\cl.lua:648]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\cl.lua:587]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [...amdir\core\sandbox\modules\import\core\tool\compiler.lua:82]: in function 'compile'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:218]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:212]:
    [...make\repositories\xmake-repo\packages\a\assimp\xmake.lua:114]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...dir\modules\private\action\require\impl\actions\test.lua:41]:
    [...\modules\private\action\require\impl\actions\install.lua:347]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
        [C]: in function 'error'
        @programdir\core\base\os.lua:898: in function 'os.raiselevel'             (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:123: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by cydthe** [comment]
It seems that I can't find zlib on my system

**Comment by waruqi** [comment]
> It seems that I can't find zlib on my system

pkgconfig provide zlib link `-lz`, but do not provide linkdir.

> checking for zlib ... pkgconfig::zlib 1.2.11

you can try adding

```lua
add_requireconfs("assimp.zlib", {system = false})
```

**Comment by cydthe** [comment]
`add_requireconfs("assimp.zlib", {system = false})`
this fixed it, thank you!
