### ISSUE TITLE
SDL2 package debug build is broken due to implicit "d" suffix 

### ISSUE THREAD

**Issue by WSSDude** [xmake-io/xmake-repo#1864]
### Xmake Version

xmake v2.7.6+master.415d9e13a

### Operating System Version and Architecture

Windows 11 22H2 x86_64

### Describe Bug

Following from https://github.com/xmake-io/xmake/issues/3409 it seems like SDL2 puts "d" suffix when you try to build the package in debug mode. From what waruqi said, xmake does not expect random suffixes for debug builds, so debug build output names and release mode output names should match for successful compilation.

### Expected Behavior

Debug package fully working without link issues.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/1865

**Comment by WSSDude** [comment]
After trying to checkout the fix, can confirm this fixes the issue for me👍

**Comment by SirLynix** [comment]
This makes me think there should be a way to have CI test multiple configs and not just the default one. Perhaps a .test file:
```json
{
    "configs":[
        {debug=false},
        {debug=true}
    ]
}
```

or maybe a callback?
```lua
package("libsdl")
    on_ci(function(package)
        package:test({ debug = false }) -- runs on_install and on_test
        package:test({ debug = true }) -- runs on_install and on_test
    end)
```

**Comment by waruqi** [comment]
> This makes me think there should be a way to have CI test multiple configs and not just the default one. Perhaps a .test file:
> 
> ```json
> {
>     "configs":[
>         "{debug=false}",
>         "{debug=true}"
>     ]
> }
> ```
> 
> or maybe a callback?
> 
> ```lua
> package("libsdl")
>     on_ci(function(package)
>         package:test({ debug = false }) -- runs on_install and on_test
>         package:test({ debug = true }) -- runs on_install and on_test
>     end)
> ```

There are already too many test combinations, static/shared+vs_runtime+x86/x64/arm64+platorm+toolchain

Adding more combinations of configs to ci tests, we don't have more time to maintain them, and ci jobs require more time and resources.

**Comment by SirLynix** [comment]
I understand that, but some packages with a lot of configurations such as imgui can't be properly tested otherwise :-/

**Comment by waruqi** [comment]
I have merge it, try it again.

xrepo update-repo

**Comment by waruqi** [comment]
> I understand that, but some packages with a lot of configurations such as imgui can't be properly tested otherwise 😕

I know, but there's no good way to do it now, there are too many combinations of configurations to test. The only priority now is to test the default configuration.

**Comment by waruqi** [comment]
I added mode (debug) check in a linux ci.
