### ISSUE TITLE
Add xlnt library to xmake repo

### ISSUE THREAD

**Issue by IcyVizi** [xmake-io/xmake-repo#1869]
### 你在什么场景下需要该功能？

Read and write excel file.

https://github.com/tfussell/xlnt

### 描述可能的解决方案

Add xlint to xmake repo.

### 其他信息

- https://github.com/tfussell/xlnt
> Cross-platform user-friendly xlsx library for C++11+

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/1882
