### ISSUE TITLE
Add patch to make package

### ISSUE THREAD

**Issue by juteman** [xmake-io/xmake-repo#189]
If we make deb package, we can add patch file in debian directory. 
If we make a rpm package, we can add patch file in rpm directory. 
If we make AUR package,  we can add patch rule in PKGBUILD file and add patch file.
And about vcpkg, they also have patch rule.

When we wanan to change something in xmake package script, we need "io.replace" or "io.gsub", this is not flexible at all. Building package sometimes, we need customization.

So I think  we need patch enhancement while making package for xmake repo.

**Comment by waruqi** [comment]
You can also use add_patches to add some patch files. see 

https://github.com/xmake-io/xmake-repo/blob/7b44576aa1b54d67a04e4088e816d6a7143c4f0c/packages/b/bin2c/xmake.lua#L10

io.replace is only used to modify some small changes

**Comment by juteman** [comment]
cools
