### ISSUE TITLE
xrepo 安装grpc 失败

### ISSUE THREAD

**Issue by wzy2687** [xmake-io/xmake-repo#1910]
### Xmake 版本

v2.7.7+20230310,

### 操作系统版本和架构

Linux ubuntu 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

xrepo install -vD grpc   执行失败

在:~/.xmake/cache/packages/2303/g/grpc/v1.46.3/installdir.failed/include$  目录下没有absl 相关的第三方库.

部分出错信息如下: 

-- Installing: /home/wzy/.xmake/packages/g/grpc/v1.46.3/fa5cb5edd791499cb17b023fd18a6912/share/pkgconfig/zlib.pc
finding grpc from xmake ..
checking for xmake::grpc ... grpc v1.46.3
{ 
  static = true,
  version = "v1.46.3",
  license = "Apache-2.0",
  sysincludedirs = { 
    "/home/wzy/.xmake/packages/g/grpc/v1.46.3/fa5cb5edd791499cb17b023fd18a6912/include" 
  },
  shared = true 
}

checking for gcc ... /usr/bin/gcc
checking for the c++ compiler (cxx) ... gcc
checking for /usr/bin/gcc ... ok
checking for flags (-fPIC) ... ok
> gcc "-fPIC"
> /usr/bin/gcc -c -m64 -std=c++11 -isystem /home/wzy/.xmake/packages/g/grpc/v1.46.3/fa5cb5edd791499cb17b023fd18a6912/include -o /tmp/.xmake1000/230312/_10EB397BA5584A10851603DB27D63920.o /tmp/.xmake1000/230312/_C09B0F55C5CD47AC8879AFB72378A4B6.cpp
checking for flags (-fdiagnostics-color=always) ... ok
> gcc "-fdiagnostics-color=always"
> checking for c++ includes(grpcpp/grpcpp.h)
> checking for c++ snippet(test)
checkinfo: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/core/tools/gcc.lua:713: In file included from /home/wzy/.xmake/packages/g/grpc/v1.46.3/fa5cb5edd791499cb17b023fd18a6912/include/grpcpp/impl/codegen/completion_queue.h:45:0,
                 from /home/wzy/.xmake/packages/g/grpc/v1.46.3/fa5cb5edd791499cb17b023fd18a6912/include/grpcpp/channel.h:28,
                 from /home/wzy/.xmake/packages/g/grpc/v1.46.3/fa5cb5edd791499cb17b023fd18a6912/include/grpcpp/grpcpp.h:52,
                 from /tmp/.xmake1000/230312/_C09B0F55C5CD47AC8879AFB72378A4B6.cpp:2:
/home/wzy/.xmake/packages/g/grpc/v1.46.3/fa5cb5edd791499cb17b023fd18a6912/include/grpcpp/impl/codegen/sync.h:32:10: fatal error: absl/synchronization/mutex.h: No such file or directory
 #include "absl/synchronization/mutex.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:912]:
    [@programdir/modules/core/tools/gcc.lua:713]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:654]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [...amdir/core/sandbox/modules/import/core/tool/compiler.lua:82]: in function 'compile'
    [@programdir/modules/lib/detect/check_cxsnippets.lua:218]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/lib/detect/check_cxsnippets.lua:212]:
    [....xmake/repositories/xmake-repo/packages/g/grpc/xmake.lua:38]: in function 'script'
    [...dir/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call'
    [...dir/modules/private/action/require/impl/actions/test.lua:41]:
    [.../modules/private/action/require/impl/actions/install.lua:366]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:287]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:218]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

### 期待的结果

能安装成功.

**Comment by waruqi** [comment]
xrepo update-repo

**Comment by wzy2687** [comment]
测试了, 已经能正常工作.   so nice.

**Comment by wzy2687** [comment]
测试了, 已经能正常工作. so nice.
