### ISSUE TITLE
glog static lib on_test link error with  -- undefined reference to symbol 'pthread_rwlock_destroy@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by guijiyang** [xmake-io/xmake-repo#1924]
### Xmake Version

2.7.7

### Operating System Version and Architecture

WSL Ubuntu20.04

### Describe Bug

after package glog build down as static library, it will test on:
```lua
on_test(function (package)
        assert(package:has_cxxfuncs("google::InitGoogleLogging(\"glog\")", {includes = "glog/logging.h"}))
    end)
```
and get link error for like this:
```
libglog.a(logging.cc.o): undefined reference to symbol 'pthread_rwlock_destroy@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
```
this lead package build failed.
actually test program need add link with -lpthread on my platform

### Expected Behavior

package build succeed

**Comment by waruqi** [comment]
try it again.

```
xrepo update-repo
xmake remove --all glogs
xmake f -c
xmake
```
