### ISSUE TITLE
mariadb-connecter-c 修改配置后依然是动态链接，无法静态链接

### ISSUE THREAD

**Issue by RimuruChan** [xmake-io/xmake-repo#1940]
### Xmake 版本

2.7.7

### 操作系统版本和架构

Windows 11

### 描述问题

无法使用静态链接。
已经测试过卸载重装，禁用预构建

### 期待的结果

可以静态链接

### 工程配置

add_requires("mariadb-connector-c 3.1.13", {configs = {shared = false}})

### 附加信息和错误日志

![image](https://user-images.githubusercontent.com/42002296/226913487-eceb4139-beab-4c3c-ab10-584eb998dc07.png)

**Comment by waruqi** [comment]
这个包被标记了 shared only 包，切不了 static 库。https://github.com/xmake-io/xmake-repo/blob/d83ba9629705dceb85a9c1fe4327cfc03b94453e/packages/m/mariadb-connector-c/xmake.lua#L18

通常可能是前期由于 包自身 static 编译遇到问题，短时间难以解决，或者包自身构建原本就不支持 static 导致。。所以暂时强制走 shared ，至少保证能用

你可以先本地强行放开 static 。。然后修改 on_install 验证测试下，如果没啥问题，或者能解决让它支持上 static 。。可以提个 pr 过来

**Comment by waruqi** [comment]
你可以翻下之前的一些背景，似乎是 cmakelists 总是安装 shared ，忽略 static/shared 配置导致。。https://github.com/xmake-io/xmake-repo/pull/436#issuecomment-850747974

按理，稍微对 on_install 做些调整，应该能切，，你可以尝试来个 pr 改进下试试，比如对 cmakelists.txt 打一些 patch 等等

**Comment by RimuruChan** [comment]
好的，我去试一下

**Comment by RimuruChan** [comment]
看了一下原仓库的pr，其实有静态构建，就是 mariadbclient.lib
https://github.com/mariadb-corporation/mariadb-connector-c/pull/197#discussion_r905802072

静态链接应该只用改为链接这个lib就好了

**Comment by waruqi** [comment]
那你提个 pr 过来处理区分下
