### ISSUE TITLE
安装 icu4c 出错

### ISSUE THREAD

**Issue by maye174** [xmake-io/xmake-repo#1948]
### Xmake 版本

2.7.7

### 操作系统版本和架构

win 11 22621.1413

### 描述问题

# 错误信息
'''
❯ xmake
checking for Microsoft Visual Studio (x64) version ... 2022
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> icu4c 72.1 [vs_runtime:"MT"]
please input: y (y/n/m)
y
  => install icu4c 72.1 .. failed   
  => download https://github.com/unicode-org/icu/releases/download/release-72-1/icu4c-72_1-src.tgz .. ok
  => install icu4c 72.1 .. failed

C:\Users\35343\AppData\Local\Temp\.xmake\230324\_24188FD80D6F4D02A7E0ADC8E84510BE.c:2:10: fatal error: 'unicode/ucnv.h' file not found
#include <unicode/ucnv.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
  ${yellow}> in ${bright}C:\Users\35343\AppData\Local\Temp\.xmake\230324\_24188FD80D6F4D02A7E0ADC8E84510BE.c
if you want to get more verbose errors, please see:
  -> C:\Users\35343\AppData\Local\.xmake\cache\packages\2303\i\icu4c\72.1\installdir.failed\logs\install.txt
error: install failed!
warning: add_cxflags("/MT") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.

'''

### 期待的结果

正确安装，感谢

**Comment by waruqi** [comment]
先自己加 -vD 排查下，然后提个 pr 过来修复下，`xmake f -cvD`
