### ISSUE TITLE
Sophus版本号命名发生更改

### ISSUE THREAD

**Issue by wt-suitors** [xmake-io/xmake-repo#1992]
### Xmake 版本

v2.7.8

### 操作系统版本和架构

Windows 10

### 描述问题

Sophus库的作者已经更改了版本号命名，V22.10更改为1.22.10。add_requires("sophus")无法安装Sophus库

### 期待的结果

修改https://github.com/xmake-io/xmake-repo/blob/master/packages/s/sophus/xmake.lua，使得add_requires("sophus")正常工作

**Comment by waruqi** [comment]
提个 pr 过来改下
