### ISSUE TITLE
编译openimageio失败

### ISSUE THREAD

**Issue by lai001** [xmake-io/xmake-repo#2002]
### 你在什么场景下需要该功能？

使用openimageio时编译失败
add_requires("openimageio", {configs = {shared = true}})

### 描述可能的解决方案

https://github.com/OpenImageIO/oiio/blob/v2.3.18.0/INSTALL.md
根据2.3.18.0版本的描述，**[fmtlib](https://github.com/fmtlib/fmt) >= 6.1.2 (tested through 9.0). If not found at build time, this will be automatically downloaded unless the build sets -DBUILD_MISSING_FMT=OFF.**，2.3.18.0版本才支持fmt9.0，应该判断openimageio的版本，低于2.3.18.0的，使用低于9.0的fmt
或者有没有办法强制让openimageio依赖fmt的某个版本？

**Comment by waruqi** [comment]
```
add_deps("fmt >=6.1.2")
```

**Comment by lai001** [comment]
add_requires("fmt 8.1.1")
add_requires("openimageio", {configs = {shared = true}})

比如像我上面那样，运行xmake
```
checking for Microsoft Visual Studio (x64) version ... 2019
checking for Microsoft C/C++ Compiler (x64) version ... 19.29.30146
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> fmt 8.1.1 [vs_runtime:"MT"]
  -> fmt#1 9.1.0 [vs_runtime:"MT", from:openimageio]
  -> openimageio 2.3.13+0 [vs_runtime:"MT", shared:y]
please input: y (y/n/m)
```
openimageio 依旧依赖的是9.1.0的fmt，但是2.3.13的openimageio不支持9.1.0的fmt，这时候是会编译失败的，我想的是让openimageio强制依赖8.1.1的fmt

**Comment by lai001** [comment]
可以了，谢谢
