### ISSUE TITLE
添加 async_simple 包

### ISSUE THREAD

**Issue by fantasy-peak** [xmake-io/xmake-repo#2020]
### Is your feature request related to a problem? Please describe.

不是。创建此 issue 以提交 PR

### Describe the solution you'd like

添加 async_simple 包的 xmake.lua

**Comment by waruqi** [comment]
每次提 pr 不用单独开 issues ，除非遇到问题

**Comment by fantasy-peak** [comment]
> 每次提 pr 不用单独开 issues ，除非遇到问题

好的，我一直以为新加包都要开issues. Ci有几个没过去，似乎是gcc版本太低了，不支持cpp20
