### ISSUE TITLE
添加vcpkg到 xmake-repo中

### ISSUE THREAD

**Issue by masx200** [xmake-io/xmake-repo#2029]
### 你在什么场景下需要该功能？

添加vcpkg到 xmake-repo中

就不需要手动安装vcpkg了

### 描述可能的解决方案

添加vcpkg到 xmake-repo中

https://github.com/microsoft/vcpkg-tool/

**Comment by waruqi** [comment]
提个 pr 过来

**Comment by star-hengxing** [comment]
https://github.com/xmake-io/xmake-repo/pull/4219
