### ISSUE TITLE
使用MSVC编译debug版libevent的动态库时,MSVC报错fatal error C1041

### ISSUE THREAD

**Issue by xiangbuchule** [xmake-io/xmake-repo#2031]
### Xmake 版本

2.7.7

### 操作系统版本和架构

Windows 10, 21H2, 19044.2846

### 描述问题

1. 使用 MSVC 编译 libevent 三方库并设置其为 debug
2. 使用命令 xmake f -p windows -a x64 -m debug -v 开始配置项目
3. MSVC报错fatal error C1041

### 期待的结果

MSVC不报错，正常编译成功

### 工程配置

main.c
```
#include <event2/event.h>
#include <stdio.h>

int main(){
    const char *xyz = event_get_version();
    return 0;
}
```
xmake.lua
```
add_rules("mode.debug", "mode.release")
set_policy("package.precompiled", false)
add_repositories("SDK-repo SDK")
add_requires("libevent 2.1.12", {
    debug = is_mode("debug"),
    system = false,
    alias = "libevent",
    configs = {shared = true}
})
target("test")
    set_kind("binary")
    add_files("main.c")
    add_packages("libevent")
```
SDK\packages\l\libevent\xmake.lua
copy from https://github.com/xmake-io/xmake-repo/blob/master/packages/l/libevent/xmake.lua

### 附加信息和错误日志

...
cache\packages\2304\l\libevent\2.1.12\source\buffer.c : fatal error C1041: 无法打开程序数据库
cache\packages\2304\l\libevent\2.1.12\source\build_27c865c2\pdb\Debug\vc143.pdb”;如果要将多个 CL.EXE 写入同一个 .PDB 文件，请使用 /FS
cache\packages\2304\l\libevent\2.1.12\source\bufferevent.c : fatal error C1041: 无法打开程序数据库
cache\packages\2304\l\libevent\2.1.12\source\build_27c865c2\pdb\Debug\vc143.pdb”；如果要将多个 CL.EXE 写入同一个 .PDB 文件，请使用 /FS
...

### 经过分析，是MSVC的MSBUILD并行构建pdb文件的问题。
原因

> xmake的源码https://github.com/xmake-io/xmake/blob/v2.7.7/xmake/modules/package/tools/cmake.lua 中默认指定了并行构建和pdb生成目录
> xmake默认并行构建
> ![image](https://user-images.githubusercontent.com/26376041/234249999-24b55ac8-739d-4687-9229-7eabffa9ddd6.png)
> xmake默认pdb生成目录
> ![image](https://user-images.githubusercontent.com/26376041/234199842-3fed314b-fe10-496f-b8e8-45debecf8deb.png)

### 所以找到两个修改方式

1、设置MSBUILD非并行构建，缺点是构建速度降低

> SDK\packages\l/libevent\xmake.lua文件
> `import("package.tools.cmake").install(package, configs)`
> 改为
> `import("package.tools.cmake").install(package, configs, {jobs = 1})`

2、取消默认pdb生成目录

>  SDK\packages\l\libevent\xmake.lua文件
> `local configs = {"-DEVENT__DISABLE_TESTS=ON", "-DEVENT__DISABLE_REGRESS=ON", "-DEVENT__DISABLE_SAMPLES=ON"}`
> 改为
> `local configs = {"-DCMAKE_COMPILE_PDB_OUTPUT_DIRECTORY=''","-DEVENT__DISABLE_TESTS=ON", "-DEVENT__DISABLE_REGRESS=ON", "-DEVENT__DISABLE_SAMPLES=ON"}`

### 扩展

1. libevent的cmake默认构建多个目标libevent_core、libevent_extra、libevent(如果配置了openssl或mbedtls会额外增加构建目标)。会不会是这个原因导致MSBUILD并行构建pdb文件的问题(单目标应该无此问题)?
2. 那么其他多目标三方库是否有此问题?

### 思路整理
libevent的cmake默认构建多个目标 ===> xmake使用MSVC的MSBUILD时默认设置并行构建(-m)、使用cmake的debug模式时设置默认设置pdb ===> 导致MSBUILD多目标使用同一pdb文件而报错。

**Comment by xiangbuchule** [comment]
上述修改方案只是提供了能编译的解决方法。
仅上述修改，还是无法调试时定位到代码行。
需要将生成的pdb文件copy到库的目录。
在SDK\packages\l\libevent\xmake.lua文件的代码
`import("package.tools.cmake").install(package, configs)`
后边添加代码
```
if package:is_plat("windows") then
    os.trycp("**.pdb", package:installdir("lib"))
    os.trycp("**.exp", package:installdir("lib"))
end
```

**Comment by waruqi** [comment]
可以改下包 提个 pr 过来。。

> 取消默认pdb生成目录

可以试下这个。。

其他包偶尔也会遇到，不多，目前遇到的只有2、3个

**Comment by libreliu** [comment]
> 可以改下包 提个 pr 过来。。
> 
> > 取消默认pdb生成目录
> 
> 可以试下这个。。
> 
> 其他包偶尔也会遇到，不多，目前遇到的只有2、3个

想问下， 需要调试的包的 pdb 都需要手动拷贝嘛..（类似上面 @xiangbuchule 的方案）？还是 xmake 的 cmake tools 那边有额外机制处理呢

**Comment by waruqi** [comment]
默认是会尝试 copy 的 https://github.com/xmake-io/xmake/blob/a4a1414b6d81985e4e880c4960ca56016038bee6/xmake/modules/package/tools/cmake.lua#L841

你也可以 on_install 里面 copy 它们，如果没生效的话，或者改进 tools.cmake

**Comment by libreliu** [comment]
> 所以，三方库构建完成后删除其缓存这个功能，能设置关闭？

我 (#2032) 现在也遇到了这个问题，似乎 package cache 里面只会有 git 下载的 sources，不会有安装过程中解压的 zip 那些

我现在的 walkaround 是自己在项目里面挂 submodule 然后自己编译...（捂脸）插眼看看有没有更好的解决方法

**Comment by waruqi** [comment]
> > 所以，三方库构建完成后删除其缓存这个功能，能设置关闭？
> 
> 我 (#2032) 现在也遇到了这个问题，似乎 package cache 里面只会有 git 下载的 sources，不会有安装过程中解压的 zip 那些
> 
> 我现在的 walkaround 是自己在项目里面挂 submodule 然后自己编译...（捂脸）插眼看看有没有更好的解决方法

之前有，但是每次安装都保留一份解压的，还带编译产物的，太占磁盘，很容易打满磁盘，最近的版本，装完自动删了

**Comment by waruqi** [comment]
想要源码调试包，可以自己解压下包源码，然后执行

```
xrepo install -d packagesrc -m debug zlib 
```

指定包源码编译安装，不仅保留包源码，还能随时修改包源码，调试更方便

**Comment by xiangbuchule** [comment]
> 想要源码调试包，可以自己解压下包源码，然后执行
> 
> ```
> xrepo install -d packagesrc -m debug zlib 
> ```
> 
> 指定包源码编译安装，不仅保留包源码，还能随时修改包源码，调试更方便

这种方式好像只是单独生成的调试库，和我的程序关联不上，除非手动拷贝这样生成的库文件替换我的程序关联的库文件。
我只是希望我调试我的程序时，能顺带调试我的程序依赖的第三方库。。。

**Comment by waruqi** [comment]
> > 想要源码调试包，可以自己解压下包源码，然后执行
> > ```
> > xrepo install -d packagesrc -m debug zlib 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 指定包源码编译安装，不仅保留包源码，还能随时修改包源码，调试更方便
> 
> 这种方式好像只是单独生成的调试库，和我的程序关联不上，除非手动拷贝这样生成的库文件替换我的程序关联的库文件。 我只是希望我调试我的程序时，能顺带调试我的程序依赖的第三方库。。。

`xrepo install -f ` 可以传递 configs ，只要跟你 `add_requires` 的 configs/mode/plat/arch/static/shared 完全一致，就会覆盖安装你程序依赖的依赖库。。可以完全对上的。

**Comment by xiangbuchule** [comment]
> > > 想要源码调试包，可以自己解压下包源码，然后执行
> > > ```
> > > xrepo install -d packagesrc -m debug zlib 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 指定包源码编译安装，不仅保留包源码，还能随时修改包源码，调试更方便
> > 
> > 
> > 这种方式好像只是单独生成的调试库，和我的程序关联不上，除非手动拷贝这样生成的库文件替换我的程序关联的库文件。 我只是希望我调试我的程序时，能顺带调试我的程序依赖的第三方库。。。
> 
> `xrepo install -f ` 可以传递 configs ，只要跟你 `add_requires` 的 version/configs/mode/plat/arch/static/shared 完全一致，就会覆盖安装你程序依赖的依赖库。。可以完全对上的。

这个操作可否下xmake.lua自动化，第三方库一多就麻烦了。

**Comment by waruqi** [comment]
> > > > 想要源码调试包，可以自己解压下包源码，然后执行
> > > > ```
> > > > xrepo install -d packagesrc -m debug zlib 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 指定包源码编译安装，不仅保留包源码，还能随时修改包源码，调试更方便
> > > 
> > > 
> > > 这种方式好像只是单独生成的调试库，和我的程序关联不上，除非手动拷贝这样生成的库文件替换我的程序关联的库文件。 我只是希望我调试我的程序时，能顺带调试我的程序依赖的第三方库。。。
> > 
> > 
> > `xrepo install -f ` 可以传递 configs ，只要跟你 `add_requires` 的 version/configs/mode/plat/arch/static/shared 完全一致，就会覆盖安装你程序依赖的依赖库。。可以完全对上的。
> 
> 这个操作可否下xmake.lua自动化，第三方库一多就麻烦了。

这个主要是用于定点排查调试特定包问题用的，没必要，你想调什么库，就对哪个库操作下。。

除非安装时候保留包源码，这就是之前那个问题了，保留所有包源码和编译产物，容易打爆磁盘。。比如一个 boost debug 编译完，就占了N个 G，还有各种依赖，随随便便 就可能磁盘跑满。

**Comment by xiangbuchule** [comment]
> > > > > 想要源码调试包，可以自己解压下包源码，然后执行
> > > > > ```
> > > > > xrepo install -d packagesrc -m debug zlib 
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 指定包源码编译安装，不仅保留包源码，还能随时修改包源码，调试更方便
> > > > 
> > > > 
> > > > 这种方式好像只是单独生成的调试库，和我的程序关联不上，除非手动拷贝这样生成的库文件替换我的程序关联的库文件。 我只是希望我调试我的程序时，能顺带调试我的程序依赖的第三方库。。。
> > > 
> > > 
> > > `xrepo install -f ` 可以传递 configs ，只要跟你 `add_requires` 的 version/configs/mode/plat/arch/static/shared 完全一致，就会覆盖安装你程序依赖的依赖库。。可以完全对上的。
> > 
> > 
> > 这个操作可否下xmake.lua自动化，第三方库一多就麻烦了。
> 
> 这个主要是用于定点排查调试特定包问题用的，没必要，你想调什么库，就对哪个库操作下。。
> 
> 除非安装时候保留包源码，这就是之前那个问题了，保留所有包源码和编译产物，容易打爆磁盘。。比如一个 boost debug 编译完，就占了N个 G，还有各种依赖，随随便便 就可能磁盘跑满。

ok，谢谢解惑。

**Comment by xiangbuchule** [comment]
@waruqi 突然想起来，未来是否可以在add_requires的时候加一个配置，例如:
`add_requires("libevent 2.1.12", {cache = true})`
来让一个固定的库保留其编译缓存(默认为false,不保留编译缓存)，这样方便配置，不用xrepo手动输入命令
