### ISSUE TITLE
glslang 1.3.239+0 编译 Debug 版本时失败

### ISSUE THREAD

**Issue by libreliu** [xmake-io/xmake-repo#2032]
### Xmake 版本

2.7.7+HEAD.da4fa3574

### 操作系统版本和架构

Windows 10 版本 21H2 (内部版本 19044.2846)

### 描述问题

编译 Debug 版本的 glslang 时遇到错误。

成功：`xrepo install -m release --verbose "glslang 1.3.239+0"`

错误：`xrepo install -m debug --verbose "glslang 1.3.239+0"`
- 报错和 #2031 类似，同时 glslang 本身也是多目标的

**仍然错误**：`xrepo install -m debug -j 1 --verbose "glslang 1.3.239+0"`

最后的验证阶段会发现 `glslangValidator --version` 可以运行，但是检测 `ShInitialize` 是否可以被链接会失败：
```
(跳过了前面的一些行...)
已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:03.99
checking for xmake::glslang ... glslang 1.3.239+0
{
  license = "Apache-2.0",
  static = true,
  version = "1.3.239+0",
  sysincludedirs = {
    "C:\Users\libreliu\AppData\Local\.xmake\packages\g\glslang\1.3.239+0\3ae55121326f42e292872105c4b7fd7d\include"
  }
}

patching C:\Users\libreliu\AppData\Local\.xmake\packages\g\glslang\1.3.239+0\3ae55121326f42e292872105c4b7fd7d\lib\pkgconfig\glslang.pc ..
glslangValidator --version
Glslang Version: 11:12.0.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 12.0.0
GLSL Version: 4.60 glslang Khronos. 12.0.0
SPIR-V Version 0x00010600, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 11
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
checking for C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe ... ok
checking for flags (/MT) ... ok
checking for flags (cl_external_includedir) ... ok
> checking for c++ includes(glslang/Public/ShaderLang.h)
> checking for c++ funcs(ShInitialize)
> checking for c++ links(SPIRV-Tools-link, SPIRV-Tools-reduce, SPIRV-Tools-opt, SPIRV-Tools)
> checking for c++ snippet(has_cxxfuncs)
error: _28F3F4947BF14E38B12A94A836403C38.o : error LNK2019: 无法解析的外部符号 ShInitialize，函数 main 中引用了该符号
C:\Users\libreliu\AppData\Local\Temp\.xmake\230425\_28F3F4947BF14E38B12A94A836403C38.b : fatal error LNK1120: 1 个无法解析的外部命令

  => install glslang 1.3.239+0 .. failed
error: install failed!
error: execv(xmake require -v -j 1 --extra={system=false,debug=true} "glslang 1.3.239+0") failed(-1)
```

### 期待的结果

可以成功运行 `xrepo install -m debug -j 1 --verbose "glslang 1.3.239+0"`。

> 本身我是在 `add_requires` 中指定的，不过我发现 xrepo 这边也编不过...这应该是 minimal reproducible example..？

**Comment by waruqi** [comment]
找下相关符号在哪个库，然后调下 包。提个pr 过来

**Comment by libreliu** [comment]
> 找下相关符号在哪个库，然后调下 包。提个pr 过来

感谢回复，现在定位问题是 glslang 会对 win32 平台编译的静态库后面设置 `set(CMAKE_DEBUG_POSTFIX "d")`，导致 package 的 link hint 和此处不一致。

我在尝试 `io.replace("CMakeLists.txt", 'set(CMAKE_DEBUG_POSTFIX "d")', "", {plain = true})`，等调通了提个 pr 来

**Comment by libreliu** [comment]
Update: 应用[这个 commit](https://github.com/libreliu/xmake-repo/commit/bfa2841a0cf8b29817b2d5f93acfcf44b96c5572） 现在可以编译 Debug 版本了，不过正如在 #2031 描述的问题，现在调试仍然缺源码，感觉不是很好的解决方案

**Comment by waruqi** [comment]
重置这个 CMAKE_COMPILE_PDB_OUTPUT_DIRECTORY ，是会让 编译器生成默认的 pdb 路径么。。vc140.pdb 这种？

为什么置空这个 就不会冲突？会有其他副作用么？ 如果它是通用的解决方式，且没有其他影响，可以放到 tools.cmake 里面去处理

**Comment by libreliu** [comment]
`CMAKE_COMPILE_PDB_OUTPUT_DIRECTORY` 的设置是在 https://github.com/xmake-io/xmake/commit/10a2694a516ddf2441bb1ea0d46e0738a631d541 引入的
直接把 `CMAKE_COMPILE_PDB_OUTPUT_DIRECTORY` 删掉看起来会影响写了 CMake Install 的库的 pdb 的拷贝

置空不会冲突感觉是因为现在每个 target 似乎会有独立的目录来输出 pdb，所以不会并行写 (#2031 提到的，不过我没有 fact check)

不过至少 #2036 让两个包的 debug 版本都可以编译了（捂脸），配合源码可以调试了；这个问题可能值得之后仔细调查一下...

**Comment by libreliu** [comment]
既然已经可以编译啦，我就把这个 issue 关掉了，感谢 ruqi 和隔壁 issue 的那位小伙伴
