### ISSUE TITLE
能不能通过查询github release的api来自动添加add_versions?

### ISSUE THREAD

**Issue by masx200** [xmake-io/xmake-repo#2097]
### 你在什么场景下需要该功能？

能不能通过查询github release的api来自动添加add_versions?

### 描述可能的解决方案

能不能通过查询github release的api来自动添加add_versions?

### 描述你认为的候选方案

xmake可以发送网络http请求和解析常用的数据类型吗,或者使用第三方工具?

### 其他信息
`add_versions("12.2.6", "12.2.6")`

**Comment by waruqi** [comment]
暂时不考虑，每个版本都需要 ci 压测的，而且版本太多也方便维护，按需添加。

**Comment by masx200** [comment]
> 暂时不考虑，每个版本都需要 ci 压测的，而且版本太多也方便维护，按需添加。

我说的是在第三方仓库里面使用,不是这个仓库

**Comment by waruqi** [comment]
不支持
