### ISSUE TITLE
expected 包重复了

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake-repo#2109]
### Xmake 版本

2.7.8

### 操作系统版本和架构

windows 11

### 描述问题

https://github.com/xmake-io/xmake-repo/blob/master/packages/e/expected/xmake.lua
https://github.com/xmake-io/xmake-repo/blob/master/packages/t/tl_expected/xmake.lua

更新完了 expected 版本才发现这个包之前出现了两次 还有个tl_expected包内容一样，可能需要ruki大佬处理下

### 期待的结果

更新tl_expected这个包，删掉另一个包

**Comment by waruqi** [comment]
你来个 pr 过来就好了，以 tl_expected 为主，更新下。。不过 expected 现在应该也有人用，暂时别删，走 set_base 指向 tl_expected，同步成一份代码。。

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/2110

expected 应该已经警告提示几年了，我去掉了。

**Comment by heheda123123** [comment]
ok
