### ISSUE TITLE
完善对 qt6 的支持

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake-repo#2124]
### 你在什么场景下需要该功能？

qt6也出来了一段时间了，从qt6.2开始模块就已经补全，现在已经到qt6.5了，市面也有出现了不少qt6的学习资料，
希望补充对qt6的支持

### 描述可能的解决方案

看了下，有大佬一年前已经提了pr https://github.com/xmake-io/xmake-repo/pull/1081 ，但是有遇到不少问题，
我刚开始学 qt 还不熟悉
希望大佬能完善这块的支持

**Comment by waruqi** [comment]
qt6 支持的，你可以直接走qt官方安装包集成。。xmake 的 qt6 包，目前没时间搞，你可以提 pr 进来。

**Comment by heheda123123** [comment]
咦，可能是我之前理解错了。
意思是之前qt5的包不用装官方集成包，自动可以下载？
我之前瞄了眼xmake-repo里面qt包的内容，没看到下载地址，以为也要自己先装好qt官方的集成包

**Comment by waruqi** [comment]
xmake-repo 的 qt 包，提供自动下载的能力 和自动集成使用，但你可以不用这个包，自己走 `xmake f --qt=` 切到自己安装的 qt sdk。。
