### ISSUE TITLE
Zigup support: Unofficial zig compilers manager

### ISSUE THREAD

**Issue by kassane** [xmake-io/xmake-repo#2159]
### Is your feature request related to a problem? Please describe.

**Reference**
- https://github.com/xmake-io/xmake/issues/3837

Unfortunately problems may occur when not identifying the environment path the zig installation.
If it fails to detect zig, xmake can recommend downloading the available version, although these are old and fixed versions that require new changes to support new versions.

### Describe the solution you'd like

This project download and manage zig compilers, like rustup.
https://github.com/marler8997/zigup/releases

Hopefully this tool will allow the xmake user to choose the zig version to be downloaded, from released versions to master/nightly. Marking the PATH exclusively linked to xmake and the toolchain.

**Comment by waruqi** [comment]
we need not it, because xmake support download specific version zig and use it automatically.

https://github.com/xmake-io/xmake-repo/tree/master/packages/z/zig

https://github.com/xmake-io/xmake/blob/master/tests/projects/package/toolchain_zig/xmake.lua
