### ISSUE TITLE
If a project changes the building system, what should be done?

### ISSUE THREAD

**Issue by juteman** [xmake-io/xmake-repo#222]
https://github.com/oneapi-src/oneTBB
tbb 2021 version use cmake instead of make. But the https://github.com/xmake-io/xmake-repo/blob/master/packages/t/tbb/xmake.lua script is still the version 2020.3 .

can we keep 2020.3 version and 2021 vesion both in xmake script?

**Comment by waruqi** [comment]
```lua
if package:version():ge("2021.3") then
    -- use cmake
else
    -- use make
end
```

**Comment by juteman** [comment]
thanks for your help
