### ISSUE TITLE
xrepo --root list-repo 报错

### ISSUE THREAD

**Issue by hjwsm1989** [xmake-io/xmake-repo#2250]
### Xmake 版本

2.7.9+20230625

### 操作系统版本和架构

rocky9.0

### 描述问题

`[root@10-16-43-4 ~]# XMAKE_ROOT=y xrepo list-repo
global repositories:
    build-artifacts https://gitee.com/xmake-mirror/build-artifacts.git main 
    xmake-repo https://gitee.com/tboox/xmake-repo.git master 
    builtin-repo /root/.local/share/xmake/repository 

3 repositories were found!
[root@10-16-43-4 ~]# xrepo --root list-repo
error: Running xmake as root is extremely dangerous and no longer supported.
As xmake does not drop privileges on installation you would be giving all
build scripts full access to your system.
Or you can add `--root` option or XMAKE_ROOT=y to allow run as root temporarily.
            
[root@10-16-43-4 ~]# XMAKE_ROOT=y xrepo --version
xRepo 2.7.9+20230625/xmake, A cross-platform C/C++ package manager based on Xmake.
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io

    __  ___ ___  ______ ____  _____
    \ \/ / |  _ \| ____|  _ \/  _  |
     >  <  | |_) |  _| | |_) | |_| |
    /_/\_\_| \___|_____|_|   |____/
                         by ruki, xmake.io
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor`

### 期待的结果

xrepo --root list-repo能执行成功

**Comment by waruqi** [comment]
> error: Running xmake as root is extremely dangerous and no longer supported.
As xmake does not drop privileges on installation you would be giving all
build scripts full access to your system.

看提示。。 root 下我不做技术支持，一切问题和后果自己解决。

**Comment by hjwsm1989** [comment]
> > error: Running xmake as root is extremely dangerous and no longer supported.
> > As xmake does not drop privileges on installation you would be giving all
> > build scripts full access to your system.
> 
> 看提示。。 root 下我不做技术支持，一切问题和后果自己解决。

明白，只是说XMAKE_ROOT=y可以执行，而提示的--root却不行。
