### ISSUE TITLE
SDL Wayland support

### ISSUE THREAD

**Issue by Persson-dev** [xmake-io/xmake-repo#2257]
### Is your feature request related to a problem? Please describe.

SDL currently supports X11 with the `with_x` config.
It would be nice to have support for Wayland as well (since I'm using it).

### Describe the solution you'd like

Adding a `with_wayland` config to compile with Wayland support.

**Comment by waruqi** [comment]
you can open a pr to improve sdl package.

**Comment by Persson-dev** [comment]
Fixed with #2563
