### ISSUE TITLE
Including package which is already included by another as dependency

### ISSUE THREAD

**Issue by WSSDude** [xmake-io/xmake-repo#2288]
### Xmake Version

xmake v2.7.9+dev.c0d12baa5

### Operating System Version and Architecture

Windows 11 22H2 64-bit

### Describe Bug

When user tries to include package other package already has set as dependency, build may fail on linking step due to mixed symbols in case of custom configuration.

Good example is SDL2 and ImGui with SDL2 config option. Shown in example.

This installs SDL2 for ImGui in static and release mode (believe it is release mode based on library name from log at least), while I already use SDL2 in my program in shared and debug mode. 

This causes symbols to clash.

I wanted to try to use backends installed by xmake instead of manually keeping them up-to-date, but I can't because of this issue.

### Expected Behavior

I would expect that if user includes package some other package is using as dependency, my package include takes precedence and include inside package is ignored.

Or I would expect dependency to otherwise inherit the properties (if I want to build debug, let dependency be built in debug, etc.)

Maybe this could resolve the clash also.

### Project Configuration

Don't think vs_runtime has anything to do with this, believe it is combination of shared and debug causing troubles with dependencies... But this should be equivalent to config causing troubles.

```lua
add_requires("libsdl 2.28.1", { configs = { shared = true, debug = true, vs_runtime = "MDd" } })

add_requires("imgui v1.89.7-docking", { configs = { sdl2 = true, shared = false, debug = true, vs_runtime = "MDd" } })
```

### Additional Information and Error Logs

Error log produced by above config

4>EXEC : error : SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_CreateRenderer already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_CreateWindow already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_DestroyRenderer already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_DestroyWindow already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_GetBasePath already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_GetDisplayDPI already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_GetError already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_GetPrefPath already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_GetRendererInfo already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_GetWindowID already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_Init already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_PollEvent already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_Quit already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_RenderClear already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_RenderPresent already defined in SDL2d.lib(SDL2d.dll)
4>SDL2-static.lib(SDL_dynapi.obj) : error LNK2005: SDL_SetRenderDrawColor already defined in SDL2d.lib(SDL2d.dll)

**Comment by SirLynix** [comment]
This is because you required "libsdl 2.28.1" as shared and imgui required libsdl as static.

While I agree we should have a better solution for this, you can just not require libsdl (as it's already required by imgui) and configure it using add_requiresconfs:

```lua
add_requires("libsdl 2.28.1", { configs = { shared = true, debug = true, vs_runtime = "MDd" } })

add_requires("imgui v1.89.7-docking", { configs = { sdl2 = true, shared = false, debug = true, vs_runtime = "MDd" } })
```

=>

```lua
add_requires("imgui v1.89.7-docking", { configs = { sdl2 = true, shared = false, debug = true, vs_runtime = "MDd" } })
add_requireconfs("imgui.libsdl", { configs = { shared = true, debug = true, vs_runtime = "MDd" }})
```

(btw you don't have to set vs_runtime for each package, just call `set_runtimes("MDd")` once and every package will automatically inherit it)

**Comment by WSSDude** [comment]
I don't want to statically link to SDL2 though, so I guess I have to stick to manual backends inclusion for now.

They themselves mention it is better to use SDL2 in shared mode. It has various advantages in regards to distributing apps also.
https://github.com/libsdl-org/SDL/blob/main/docs/README-dynapi.md

**Comment by WSSDude** [comment]
Don't know if this answer basically means we won't fix it and this can be closed or if this should be kept open now so feel free to close it if you want. I guess I got my answer in regards as to what to do for now 🙇

**Comment by SirLynix** [comment]
> I don't want to statically link to SDL2 though, so I guess I have to stick to manual backends inclusion for now.

You don't have to, `add_requireconfs` set imgui to use libsdl in shared

**Comment by WSSDude** [comment]
How would that look please? Never tried to set inner dependency config 😁 Didn't even know you can.

**Comment by SirLynix** [comment]
Did you read my message? I gave you a code doing that

**Comment by WSSDude** [comment]
Oh, I read it but I somehow didnt see it 🤦‍♂️ My bad... Thank you 🙇
