### ISSUE TITLE
Update protobuf-c library from 1.3.1 to 1.4.1

### ISSUE THREAD

**Issue by YugoCode** [xmake-io/xmake-repo#2388]
### Is your feature request related to a problem? Please describe.

The current version of the protobuf-c library in the official repo is 1.3.1. The latest released version is 1.4.1.  

### Describe the solution you'd like

Could you please support the latest version?

**Comment by waruqi** [comment]
you can open a pr to add new version.

**Comment by exalight87** [comment]
I opened a pr for that : https://github.com/xmake-io/xmake-repo/pull/2490
