### ISSUE TITLE
添加UniversalStacktrace包

### ISSUE THREAD

**Issue by jingkaimori** [xmake-io/xmake-repo#2413]
### 你在什么场景下需要该功能？

[PikachuHy/pscm](https://github.com/PikachuHy/pscm) 项目采用[UniversalStacktrace](https://github.com/MisterTea/UniversalStacktrace)包来打印堆栈调试信息。[UniversalStacktrace包的用户](https://github.com/search?q=UniversalStacktrace&type=code)。

这个包没有发行版的tar包，而且把依赖放到git的子模块里面，因此需要在镜像仓库里生成稳定的版本。

### 描述可能的解决方案

- [ ] 在xmake-mirror添加镜像
- [ ] 用xrepo的`catch2`包取代子模块

### 描述你认为的候选方案

把这个包port到xmake里

**Comment by waruqi** [comment]
> 没懂，这和 xmake 有什么关系。而且一个几个月没更新的单头文件库，直接内置源码在项目不就行了么

我猜他的意思是

1. 想要 [UniversalStacktrace](https://github.com/MisterTea/UniversalStacktrace) 做成包放进来，但是没有固定版本 tag，所以没有 tar 包。。这个走 fake date version -> git commit  就行了。。可以参考其他包 @jingkaimori 

2. 里面内置 [external](https://github.com/MisterTea/UniversalStacktrace/tree/master/external) 目录的 catch2 依赖，从 cmakelists 里面去掉，完全走 xmake-repo 仓库的外置 catch2 依赖 ， add_deps 引入。。避免多个包时候有依赖冲突。

这种 io.replace 或者 add_patches 去 patch 下 Cmakelists 就行了。或者直接 port 到 xmake.lua

**Comment by waruqi** [comment]
> 这个包没有发行版的tar包，而且把依赖放到git的子模块里面，因此需要在镜像仓库里生成稳定的版本。

可以用这个脚本 https://github.com/xmake-io/xmake-repo#create-a-package-template-from-github

直接生成一个包模版，没有 tar 的包，会自动用 git commit 。。

```
xmake l scripts/new.lua github:MisterTea/UniversalStacktrace
```

**Comment by waruqi** [comment]
[done ](https://github.com/xmake-io/xmake-repo/pull/2415)
