### ISSUE TITLE
Windwos 上安装 spdlog 失败

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake-repo#25]
cache里有下载，解压后的目录里也有include目录，但不知为啥始终报找不到

install.txt 显示如下：
cannot copy file include, error: not found this file

测试命令显示如下：
PS D:\xmake\.xmake\repositories\xmake-repo> xmake l scripts/test.lua -v -D —shallow spdlog
{
  "spdlog"
}

create test ...
create ok!👌
C:\Users\ADMINI~1\AppData\Local\Temp\.xmake\190908\xmake-repo\test
add local repository(local-repo): D:\xmake\.xmake\repositories\xmake-repo ok!
local repositories:
    local-repo D:\xmake\.xmake\repositories\xmake-repo

global repositories:
    xmake-repo https://gitee.com/tboox/xmake-repo.git master
    builtin-repo C:\Program Files\xmake\repository

3 repositories were found!
checking for the architecture ... x64
checking for the vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for the cl.exe ... ok
checking for the Microsoft Visual Studio (x64) version ... 2017
configure
{
    arch = x64
    ccache = true
    clean = true
    plat = windows
    mode = release
    kind = static
    buildir = build
    vs = 2017
    host = windows
    ndk_stdcxx = true
}
configure
{
    arch = x64
    ccache = true
    mode = release
    ndk_stdcxx = true
    plat = windows
    host = windows
    kind = static
    buildir = build
    vs = 2017
    clean = true
}
checking for the unzip ... ok
checking for the git ... ok
checking for the gzip ... no
checking for the 7z ... ok
checking for the ping ... ok
pinging for the host(gitlab.com) ... 263 ms
checking for the nmap ... no
pinging for the host(github.com) ... 65535 ms
pinging for the host(gitee.com) ... 24 ms
7z x -y v1.3.1.tar.gz -oC:\Users\ADMINI~1\AppData\Local\Temp\.xmake\190908\_EC55959E5CB8F24A8E181C0350F07B73.tar

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 202634 bytes (198 KiB)

Extracting archive: v1.3.1.tar.gz
--
Path = v1.3.1.tar.gz
Type = gzip
Headers Size = 10

Everything is Ok

Size:       1064960
Compressed: 202634
7z x -y C:\Users\ADMINI~1\AppData\Local\Temp\.xmake\190908\_EC55959E5CB8F24A8E181C0350F07B73.tar\v1.3.1.tar -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 1064960 bytes (1040 KiB)

Extracting archive: C:\Users\ADMINI~1\AppData\Local\Temp\.xmake\190908\_EC55959E5CB8F24A8E181C0350F07B73.tar\v1.3.1.tar
--
Path = C:\Users\ADMINI~1\AppData\Local\Temp\.xmake\190908\_EC55959E5CB8F24A8E181C0350F07B73.tar\v1.3.1.tar
Type = tar
Physical Size = 1064960
Headers Size = 71168
Code Page = UTF-8

Everything is Ok

Folders: 14
Files: 113
Size:       963016
Compressed: 1064960
error: @programdir\core\sandbox\modules\os.lua:80: cannot copy file include, error: not found this file
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:762]: in function 'raise'
    [@programdir\core\sandbox\modules\os.lua:80]: in function 'cp'
    [...make\repositories\xmake-repo\packages\s\spdlog\xmake.lua:12]: in function 'script'
    [@programdir\actions\require\impl\utils\filter.lua:119]: in function 'call'
    [@programdir\actions\require\impl\action\install.lua:180]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\actions\require\impl\action\install.lua:142]: in function 'install'
    [@programdir\actions\require\impl\package.lua:594]:

  => install spdlog 1.3.1 .. failed
error: @programdir\core\sandbox\modules\process.lua:148: @programdir\actions\require\impl\action\install.lua:262: install failed!
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:762: in function 'raise'
        @programdir\actions\require\impl\action\install.lua:262: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\actions\require\impl\action\install.lua:142: in function 'install'
        @programdir\actions\require\impl\package.lua:594: in function <@programdir\actions\require\impl\package.lua:519>
error: execv(xmake require -f -y -v -D spdlog) failed(4294967295)!

**Comment by fasiondog** [comment]
刚看了下历史记录，已经改了。不过 xmake repo -u 似乎更新不过来

**Comment by waruqi** [comment]
只有xmake.lua里面有新包，或者手动xmake f -c 加-c 重新配置 才会重拉。。或者手动执行 xmake repo -u
