### ISSUE TITLE
lua 无法编译 debug 模式

### ISSUE THREAD

**Issue by q962** [xmake-io/xmake-repo#2584]
### Xmake Version

xmake v2.8.2+HEAD.57212c6, 

### Operating System Version and Architecture

Linux ti-ji-pc 6.2.12-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 20 23:38:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Describe Bug

```
$ xrepo install -m debug -k shared -vD lua
```
通过观察其输出，并没有发现 `-g`

### Expected Behavior

当我在 `target("lualib")` 目标下添加 `add_rules("mode.debug", "mode.release")` 时，得到了正确的结果。

### Project Configuration

-

### Additional Information and Error Logs

-

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/2585

**Comment by waruqi** [comment]
再试试

```
xrepo update-repo
```

**Comment by q962** [comment]
ok
