### ISSUE TITLE
xrepo安装mingw-w64出错

### ISSUE THREAD

**Issue by darcy-shen** [xmake-io/xmake-repo#2589]
### Xmake 版本

2.8.2

### 操作系统版本和架构

Windows 11

### 描述问题

```
> xrepo install "mingw-w64"
error: checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... no
error: target(working): toolchain not found!
```

### 期待的结果

不需要安装msvc就可以直接安装mingw-w64，因为这个过程应该只涉及下载

### 工程配置

无

### 附加信息和错误日志

无

**Comment by darcy-shen** [comment]
好像那个xrepo的package路劲中的hash计算规则中其中一项就是platform，但感觉这个toolchain本身应该是有例外的

**Comment by darcy-shen** [comment]
> xrepo install -p mingw mingw-w64

实测，这样还是不行的，我试试先用scoop安装一个mingw

**Comment by darcy-shen** [comment]
最终这样解决了：
```
xrepo install -p mingw --mingw=C:\Users\darcy\scoop\apps\mingw\current mingw-w64
```
这个对新用户来说，不那么友好

**Comment by star-hengxing** [comment]
不过我感觉没多少用户会用这个功能，而且 Windows 上现在三大编译器都可以命令行安装，llvm 和 mingw 用 scoop，vs2022 用 winget

**Comment by darcy-shen** [comment]
> vs2022 用 winget

原来可以winget，感谢！我之前都是手动安装的。。。
