### ISSUE TITLE
Cannot install `drogon`

### ISSUE THREAD

**Issue by Chi-EEE** [xmake-io/xmake-repo#2665]
### Xmake Version

2.8.3

### Operating System Version and Architecture

Windows 10 Home 22H2

### Describe Bug

Cannot install `drogon` because `c-ares`'s method is not linked and is referenced in `trantor`

### Expected Behavior

Installs `drogon` with no error

### Project Configuration

The following command does not work:
`xrepo install drogon`

### Additional Information and Error Logs

Log from `xrepo install drogon`:
https://pastebin.com/MNmykYhG (over 65536 characters)

**Comment by waruqi** [comment]
it will patch drogon's cmakelists and pass c-ares links into it.
