### ISSUE TITLE
include glfw/deps in glfw package

### ISSUE THREAD

**Issue by mtoons** [xmake-io/xmake-repo#2677]
### Is your feature request related to a problem? Please describe.

I was trying to create a project with xmake and glfw and when i wasn't able to use linmath.h i discover that the entire deps folder was missing

### Describe the solution you'd like

adding the deps folder to the glfw package

### Describe alternatives you've considered

i might try to install the lib manually

**Comment by waruqi** [comment]
These are third-party dependencies, they don't belong to glfw, you should make it a separate package and submit pr to xmake-repo

https://github.com/datenwolf/linmath.h

then you can use `add_requires("linmath")` to use it.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/2684

**Comment by waruqi** [comment]
you can use `add_requires("linmath.h")` now.

please run `xrepo update-repo` first.
