### ISSUE TITLE
mysql包在ubuntu上安装失败

### ISSUE THREAD

**Issue by KkemChen** [xmake-io/xmake-repo#2784]
### Xmake 版本

2.8.3

### 操作系统版本和架构

Ubuntu18.04

### 描述问题

我在使用xmake安装mysql包的时候，碰到了如下截图的问题。
![image](https://github.com/xmake-io/xmake-repo/assets/44298896/97408f5e-aa75-4e65-b57f-794cd658ad03)

除此之外，我在自己的项目中使用的时候，当我指定使用5.7.29版本的mysql包时，会出现下载下来的包hash对不上，但是我手动下载下来后 查看hash跟repo里描述的hash是一致的
![G{NOH7) _{7D3PCEO{FDYGR](https://github.com/xmake-io/xmake-repo/assets/44298896/874976a3-50d0-4f20-82fb-48e720c519eb)
![OD5IX41E3%I%D9 U8ONJC{G](https://github.com/xmake-io/xmake-repo/assets/44298896/af7842fb-bcca-4182-b3ae-23aafe422d7d)

### 期待的结果

望大佬尽快修复

### 工程配置

使用的xmake-repo提供的测试
xmake l scripts/test.lua -v -D --shallow mysql

### 附加信息和错误日志

如上描述

**Comment by waruqi** [comment]
> 除此之外，我在自己的项目中使用的时候，当我指定使用5.7.29版本的mysql包时，会出现下载下来的包hash对不上，但是我手动下载下来后 查看hash跟repo里描述的hash是一致的

你手动下载的，不代表 xmake 调用 curl 下载的结果 就完全一样，手动下载成功，完整状态 hash 肯定一致，但是 xmake 下载，如果下载中途失败，或者其他原因，也会导致 hash 不一致，你要验证实际 xmake 下载的那个 tar 包，是否完整下全，验证自己手动下载的 没啥意义。

> 我在使用xmake安装mysql包的时候，碰到了如下截图的问题。

mysql 里面，之前别人 pr 进来，zlib 版本依赖写死了，一种就是你再提 pr 改进下包，一种就是走 add_requireconfs 自己外面重写下 mysql.zlib 的版本

**Comment by KkemChen** [comment]
> > 除此之外，我在自己的项目中使用的时候，当我指定使用5.7.29版本的mysql包时，会出现下载下来的包hash对不上，但是我手动下载下来后 查看hash跟repo里描述的hash是一致的
> 
> 你手动下载的，不代表 xmake 调用 curl 下载的结果 就完全一样，手动下载成功，完整状态 hash 肯定一致，但是 xmake 下载，如果下载中途失败，或者其他原因，也会导致 hash 不一致，你要验证实际 xmake 下载的那个 tar 包，是否完整下全，验证自己手动下载的 没啥意义。
> 
> > 我在使用xmake安装mysql包的时候，碰到了如下截图的问题。
> 
> mysql 里面，之前别人 pr 进来，zlib 版本依赖写死了，一种就是你再提 pr 改进下包，一种就是走 add_requireconfs 自己外面重写下 mysql.zlib 的版本

我换了一台阿里云，在上面直接拉这个mysql的包进行安装测试， curl 下载mysql一直没成功，这种情况该怎么解决

**Comment by waruqi** [comment]
> > > 除此之外，我在自己的项目中使用的时候，当我指定使用5.7.29版本的mysql包时，会出现下载下来的包hash对不上，但是我手动下载下来后 查看hash跟repo里描述的hash是一致的
> > 
> > 
> > 你手动下载的，不代表 xmake 调用 curl 下载的结果 就完全一样，手动下载成功，完整状态 hash 肯定一致，但是 xmake 下载，如果下载中途失败，或者其他原因，也会导致 hash 不一致，你要验证实际 xmake 下载的那个 tar 包，是否完整下全，验证自己手动下载的 没啥意义。
> > > 我在使用xmake安装mysql包的时候，碰到了如下截图的问题。
> > 
> > 
> > mysql 里面，之前别人 pr 进来，zlib 版本依赖写死了，一种就是你再提 pr 改进下包，一种就是走 add_requireconfs 自己外面重写下 mysql.zlib 的版本
> 
> 我换了一台阿里云，在上面直接拉这个mysql的包进行安装测试， curl 下载mysql一直没成功，这种情况该怎么解决

curl 下载不成功和网络问题，我也没办法，你得找 curl 那边，或者自己调下网络。。xmake 也只是调用 curl

**Comment by KkemChen** [comment]
> > > > 除此之外，我在自己的项目中使用的时候，当我指定使用5.7.29版本的mysql包时，会出现下载下来的包hash对不上，但是我手动下载下来后 查看hash跟repo里描述的hash是一致的
> > > 
> > > 
> > > 你手动下载的，不代表 xmake 调用 curl 下载的结果 就完全一样，手动下载成功，完整状态 hash 肯定一致，但是 xmake 下载，如果下载中途失败，或者其他原因，也会导致 hash 不一致，你要验证实际 xmake 下载的那个 tar 包，是否完整下全，验证自己手动下载的 没啥意义。
> > > > 我在使用xmake安装mysql包的时候，碰到了如下截图的问题。
> > > 
> > > 
> > > mysql 里面，之前别人 pr 进来，zlib 版本依赖写死了，一种就是你再提 pr 改进下包，一种就是走 add_requireconfs 自己外面重写下 mysql.zlib 的版本
> > 
> > 
> > 我换了一台阿里云，在上面直接拉这个mysql的包进行安装测试， curl 下载mysql一直没成功，这种情况该怎么解决
> 
> curl 下载不成功和网络问题，我也没办法，你得找 curl 那边，或者自己调下网络。。xmake 也只是调用 curl

嗯，那mysql这个脚本里，它依赖的zlib 1.2.13，xmake没办法自动去下载zlib 1.2.13来使用吗。

**Comment by waruqi** [comment]
> 嗯，那mysql这个脚本里，它依赖的zlib 1.2.13，xmake没办法自动去下载zlib 1.2.13来使用吗。

?? 不懂什么意思，所有的包 不都是自动下载的么，只要系统库没找到

**Comment by KkemChen** [comment]
> > 嗯，那mysql这个脚本里，它依赖的zlib 1.2.13，xmake没办法自动去下载zlib 1.2.13来使用吗。
> 
> ?? 不懂什么意思，所有的包 不都是自动下载的么，只要系统库没找到

就是系统找到的这个版本 不满足要求，xmake可以自动去下载满足要求的zlib版本来进行后续的安装么

**Comment by waruqi** [comment]
> > > 嗯，那mysql这个脚本里，它依赖的zlib 1.2.13，xmake没办法自动去下载zlib 1.2.13来使用吗。
> > 
> > 
> > ?? 不懂什么意思，所有的包 不都是自动下载的么，只要系统库没找到
> 
> 就是系统找到的这个版本 不满足要求，xmake可以自动去下载满足要求的zlib版本来进行后续的安装么

是否满足要求 是要用户告诉 xmake 的，（通过 add_requires/add_requireconfs 配置版本，或者包配置里配置版本）。。

否则 xmake 怎么知道怎样的要求才是满足的。。而用户都配置告诉 xmake 哪个版本是满足要求的，那一开始的拉取就已经是正确的版本了，也就没有自动下载其他版本一说。。

另外，所有的包里面原本 add_deps 就不应该写死版本的，外面用户自己 add_requireconfs。。而这里它写死了，也是之前的包贡献者写的，我不清楚他为什么要写死，按我的理解，他可能当初遇到其他版本的 zlib 导致 mysql 编译不过，不满足所谓的要求，所以才必须要写死。。当然我也没时间去验证，如果不是这种情况，你也可以提 pr 继续改进 mysql 包，去掉版本号，看下 ci 是否通过。

**Comment by KkemChen** [comment]
我看了mysql的cmake里面，要求zlib必须大于1.2.12才能进行后续的编译，只是我现在不知道该怎么改mysql这个包😅

**Comment by waruqi** [comment]
> 我看了mysql的cmake里面，要求zlib必须大于1.2.12才能进行后续的编译，只是我现在不知道该怎么改mysql这个包😅

那就 mysql 里面 add_deps 改成 `>= 1.2.12`，然后自己的项目，还是走 `add_requireconfs` 打平 zlib 依赖版本

```lua
add_requireconfs("mysql.zlib", {override = true, "1.2.13"})
add_requireconfs("mysql.**.zlib", {override = true, "1.2.13"})
```

**Comment by KkemChen** [comment]
ok
