### ISSUE TITLE
请求增加第3方net的mono

### ISSUE THREAD

**Issue by xizhengchao** [xmake-io/xmake-repo#28]

**Comment by waruqi** [comment]
这里是c/c++的依赖包仓库，这跟net和mono有啥关系，请详细描述需求！！！

**Comment by xizhengchao** [comment]
这个是c语言的运行时，运行c#，vb，java等等的，win,liunx,mac,ios,Android,等等,还支持mips的。https://github.com/mono/mono，兼容性好，性能可以。

**Comment by xizhengchao** [comment]
可以通过c/c++调用，net之类的语言。通过mono下面的c语言的api

**Comment by waruqi** [comment]
这个repo只集成c/c++静态库，动态库，不集成运行时
