### ISSUE TITLE
Ctre update

### ISSUE THREAD

**Issue by Extra-Creativity** [xmake-io/xmake-repo#2852]
### Is your feature request related to a problem? Please describe.

CTRE version is about 2 years ago, now it's 3.8.1 instead of 3.4.1(and in xrepo even only one version is provided...).
Isn't there any feature to update automatically?

### Describe the solution you'd like

Add more versions of ctre.

**Comment by waruqi** [comment]
> Isn't there any feature to update automatically?

not supported yet, but you can open a pr to update it.

**Comment by Extra-Creativity** [comment]
> > Isn't there any feature to update automatically?
> 
> not supported yet, but you can open a pr to update it.

I would like to, but what is the source string of sha256 hash for `add_version`?

**Comment by waruqi** [comment]
> > > Isn't there any feature to update automatically?
> > 
> > 
> > not supported yet, but you can open a pr to update it.
> 
> I would like to, but what is the source string of sha256 hash for `add_version`?

sha256 of tar.gz file in add_urls

you can use `shasum -a 256 file` or `xmake l hash.sha256 file` to get it.
