### ISSUE TITLE
添加 asio2 库，脚本已写好

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake-repo#2889]
### 你在什么场景下需要该功能？

脚本如下
```
package("asio2")

    set_kind("library", {headeronly = true})
    set_homepage("https://github.com/zhllxt/asio2")
    set_description("Header only c++ network library, based on asio, support tcp,udp,http,websocket,rpc,ssl,icmp,serial_port.")
    set_license("BSL-1.0")

    add_urls("https://github.com/zhllxt/asio2.git")
    add_versions("2023.05.09", "ac8c79964d79020091e38fcbb4ae9dccccb3b03c")

    on_install(function (package)
            os.cp(path.join("3rd" , "*"), package:installdir("include"))
            os.cp(path.join("include", "*"), package:installdir("include"))
    end)

    on_test(function (package)
        assert(package:check_cxxsnippets({test = [[
            #include <asio2/asio2.hpp>
            void test() {
                asio2::tcp_server server;
            }
        ]]}, {configs = {languages = "c++17"}}))
    end)

```

### 描述可能的解决方案

rt

**Comment by heheda123123** [comment]
话说有什么方便的方法添加新库吗？如果只是修改已有的包很方便，但是想新增包就比较麻烦，我之前提交的步骤如下
1 先在自己的fork同步最新的xmake-repo
2 自己本地加上之后pull到自己的fork
3 提交pr合并到xmake-repo的dev上

这样一般没啥问题，但是如果在之前已经提交了pr，还没合并的情况下再提交就会互相干扰，比如上面这个asio2的，就和之前acl-server的干扰了。
貌似第二步，创建个分支，在分支里面添加，然后pull到自己的fork上，再合并那个分支到xmake-repo的dev上就不会干扰了。不过还是比较麻烦。如果能比较方便，像修改已有包一样直接在github网页上操作就好了

**Comment by waruqi** [comment]
每个包都是独立的，为啥会冲突，单独开分支提 pr ，如果有依赖关系，那就 依赖包被merge后，rebase 下另外一个 branch pr ，重新 push force 下

**Comment by heheda123123** [comment]
> 每个包都是独立的，为啥会冲突，单独开分支提 pr ，如果有依赖关系，那就 依赖包被merge后，rebase 下另外一个 branch pr ，重新 push force 下

因为默认都是选的从我的master合并过来
![image](https://github.com/xmake-io/xmake-repo/assets/97490782/86ff283a-096e-4c3b-a3c3-affb65cbc0f1)
有时候我忘了之前的还没合并就又提交到自己的master了
![image](https://github.com/xmake-io/xmake-repo/assets/97490782/c249a1dc-3c63-41a9-82b3-731320896fcd)
