### ISSUE TITLE
请麻烦增加libwebsockets 这个c库

### ISSUE THREAD

**Issue by xizhengchao** [xmake-io/xmake-repo#29]
libwebsockets  这个c库是跨平台的webscoket，还是有用的，它这个是cmake弄的。麻烦请增加这个。

**Comment by waruqi** [comment]
我加上了，由于个人时间精力有限，不一定每次都能即时添加一些包需求，如果自己有些包需要使用，也可以自己参考文档，制作和提交包到仓库，详情可看下文档：https://xmake.io/#/zh-cn/package/remote_package?id=%e6%b7%bb%e5%8a%a0%e5%8c%85%e5%88%b0%e4%bb%93%e5%ba%93

**Comment by xizhengchao** [comment]
好的，提供教程后，我们可以自己添加上去，主要是之前没有找到相关文档，制作包的
