### ISSUE TITLE
Hi，pcl库能添加ios系统下的编译选项吗？

### ISSUE THREAD

**Issue by 11janson** [xmake-io/xmake-repo#2907]
### 你在什么场景下需要该功能？

项目需要在ipad里开发点云后处理软件，需要ios系统下编译的pcl库？

### 描述可能的解决方案

我发现现在pcl支持"windows", "linux", "macosx"这三种平台编译，加上ios会解决我的项目需求

### 描述你认为的候选方案

我也在本地尝试自己修改包描述，不知道能否成功。vcpkg里有人成功在ios下编译了pcl库，应该是可以走通的

**Comment by waruqi** [comment]
你可以试下，来个 pr 放开 iphoneos ，然后跑通 ci 就行了

**Comment by 11janson** [comment]
> 你可以试下，来个 pr 放开 iphoneos ，然后跑通 ci 就行了

今天在mac上尝试放开iphoneos，跑了下本地测试，因为pcl路依赖boost，需要先改boost。
![7LRTYQ7{2D}B$2T3 {@9BAN](https://github.com/xmake-io/xmake-repo/assets/105896625/8ff60063-71a3-4de2-a9ac-1ee4578e58fd)
![image](https://github.com/xmake-io/xmake-repo/assets/105896625/ea7866fe-4ca1-4c27-a33e-d48da1b24318)
出现下图错误
![2`5LTQUF)GR(LE@$}EAT31O](https://github.com/xmake-io/xmake-repo/assets/105896625/3cae1684-da2d-47f8-9096-f1ad0e79acd3)
能帮忙看下那出问题了吗

**Comment by waruqi** [comment]
ios 跟 brew::boost 有啥关系。。brew 只支持 pc 版本，又不支持 ios 的库安装。。遇到什么错 就自己针对性分析下，然后修下，或者打 patch

**Comment by 11janson** [comment]
> ios 跟 brew::boost 有啥关系。。brew 只支持 pc 版本，又不支持 ios 的库安装。。遇到什么错 就自己针对性分析下，然后修下，或者打 patch

对于我这样的xmake的新手来说，这要求有点高了，看不懂是什么错误主要是

**Comment by 11janson** [comment]
xmake的最终目的不是让用户避开这些麻烦的第三方库的编译连接，专心到代码编写上的吗？为何还要要求一个小白用户去分析解决一些未知原因的问题呢？我只是想在iOS系统上使用pcl库，现在已经花了一周时间去研究如何修改包描述，希望作者能够理解

**Comment by waruqi** [comment]
> xmake的最终目的不是让用户避开这些麻烦的第三方库的编译连接，专心到代码编写上的吗？为何还要要求一个小白用户去分析解决一些未知原因的问题呢？我只是想在iOS系统上使用pcl库，现在已经花了一周时间去研究如何修改包描述，希望作者能够理解

也希望你能理解，我一个人精力有限，每天光 xmake 的 issues 的处理就忙不过来，一天几十个 issues 动态更新，每个 issues 快的几小时，慢的几天甚至要花个把月才能解决。。这还不算日常新特性开发，文档维护，白天还得工作，晚上还得加班。

每天的时间少之又少，xmake-repo 仓库的所有包目前都是用户自己按需维护，没有的包 或者不支持的平台，都是自己提 pr 更新，也有一些志愿维护者 会帮忙更新维护。

包的维护原本就是很耗费时间的，有时候一个 error 就要花好几天时间去解决。我目前只能尽可能保证 xmake issues 的正常处理，不可能还有其他时间去为了一个包折腾几天，一周在这上面。

如果你搞不定，也可以耐心等待其他维护者或者用户解决。

**Comment by waruqi** [comment]
> > ios 跟 brew::boost 有啥关系。。brew 只支持 pc 版本，又不支持 ios 的库安装。。遇到什么错 就自己针对性分析下，然后修下，或者打 patch
> 
> 对于我这样的xmake的新手来说，这要求有点高了，看不懂是什么错误主要是

你也没给全错误和 logs ，我也看不出来什么
