### ISSUE TITLE
has_cfuncs 在mingw下测试时没有正确区分动态库和静态库

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake-repo#2943]
### Xmake 版本

2.8.5

### 操作系统版本和架构

windows 11

### 描述问题

如图，这里只改了三处地方，主要是加上mingw的支持
![image](https://github.com/xmake-io/xmake-repo/assets/97490782/429cf24c-af77-46ae-a887-8745d0c2980a)
然后在mingw环境中测试
如果指定是构建动态库，可以成功，测试也通过了
![image](https://github.com/xmake-io/xmake-repo/assets/97490782/841d4e4d-575b-4a9c-b459-bcaf004ea6c3)
如果构建静态库，库文件构建出来了，但是测试失败，会发现提示找不到 `__imp_gdImageDestroy`
![image](https://github.com/xmake-io/xmake-repo/assets/97490782/9328080c-47b5-4b96-b386-814a7fa277eb)
这个`__imp_`前缀是动态库才有的把，静态库里肯定没有，用nm查看构建出的静态库，可以看到是存在符号的
![image](https://github.com/xmake-io/xmake-repo/assets/97490782/254d87d2-8f5b-4821-8fa0-ced8f71ebaaf)

### 期待的结果

正确 has_cfuncs 在 mingw 静态库中测试的情况

### 工程配置

1

### 附加信息和错误日志

1

**Comment by waruqi** [comment]
库自身根据宏配置了导入导出切换，对用户 和 on_test 生效，得配置 package:add("defines", ..)

根据库自身代码情况，自己处理下，参考：

https://github.com/xmake-io/xmake-repo/blob/066f3ffa96ec1a93cc343561caca1ce26067a7e0/packages/f/flann/xmake.lua#L18
