### ISSUE TITLE
Fail to install assimp 5.2.4 at (vs_runtime="MTd" and debug=true)

### ISSUE THREAD

**Issue by Kethers** [xmake-io/xmake-repo#2993]
### Xmake Version

v2.8.5+dev.1ccbc20e7

### Operating System Version and Architecture

Windows11 22H2 22621.2861

### Describe Bug

Using VS2022 as toolchain and below statement in xmake
add_requires("assimp >= 5.2.4", {configs = {debug = true, vs_runtime = "MTd"}} )

Fail to install it, the detailed output log shows there's something wrong with the "/EHsc" flags and all these warnings are considered as errors.

Just [change version limit](https://github.com/xmake-io/xrepo/issues/37) is not working, test by command in local:

```Shell
cd xmake-repo
xmake l ./scripts/test.lua --shallow --vs_runtime=MTd -m debug "assimp 5.2.4"
```

Code changes in Line 102
old:`if not package:gitref() and package:version():lt("v5.2.4") then`
new:`if not package:gitref() and package:version():lt("v5.2.5") then`

### Expected Behavior

Should install successfully.

### Project Configuration

add_requires("assimp >= 5.2.4", {configs = {debug = true, vs_runtime = "MTd"}} )

### Additional Information and Error Logs

[install.txt](https://github.com/xmake-io/xmake-repo/files/13768582/install.txt)

**Comment by waruqi** [comment]
fixed

https://github.com/xmake-io/xmake-repo/pull/2994
