### ISSUE TITLE
open3d windows 平台安装失败

### ISSUE THREAD

**Issue by oahzuw** [xmake-io/xmake-repo#3050]
### Xmake 版本

2.8.6

### 操作系统版本和架构

Windows 10 10.0.19044

### 描述问题

C:\Users\xuexi>xrepo install open3d
checking for Microsoft Visual Studio (x64) version ... 2022
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> open3d v0.17.0 [vs_runtime:"MT"]
please input: y (y/n/m)
y
  => install open3d v0.17.0 .. failed

生成启动时间为 2024/1/6 18:55:50。
     1>项目“C:\Users\xuexi\AppData\Local\Temp\.xmake\240106\_4AEC802A9D0648308CD0D08B0B76F960.dir\Open3D.sln”在节点 1 上(Rebuild 个目标)。
     1>ValidateSolutionConfiguration:
         正在生成解决方案配置“Release|x64”。
       ValidateProjects:
         在解决方案配置“Release|x64”中未选定生成项目“INSTALL”。
         在解决方案配置“Release|x64”中未选定生成项目“PACKAGE”。
         在解决方案配置“Release|x64”中未选定生成项目“apply-cpp-style”。
         在解决方案配置“Release|x64”中未选定生成项目“apply-style”。
         在解决方案配置“Release|x64”中未选定生成项目“check-cpp-style”。
         在解决方案配置“Release|x64”中未选定生成项目“check-style”。
         在解决方案配置“Release|x64”中未选定生成项目“uninstall”。
     1>项目“C:\Users\xuexi\AppData\Local\Temp\.xmake\240106\_4AEC802A9D0648308CD0D08B0B76F960.dir\Open3D.sln”(1)正在节点 2 上生成“C:\Users\xuexi\AppData\Local\Temp\.xmake\240106\_4AEC802A9D0648308CD0D08B0B76F960.dir\ZERO_CHECK.vcxproj”(62) (Rebuild 个目标)。
    62>CoreClean:
         正在创建目录“x64\Release\ZERO_CHECK\”。
    62>D:\Devs\VS\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: 中间目录或输出目录无法驻留在临时目录下，因为这可能会导致增量生成出现问题。 [C:\Users\xuexi\AppData\Local\Temp\.xmake\240106\_4AEC802A9D0648308CD0D08B0B76F960.dir\ZERO_CHECK.vcxproj]
         已启用结构化输出。编译器诊断的格式设置将反映错误层次结构。有关详细信息，请参阅 https://aka.ms/cpp/structured-output。
if you want to get more verbose errors, please see:
  -> C:\Users\xuexi\AppData\Local\.xmake\cache\packages\2401\o\open3d\v0.17.0\installdir.failed\logs\install.txt
error: install failed!
error: execv(xmake require -j 10 --extra={system=false} open3d) failed(-1)

### 期待的结果

安装成功

### 工程配置

xrepo install open3d

### 附加信息和错误日志

[install.zip](https://github.com/xmake-io/xmake-repo/files/13849469/install.zip)

**Comment by ChrisCatCP** [comment]
你这个报错，是下载依赖项失败了啊。。。你保证网络稳定再看看吧

**Comment by oahzuw** [comment]
> 你这个报错，是下载依赖项失败了啊。。。你保证网络稳定再看看吧

感谢，那个报错文件一看一大堆没仔细看，挂上代理编译可以了
