### ISSUE TITLE
toml++ install failed

### ISSUE THREAD

**Issue by KkemChen** [xmake-io/xmake-repo#3053]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Ubuntu18.04

### 描述问题

安装toml++时，指定源码编译add_requires("toml++",{configs = {header_only = false},system = false})，报如下错误
![BZL5} _7A09PH95E5)B9(AH](https://github.com/xmake-io/xmake-repo/assets/44298896/c5609406-16c0-43ae-b64f-c35a3f0102e1)

### 期待的结果

修复该问题

### 工程配置

add_requires("toml++",{configs = {header_only = false},system = false})

### 附加信息和错误日志

note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> toml++ v3.4.0 [header_only:n]
please input: y (y/n/m)
y
checking for ping ... /bin/ping
pinging the host(github.com) ... 102 ms
/bin/tar -xf v3.4.0.tar.gz -C source.tmp
checking for meson ... /usr/bin/meson
/usr/bin/meson setup -Dbuild_lib=true -Ddefault_library=static --prefix=/root/.xmake/packages/t/toml++/v3.4.0/38b0e843347f488aa9e71202d5a38a83 --libdir=lib -Dbuildtype=release -Db_staticpic=true build_38b0e843
The Meson build system
Version: 0.45.1
Source dir: /root/.xmake/cache/packages/2401/t/toml++/v3.4.0/source
Build dir: /root/.xmake/cache/packages/2401/t/toml++/v3.4.0/source/build_38b0e843
Build type: native build

meson_options.txt:13:0: ERROR: Invalid kwargs for option "compile_library": "deprecated"

A full log can be found at /root/.xmake/cache/packages/2401/t/toml++/v3.4.0/source/build_38b0e843/meson-logs/meson-log.txt
error: @programdir/core/sandbox/modules/os.lua:378: execv(/usr/bin/meson setup -Dbuild_lib=true -Ddefault_library=static --prefix=/root/.xmake/packages/t/toml++/v3.4.0/38b0e843347f488aa9e71202d5a38a83 --libdir=lib -Dbuildtype=release -Db_staticpic=true build_38b0e843) failed(1)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:923]:
    [@programdir/core/sandbox/modules/os.lua:378]:
    [@programdir/core/sandbox/modules/os.lua:291]: in function 'vrunv'
    [@programdir/modules/package/tools/meson.lua:448]: in function 'generate'
    [@programdir/modules/package/tools/meson.lua:478]: in function 'install'
    [...make/repositories/xmake-repo/packages/t/toml++/xmake.lua:34]: in function 'script'
    [...dir/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call'
    [.../modules/private/action/require/impl/actions/install.lua:366]:

  => install toml++ v3.4.0 .. failed
error: @programdir/core/main.lua:309: @programdir/core/sandbox/modules/import/core/base/task.lua:65: @programdir/modules/async/runjobs.lua:320: .../modules/private/action/require/impl/actions/install.lua:471: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:923]:
    [.../modules/private/action/require/impl/actions/install.lua:471]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:330]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/async/runjobs.lua:237]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:923: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:309: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>

**Comment by waruqi** [comment]
你可以提个 pr 过来改进下这个包

**Comment by star-hengxing** [comment]
看了一下，应该是本地 meson 版本太低的问题（meson.build 有指定最小版本但没报错）

解决办法：更新本地 meson 或者手动 port 一份

**Comment by waruqi** [comment]
xmake-repo 里面的 meson 都 1.3.0 了，你这才  0.45.1。。是太老了。。

要么干脆删了本地 meson，让 xmake 走自动安装新版本 meson，要么手动更新下 meson

**Comment by KkemChen** [comment]
> xmake-repo 里面的 meson 都 1.3.0 了，你这才 0.45.1。。是太老了。。
> 
> 要么干脆删了本地 meson，让 xmake 走自动安装新版本 meson，要么手动更新下 meson

![2N159@R7@D{J1`CQ)BFP@{9](https://github.com/xmake-io/xmake-repo/assets/44298896/a8c94cac-0b94-4973-af46-27c51acc119c)

主要还是我这走 xmake自动安装新版本meson的时候，py3.11 装不上，所以才直接apt装了一个😅

**Comment by KkemChen** [comment]
像这个py安装错误，该怎么修复啊，google了好一会也没找到解决方法😥

**Comment by waruqi** [comment]
估计是安装 py 时候，里面 对 ssl 的检测没通过，ssl 被禁用了，得看下为啥 openssl 没检测到

**Comment by KkemChen** [comment]
> 估计是安装 py 时候，里面 对 ssl 的检测没通过，ssl 被禁用了，得看下为啥 openssl 没检测到

会不会也是因为我系统自带的openssl版本太低导致的

**Comment by waruqi** [comment]
那你可以更新下试试

**Comment by KkemChen** [comment]
> 那你可以更新下试试

![image](https://github.com/xmake-io/xmake-repo/assets/44298896/bd464825-fb00-4302-9f8d-613f4751864e)

刚更新成1.1.1w，安装py还是一样的报错

**Comment by KkemChen** [comment]
![image](https://github.com/xmake-io/xmake-repo/assets/44298896/496cc276-1b6d-468f-b3f0-028ed7f7286b)

我手动源码安装py是成功了，但是xmake为什么还是没检测到

**Comment by KkemChen** [comment]
难道说，这玩意必须得3.11.3😥

**Comment by waruqi** [comment]
你是怎么确认没检测到，贴下 logs

**Comment by KkemChen** [comment]
> 你是怎么确认没检测到，贴下 logs

就我重新执行xmake -v去build，他还是会去下载安装py3.11.3

**Comment by KkemChen** [comment]
![image](https://github.com/xmake-io/xmake-repo/assets/44298896/445fce1f-e8ad-4a5c-af48-a138f69083ae)

**Comment by waruqi** [comment]
<img width="445" alt="image" src="https://github.com/xmake-io/xmake-repo/assets/151335/6828c49b-fe39-4306-97bd-9def95dfefb4">

你的 py 没装完整，一些基础模块都没有

**Comment by KkemChen** [comment]
![image](https://github.com/xmake-io/xmake-repo/assets/44298896/6d229bec-1a3b-450a-942d-b5bd0bd24232)

**Comment by KkemChen** [comment]
> <img alt="image" width="445" src="https://private-user-images.githubusercontent.com/151335/295153545-6828c49b-fe39-4306-97bd-9def95dfefb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTE1MTUsIm5iZiI6MTcwNDc5MTIxNSwicGF0aCI6Ii8xNTEzMzUvMjk1MTUzNTQ1LTY4MjhjNDliLWZlMzktNDMwNi05N2JkLTlkZWY5NWRmZWZiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwOTA2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDVhMzIxOGQwM2E2ZDNlMzc5OTYwNTY5MjNkOGYzYWEwMDUwMmZjMjk4YmI1NjQ0MDFmOTcyNWZkMjE0NzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.66QfPsKmlUNK4pfgTCwDXAo_TgTd7kJPzRd7Srv_5Og">
> 你的 py 没装完整，一些基础模块都没有

你看我下面这张截图，我pip把这个模块装进去了，xmake也不报缺模块了

**Comment by waruqi** [comment]
python --version 看下版本号

**Comment by KkemChen** [comment]
> python --version 看下版本号

上面截图里，有用python --version 执行的结果

**Comment by KkemChen** [comment]
![image](https://github.com/xmake-io/xmake-repo/assets/44298896/f56010ce-e646-44d6-8c57-6ca223af38cd)

**Comment by waruqi** [comment]
你执行的是  `python3 --version` 。。我要看 `python --version`

xmake 检测的是 python 的版本是满足 3.x 而不是 python3

**Comment by KkemChen** [comment]
> 你执行的是 `python3 --version` 。。我要看 `python --version`
> 
> xmake 检测的是 python 的版本是满足 3.x 而不是 python3

那雀氏是不满足，python --version 是2.7.17 
![image](https://github.com/xmake-io/xmake-repo/assets/44298896/cdfe455b-885d-407b-b6f8-9266f0a7a7d9)

**Comment by waruqi** [comment]
你这个得改成 python 3。因为 meson 的 python 依赖，显示指定了版本 `python 3.x`，否则肯定会下载安装一份。

**Comment by KkemChen** [comment]
> 你这个得改成 python 3。因为 meson 的 python 依赖，显示指定了版本 `python 3.x`，否则肯定会下载安装一份。

ok，了解了
