### ISSUE TITLE
libass包的配置有问题

### ISSUE THREAD

**Issue by BusyStudent** [xmake-io/xmake-repo#3055]
### Xmake 版本

v2.8.5+HEAD.debbd3ac3

### 操作系统版本和架构

Windows 11 22H2

### 描述问题

你好 我在使用libass这个包的时候发现没有系统字体供应器 感觉这个编译选项没有开
然后我看libass/port/xmake.lua的时候看到了这个选项
```lua
option("system-font-provider")
    on_check(function (option)
        option:enable(not is_plat("wasm"))
    end)
    set_description("enable checking for system fonts provider")
```
看样子只要不在wasm上就是开的 但是就没有开的样子
而且我也手动打开不了开关
```lua
add_requires("libass", {configs = {system-font-provider = true} })
```
这样不行 应该是'-'的问题

### 期待的结果

我希望这个选项应该是开的 或者我能手动打开这个选项
正确的话 在Windows上应该有ASS_FONTPROVIDER_DIRECTWRITE这个提供器

### 工程配置

[test.zip](https://github.com/xmake-io/xmake-repo/files/13854248/test.zip)

### 附加信息和错误日志

暂无

**Comment by waruqi** [comment]
提个 pr 过来，改进下包，加上 config 就行了

**Comment by BusyStudent** [comment]
找到原因了 在 port/config.h.in里面 前面有一堆无意义的 ```#unref``` 他会导致 构建时候设置的CONFIG_DIRECTWRITE等其他宏被undef
```cpp
/* found CoreText framework */
#undef CONFIG_CORETEXT

/* found DirectWrite and GDI (Win32) */
#undef CONFIG_DIRECTWRITE

/* found libpng via pkg-config */
#undef CONFIG_LIBPNG
#define CONFIG_SOURCEVERSION "commit: ${GIT_TAG}${GIT_COMMIT_LONG}"
${define HAVE_STRDUP}
${define HAVE_STRNDUP}
```

**Comment by BusyStudent** [comment]
#3056 我提了个pr 这样子改在我电脑上行的通, 话说这个库用的构建工具用的是autotools 有办法方便的集成进去么 我看目前仓库里面这个包的构建是手写的xmake

**Comment by waruqi** [comment]
> #3056 我提了个pr 这样子改在我电脑上行的通, 话说这个库用的构建工具用的是autotools 有办法方便的集成进去么 我看目前仓库里面这个包的构建是手写的xmake

原本大部分库就是 autotools 直接用的，只有 autotools 构建遇到了很多问题，才会 port 到 xmake.lua 。。既然这个包目前走的 xmake.lua ，说明当初 autotools 就遇到了很多的问题搞不定。

**Comment by BusyStudent** [comment]
那 应该没问题了
