### ISSUE TITLE
openssl 1.1.1-w 在安装的时候会安装文档

### ISSUE THREAD

**Issue by da-liii** [xmake-io/xmake-repo#3063]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Windows 11

### 描述问题

openssl在安装时会安装文档，很多小文件，会比较慢

### 期待的结果

不安装文档

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
我记得之前已经用了 install_sw 去安装，禁用文档了，你可以再来个 pr 过来改进下
