### ISSUE TITLE
sockpp 安装出错

### ISSUE THREAD

**Issue by StarBeat** [xmake-io/xmake-repo#3162]
### Xmake 版本

 v2.8.2+20230909

### 操作系统版本和架构

win 10 wsl1 4.4.0-19041-Microsoft

### 描述问题

 xrepo install  sockpp  安装 sockpp v0.8.1 出现  unmatched checksum! 错误，无法正常下载包

### 期待的结果

 xrepo install  sockpp 在 linux 下正常安装

### 工程配置

No Need

### 附加信息和错误日志

xmake f -c --require=n -vD
checking for platform ... linux
checking for architecture ... x86_64
checking for gcc ... /usr/bin/gcc
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
configure
{
    proxy_pac = pac.lua
    arch = x86_64
    theme = default
    network = public
    plat = linux
    proxy_hosts = github.com,gitlab.*,*.xmake.io
    proxy = http://127.0.0.1:1080
    clean = true
    buildir = build
    ccache = true
    mode = release
    host = linux
    ndk_stdcxx = true
    kind = static
}
xmake require -v -D -j 26 --extra={system=false} sockpp
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /bin/gzip
checking for tar ... /bin/tar
/usr/bin/git rev-parse HEAD
checking for cmake ... no
checking for cmake ... /usr/bin/cmake
finding sockpp from xmake ..
checking for xmake::sockpp ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in myrepo:
  -> sockpp v0.8.1
please input: y (y/n/m)
y
checking for ping ... /bin/ping
pinging the host(github.com) ... 65535 ms
/bin/tar -xf v0.8.1.tar.gz -C source.tmp
patching /mnt/x/wsl/X/xmake-repo/packages/s/sockpp/patches/0.8.1/strerror.patch to sockpp-v0.8.1 ..
error: ...es/private/action/require/impl/actions/patch_sources.lua:96: patch(/mnt/x/wsl/X/xmake-repo/packages/s/sockpp/patches/0.8.1/strerror.patch): unmatched checksum!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:921]:
    [...es/private/action/require/impl/actions/patch_sources.lua:96]: in function '_patch'
    [...es/private/action/require/impl/actions/patch_sources.lua:120]:
    [.../modules/private/action/require/impl/actions/install.lua:352]:

  => install sockpp v0.8.1 .. failed
error: @programdir/modules/private/async/runjobs.lua:256: .../modules/private/action/require/impl/actions/install.lua:469: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:921]:
    [.../modules/private/action/require/impl/actions/install.lua:469]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:328]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:921: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/modules/private/async/runjobs.lua:256: in field 'catch'
        @programdir/core/sandbox/modules/try.lua:123: in global 'try'
        @programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
error: @programdir/core/main.lua:300: @programdir/core/sandbox/modules/os.lua:378: execv(xmake require -v -D -j 26 --extra={system=false} sockpp) failed(255)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:921]:
    [@programdir/core/sandbox/modules/os.lua:378]:
    [@programdir/modules/private/xrepo/action/install.lua:300]: in function '_install_packages'
    [@programdir/modules/private/xrepo/action/install.lua:307]:
    [@programdir/modules/private/xrepo/main.lua:196]:
    [@programdir/plugins/lua/main.lua:123]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/main.lua:298]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:921: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:300: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>

**Comment by SirLynix** [comment]
See https://github.com/xmake-io/xmake/pull/4649

**Comment by StarBeat** [comment]
该方法有效，v0.8.1 安装成功

> See [xmake-io/xmake#4649](https://github.com/xmake-io/xmake/pull/4649)
> 
> Could you try this patch? `xmake update -s github:SirLynix/xmake#improve-gitrepo`
