### ISSUE TITLE
target(aaa)里add_deps(bbb)的目标还没构建完成，aaa的构建就开始了，但是aaa依赖bbb产生的头文件，导致aaa编译失败

### ISSUE THREAD

**Issue by SmartSmallBoy** [xmake-io/xmake-repo#3235]
### Xmake 版本

2.8.6

### 操作系统版本和架构

ubuntu22.04

### 描述问题

target(aaa)里add_deps(bbb)的目标还没构建完成，aaa的构建就开始了，但是aaa依赖bbb产生的头文件，导致aaa编译失败
 > xmake -v -y
headerdir:1111111111  build/.gens/bpf_skel/cross/arm64/release/rules/bpf
pre build
hello build
test before_build
[ 70%]: cache compiling.release src/kprobe.c
/home/vimoon/src/third/forlinx/tools/gcc/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc -c -fvisibility=hidden -O3 -Isrc -Ibuild/.gens/bpf_skel/cross/arm64/release/rules/bpf -Ithird/libbpf/include/uapi -Ibuild -DNDEBUG -o build/.objs/hello/cross/arm64/release/src/kprobe.c.o src/kprobe.c
error: src/kprobe.c:7:10: fatal error: kprobe.skel.h: No such file or directory
    7 | #include <kprobe.skel.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

hello里的build依赖pre的头文件
但是pre还没build完成，hello就开始了
![image](https://github.com/xmake-io/xmake-repo/assets/82008372/509704fd-09cc-448c-b6d6-72b1763fe8b4)

### 期待的结果

怎么处理一下

### 工程配置

![image](https://github.com/xmake-io/xmake-repo/assets/82008372/2043b7a6-8acd-4d68-984e-43779a5eddb3)

### 附加信息和错误日志

 > xmake -v -y
headerdir:1111111111  build/.gens/bpf_skel/cross/arm64/release/rules/bpf
pre build
hello build
test before_build
[ 70%]: cache compiling.release src/kprobe.c
/home/vimoon/src/third/forlinx/tools/gcc/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc -c -fvisibility=hidden -O3 -Isrc -Ibuild/.gens/bpf_skel/cross/arm64/release/rules/bpf -Ithird/libbpf/include/uapi -Ibuild -DNDEBUG -o build/.objs/hello/cross/arm64/release/src/kprobe.c.o src/kprobe.c
error: src/kprobe.c:7:10: fatal error: kprobe.skel.h: No such file or directory
    7 | #include <kprobe.skel.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by SmartSmallBoy** [comment]
![image](https://github.com/xmake-io/xmake-repo/assets/82008372/d761a34a-e86a-4c81-a32a-fbc246e8f6e9)

**Comment by waruqi** [comment]
codegen 参考 https://github.com/xmake-io/xmake/blob/79f6d8712b1b85e2ae089b92295a7aadc8cae4b6/tests/projects/other/autogen_codedep/xmake.lua#L34

得关了跨 target 并行编译。。
