### ISSUE TITLE
xrepo NASM download does not exist

### ISSUE THREAD

**Issue by PerikiyoXD** [xmake-io/xmake-repo#3295]
### Xmake Version

2.8.6+master.c601bfa82

### Operating System Version and Architecture

Windows 10 LTSC 21H2 v19044.2965

### Describe Bug

NASM Download is non-existant.

### Expected Behavior

Download NASM dependency succesfully.

### Project Configuration

Using these dependencies:
```
add_requires("tinyxml2 10.0.0")
add_requires("fmt 10.2.1")
add_requires("crow 2023.07.22")
```

### Additional Information and Error Logs

```
in xmake-repo:
  -> asio 1.29.0 [from:crow]
  -> zlib v1.3.1 [runtimes:"MT", from:crow]    
  -> nasm 2.16.01 [from:openssl]
  -> strawberry-perl 5.32.0+1 [from:openssl]   
  -> openssl 1.1.1-w [runtimes:"MT", from:crow]
  -> crow 2023.07.22 
please input: y (y/n/m)
y
  => download https://github.com/xmake-mirror/nasm/releases/download/nasm-2.16.01/nasm-2.16.01-win64.zip 
.. failed
```

**Comment by waruqi** [comment]
I have fixed it.

**Comment by PerikiyoXD** [comment]
@waruqi,  Could you please indicate the related PR?
