### ISSUE TITLE
FFmpeg: libxz, libx264, libx265, iconv requested but not found

### ISSUE THREAD

**Issue by SnowinterCat** [xmake-io/xmake-repo#3442]
### Xmake Version

2.8.8

### Operating System Version and Architecture

windows10 22h2, using msvc2019, build on x86, runtimes MD, STATIC

### Describe Bug

add_require("ffmpeg", {configs = {zlib = true, libx264 = true, libx265 = true, iconv = true}})
Get these errors:
ERROR: libx264 not found
ERROR: x265 not found using pkg-config
ERROR: iconv requested but not found
And then try:
add_require("ffmpeg", {configs = {zlib = true, lzma = true}})
it is also error

### Expected Behavior

Can use ffmpeg by {configs = {zlib = true, libx264 = true, libx265 = true, iconv = true}}

### Project Configuration

add_requires("ffmpeg", {configs = {zlib = true, libx264 = true, libx265 = true, iconv = true}})

### Additional Information and Error Logs

```
PS D:\work\Code\Demo> xmake f --plat=windows --arch=x86 --mode=releasedbg --runtimes='MD' --buildversion=10 -v
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.exe
checking for Microsoft Visual Studio (x86) version ... 2019
checking for zig ... no
checking for zig ... no
checking for unzip ... no
checking for 7z ... C:\Program Files\xmake\winenv\bin\7z
checking for git ... ok
checking for gzip ... no
git rev-parse HEAD
"versions.txt"
checking for cmake ... no
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2019
checking for cmake ... no
checking for cmake ... no
checking for cmake ... C:\Program Files\CMake\bin\cmake
checking for xmake::actor-framework ... actor-framework 0.19.2
checking for xmake::boost ... boost 1.84.0
checking for nasm ... no
checking for xmake::zlib ... zlib v1.3.1
checking for xmake::libiconv ... libiconv 1.17
checking for msys2-base ... no
checking for msys2 ... no
checking for xmake::x264 ... x264 v2023.04.04
checking for xmake::x265 ... x265 3.4
checking for xmake::ffmpeg ... no
checking for ffmpeg ... no
checking for xmake::fmt ... fmt 10.2.1
checking for xmake::libcurl ... libcurl 8.6.0
checking for xmake::nlohmann_json ... nlohmann_json v3.11.3
checking for xmake::rapidjson ... rapidjson 2023.12.6
checking for xmake::pahomqttc ... pahomqttc v1.3.13
checking for xmake::pahomqttcpp ... pahomqttcpp v1.3.2
checking for xmake::protobuf-cpp ... protobuf-cpp 3.19.4
checking for xmake::openssl ... openssl 1.1.1-w
checking for xmake::sqlite3 ... sqlite3 3.45.0+100
checking for xmake::expat ... expat 2.5.0
checking for xmake::pcre2 ... pcre2 10.42
checking for xmake::poco ... poco 1.12.5
checking for aqt ... no
checking for Qt SDK directory ... C:/Users/admin/AppData/Local/.xmake/packages/q/qt5base/5.15.2/8207bac5b16e4edfbb0e20df477003b2
checking for Qt SDK version ... 5.15.2
checking for xmake-repo::qt5base ... qt5base 5.15.2
checking for xmake-repo::qt5core ... qt5core 5.15.2
checking for xmake-repo::qt5gui ... qt5gui 5.15.2
checking for xmake-repo::qt5widgets ... qt5widgets 5.15.2
checking for xmake::spdlog ... spdlog v1.13.0
checking for xmake::yaml-cpp ... yaml-cpp 0.8.0
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> ffmpeg 6.1 [zlib:y, runtimes:"MD", iconv:y, libx264:y, libx265:y]
please input: y (y/n/m)
y
checking for ping ... ok
pinging the host(github.com) ... 91 ms
pinging the host(ffmpeg.org) ... 186 ms
pinging the host(git.ffmpeg.org) ... 186 ms
checking for curl ... C:\Program Files\xmake\winenv\bin\curl
C:\Program Files\xmake\winenv\bin\curl -SL -x http://127.0.0.1:7890 -A "Xmake/2.8.8+HEAD.d8e248255 (Windows;) curl/8.2.1" https://github.com/FFmpeg/FFmpeg/archive/n6.1.zip -o n6.1.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 18.8M    0 18.8M    0     0  4665k      0 --:--:--  0:00:04 --:--:-- 6959k
C:\Program Files\xmake\winenv\bin\7z x -y n6.1.zip -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 19791345 bytes (19 MiB)

Extracting archive: n6.1.zip
--
Path = n6.1.zip
Type = zip
Physical Size = 19791345
Comment = d4ff0020b40b524a490cf62eccbd3a318f4c0e58

Everything is Ok

Folders: 98
Files: 8190
Size:       78475137
Compressed: 19791345
  => download https://github.com/FFmpeg/FFmpeg/archive/n6.1.zip .. ok
./configure --enable-version3 --disable-doc --disable-bzlib --enable-ffmpeg --disable-ffplay --disable-ffprobe --enable-gpl --enable-hardcoded-tables --enable-iconv --enable-libx264 --enable-libx265 --disable-lzma --disable-vaapi --disable-vdpau --enable-zlib --enable-static --disable-shared --disable-debug --target-os=win32 --enable-w32threads --enable-d3d11va --enable-dxva2 --enable-mediafoundation --toolchain=msvc --prefix=C:\Users\admin\AppData\Local\.xmake\packages\f\ffmpeg\6.1\ad8f1fea60414921a0459e380a66eff8
ERROR: x264 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
error: execv(./configure --enable-version3 --disable-doc --disable-bzlib --enable-ffmpeg --disable-ffplay --disable-ffprobe --enable-gpl --enable-hardcoded-tables --enable-iconv --enable-libx264 --enable-libx265 --disable-lzma --disable-vaapi --disable-vdpau --enable-zlib --enable-static --disable-shared --disable-debug --target-os=win32 --enable-w32threads --enable-d3d11va --enable-dxva2 --enable-mediafoundation --toolchain=msvc --prefix=C:\Users\admin\AppData\Local\.xmake\packages\f\ffmpeg\6.1\ad8f1fea60414921a0459e380a66eff8) failed(1)
  => install ffmpeg 6.1 .. failed
error: install failed!
warning: please use package:runtimes() or package:has_runtime() instead of package:config("vs_runtime")
warning: please use add_configs("runtimes") instead of add_configs("vs_runtime").
warning: configs.runtimes is readonly in package(qt5base), it's always MD
warning: configs.runtimes is readonly in package(aqt), it's always MD
```

**Comment by SnowinterCat** [comment]
可能是这里的问题，ffmpeg需要的是libx264，libx265，iconv。但是仓库里面的名字是x264，x265和libiconv。能够通过alis 修改包名字吗？
https://github.com/xmake-io/xmake-repo/blob/ce0452a6f795a331e893e46447cb7de58c9662ec/packages/f/ffmpeg/xmake.lua#L82

**Comment by waruqi** [comment]
跟包名又没啥关系

**Comment by SnowinterCat** [comment]
但是x264，x265，libiconv应该是装上了。
难道是ffmpeg用pkg-config去找了？

**Comment by waruqi** [comment]
嗯 你可以自己调下

**Comment by SnowinterCat** [comment]
是不是ffmpeg的configure里面用了这个，指定用pkg-config去找包了？
我该怎么做呢？
![image](https://github.com/xmake-io/xmake-repo/assets/67003051/8e8f4540-48ec-4b6e-b6d8-49bc6e13c430)

**Comment by waruqi** [comment]
具体包具体分析，这个只能你自己分析 configure 去研究了，分析下 它为什么没找到。

**Comment by SnowinterCat** [comment]
我看它的整个configure全在用pkg_config来找包，我可不可以把xmake仓库里面的pkgconfig加到ffmpeg的依赖里面，然后把x264和x265和iconv交给pkgconfig，再让ffmpeg用pkg_config找？

**Comment by SnowinterCat** [comment]
https://github.com/xmake-io/xmake-repo/blob/ce0452a6f795a331e893e46447cb7de58c9662ec/packages/f/ffmpeg/xmake.lua#L184-L202

我大概了解了ffmpeg的编译流程，应该是在msys2的虚拟linux环境，把编译器和链接器改成mvsc之后，使用pkg-config配置之后，再用make编译。
这个pkg-config是运行在虚拟linux环境里面的，我把libx264的pkg-config的配置文件复制进去就能找到libx264了。
我进行了这样的修改来测试：
···
            table.insert(configs, "--prefix=" .. package:installdir())
            -- envs["PKG_CONFIG_PATH"] = "D:/.xmake/packages/x/x264/v2023.04.04/d6c587de58ca4c5b8f5fa8b0cfd93f1f/lib/pkgconfig"
            os.vexecv("cp", {"D:/.xmake/packages/x/x264/v2023.04.04/d6c587de58ca4c5b8f5fa8b0cfd93f1f/lib/pkgconfig/x264.pc", "/usr/lib/pkgconfig/"}, {shell = true, envs = envs})
            os.vexecv("cp", {"D:/.xmake/packages/x/x265/3.4/446ef5ca844142bf838d958b3ff2920e/lib/pkgconfig/x265.pc", "/usr/lib/pkgconfig/"}, {shell = true, envs = envs})
            os.vexecv("cp", {"D:/.xmake/packages/l/libiconv/1.17/8c91afaa2b6848c8b08da614971a2012/lib/pkgconfig/iconv.pc", "/usr/lib/pkgconfig/"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--list-all"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--variable=libdir", "x264"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--variable=libdir", "x265"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--variable=libdir", "iconv"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--libs", "x264"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--libs", "x265"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--libs", "iconv"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--modversion", "x264"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--modversion", "x265"}, {shell = true, envs = envs})
            os.vexecv("pkg-config", {"--modversion", "iconv"}, {shell = true, envs = envs})
            print("********************************")
            os.vrunv("./configure", configs, {shell = true, envs = envs})
···
可是libx265和libiconv仍然有问题。
而且我的写法根本不通用。我该怎么样获取ffmpeg的deps中的某些包的lib路径呢？

**Comment by waruqi** [comment]
```lua
local buildenvs = import("package.tools.autoconf").buildenvs(package)
local envs = os.joinenvs(os.getenvs(), msvc:runenvs())
```

追加 buildenvs 就能自动提取 deps 的路径，设置 PKG_CONFIG_PATH 

不过现在的问题是，即使设置上也是不通过的。因为 msys2 里面的 pkg-config ，只支持 /c/xxx 路径，传入的 `c:\xx` 路径，它不支持，所以检测不到。。

另外，即使改成了 /c/xxx ，它返回的也是 `c:\foo\xxx` 路径中的 `\` 也没了，变成了 `c:fooxxx` 导致 includedir 无效，一样找不到。。

这个要搞起来，估计也要费不少功夫，估计还得调 msys2 环境配置，你可以继续分析下

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/3456

试下这个 patch，重装下 x264 ，至少 x264 检测能过

**Comment by waruqi** [comment]
更新下  xmake 到 dev，`xmake update -s dev`

然后等这个 patch https://github.com/xmake-io/xmake-repo/pull/3456

应该可以了

**Comment by SnowinterCat** [comment]
@waruqi 抱歉哈，我周末没看。我刚刚试了一下，貌似这行命令xmake update -s dev用了之后，make-repo没有更新，是不是还需要xrepo update-repo一下？

**Comment by SnowinterCat** [comment]
啊，没事了，我改了本地的xmake-repo的代码，用了xmake update -s dev之后git更新不了仓库

**Comment by SnowinterCat** [comment]
嗯，可以了，太感谢了
