### ISSUE TITLE
cmake lib64 error

### ISSUE THREAD

**Issue by inter1965** [xmake-io/xmake-repo#35]
`error: cannot copy file install/lib, error: not found this file`
Since on x64 platform cmake install library to lib64 on default.

the workaround is add "-DCMAKE_INSTALL_LIBDIR=lib" to the configs, however it would be better if xmake could handler this .

This happens in package "freeglut" on "linux x64", however it would affect other packages which use cmake.

**Comment by waruqi** [comment]
I tested it on ubuntu16.04/x86_64, cmake is not installed by default to the lib64 subdirectory.
Can you tell me what version of the test was it? Is cmake the version?...

```
checking for the xmake::freeglut ... 3.0.0
{ 
  links = { 
    "glut" 
  },
  linkdirs = { 
    "/home/ruki/.xmake/packages/f/freeglut/3.0.0/10ea5b624f77a230f547aea4ba5e5e7f/lib" 
  },
  version = "3.0.0",
  includedirs = { 
    "/home/ruki/.xmake/packages/f/freeglut/3.0.0/10ea5b624f77a230f547aea4ba5e5e7f/include" 
  } 
}
```

**Comment by inter1965** [comment]
Please check this:
`https://cmake.org/cmake/help/v3.14/module/GNUInstallDirs.html`

`LIBDIR`
`object code libraries (lib or lib64 or lib/<multiarch-tuple> on Debian)`

**Comment by waruqi** [comment]
Ok, I have improved xmake to set `-DCMAKE_INSTALL_LIBDIR=lib`. I can update dev and try it again.

xmake update dev
