### ISSUE TITLE
Update tesseract to 5.3.4

### ISSUE THREAD

**Issue by enzalito** [xmake-io/xmake-repo#3535]
### Is your feature request related to a problem? Please describe.

The latest version of tesseract available in the repo is quite old (more than 2 years old). Quite a lot of fixes and improvements have been added since then.

### Describe the solution you'd like

Update tesseract to the latest version (along with its dependencies).

### Describe alternatives you've considered

The 5.3.3 version is available on conan but I strongly prefer using xrepo as I've had quite a few issues with conan and vcpkg.

**Comment by waruqi** [comment]
you can open a pr to update it.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/3538
