### ISSUE TITLE
Need to add Angelscript compilation patch for MSVC ARM architecture

### ISSUE THREAD

**Issue by Seedking** [xmake-io/xmake-repo#3537]
### 你在什么场景下需要该功能？

[angelscript update pr](https://github.com/xmake-io/xmake-repo/pull/3524)

### 描述可能的解决方案

>Pocket PC with ARM CPU
The MSVC compiler doesn't support inline assembler for the ARM CPU, so a separate assembler file has been written with this code: as_callfunc_arm_msvc.asm.
>In order to compile this file properly it is necessary to configure a custom build command with the following:
>`armasm -g $(InputPath)`

**Comment by star-hengxing** [comment]
https://stackoverflow.com/questions/59742466/building-arm64-asm-in-visual-studio-with-cmake
