### ISSUE TITLE
xmake require grpc fail

### ISSUE THREAD

**Issue by MarcusMogg** [xmake-io/xmake-repo#3705]
### Xmake Version

v2.8.9

### Operating System Version and Architecture

ubuntu22.04

### Describe Bug

xmake require grpc fail

run
```shell
$ rm -rf ~/.xmake/
$ xmake require grpc
checking for platform ... linux
checking for architecture ... x86_64
updating repositories .. ok
error: package(abseil/latest:{"cxx_standard=17"}): conflict dependences with package(abseil/latest:{}) in grpc!
```

it seems caused by https://github.com/xmake-io/xmake-repo/pull/3667/files#diff-c75113795568cbea15dfb1ea883ddc9982f4013aefd2a13a7a32b508f39a356cR43

`protobuf-cpp` used `abseil/latest:{"cxx_standard=17"}`, but `re2` used  `abseil/latest:{}`

### Expected Behavior

build success

### Project Configuration

```
add_rules("mode.debug", "mode.release")

set_languages("cxx23")
add_requires("grpc")

```

### Additional Information and Error Logs

no more

**Comment by MarcusMogg** [comment]
it seems caused by  https://github.com/xmake-io/xmake-repo/pull/3667/files#diff-c75113795568cbea15dfb1ea883ddc9982f4013aefd2a13a7a32b508f39a356cR43

I will have a quick fix by set all of abseil use c++17

**Comment by MarcusMogg** [comment]
is there any solution that automatically merges options with the same dependencies?
or toplever configurations specified in the project files (projectdir/xmake.lua) to manually designate the dependency project's settings?

**Comment by waruqi** [comment]
@Chi-EEE @c8ef We should remove `{configs = {cxx_standard = "17"}}` in add_deps and use the default config.

and We can use `add_requireconfs("**.abseil", {override = true, configs = {cxx_standard = "17"}})` to modify it in user project.

**Comment by MarcusMogg** [comment]
> @Chi-EEE @c8ef We should remove `{configs = {cxx_standard = "17"}}` in add_deps and use the default config.
> 
> and We can use `add_requireconfs("**.abseil", {override = true, configs = {cxx_standard = "17"}})` to modify it in user project.

remove all config and use default config will be build fail ( ` multiple definition` ) in my pc, it seems caused by abseil default use c++14 but others default use c++17, maybe some gcc bug here

so i have to change abseil default cxx_standard to c++17 @Chi-EEE @waruqi
