### ISSUE TITLE
Broken links in the README

### ISSUE THREAD

**Issue by Glinrens-corner** [xmake-io/xmake-repo#372]
### Describe the bug
The links

in README.md
https://xmake.io/#/home   

in README_zh.md
https://xmake.io/#/zh/

lead to return a 404.

### Expected behavior
That all links refer to existing pages.

### Error output
Not applicable.

### Related Environment
not applicable

### Additional context
As there are in both cases working links close by to very similar pages, it is probably ok to just remove these links. 

I will shortly submit a patch. This issue is to explain the problem and if necessary discussion.

**Comment by waruqi** [comment]
I have fixed them.
