### ISSUE TITLE
A newcomers confusion about linked documentation.

### ISSUE THREAD

**Issue by Glinrens-corner** [xmake-io/xmake-repo#373]
### Describe the problem details

As a newcomer I was a bit confused that the first link in the documentation  brought me back to xmake where I was just coming from. Additionally there is later an identically named link "Documents" in the next section which was more what I was looking for.

I will in short time submit a patch. This issue is for tracking and discussion.

**Comment by waruqi** [comment]
open `https://xmake.io` and click `getting started` to enter documents.
