### ISSUE TITLE
Don't build/copy doc when installing openssl3 on windows

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake-repo#3740]
### Xmake Version

N/A

### Operating System Version and Architecture

N/A

### Describe Bug

N/A

### Expected Behavior

N/A

### Project Configuration

N/A

### Additional Information and Error Logs

N/A

**Comment by star-hengxing** [comment]
https://stackoverflow.com/questions/47136654/is-there-a-way-to-install-openssl-without-installing-man-pages

**Comment by waruqi** [comment]
除了 windows ，其他平台目前都已经是不安装 docs 的，windows 下还没搞。可以来个 pr 

https://github.com/xmake-io/xmake-repo/blob/efaf379de2b94981a33ffe947e30ea5310257b8d/packages/o/openssl3/xmake.lua#L106
