### ISSUE TITLE
[Boost] Can't execute programs using boost with certain setups

### ISSUE THREAD

**Issue by SFGrenade** [xmake-io/xmake-repo#3830]
### Xmake Version

https://github.com/xmake-io/xmake/releases/download/v2.8.9/xmake-dev.win64.exe

### Operating System Version and Architecture

Microsoft Windows Server 2022   10.0.20348   Datacenter

### Describe Bug

When building BoostNng ([here](https://github.com/SFGrenade/BoostNng) and [here](https://github.com/NetworkingHelpers/BoostNng-Cpp)), the test targets cause `error LNK2001: unresolved external symbol` when statically building.
When shared building that step works but then on execution anything with a boost function crashes.

### Expected Behavior

Things should build and run without errors.

### Project Configuration

https://github.com/NetworkingHelpers/BoostNng-Cpp

### Additional Information and Error Logs

[Logs for both debug variants](https://github.com/SFGrenade/BoostNng/actions/runs/8764986961/job/24055566083)
[Actual repo with log for static debug variant](https://github.com/NetworkingHelpers/BoostNng-Cpp/actions/runs/8765232821/job/24056028769)

**Comment by SFGrenade** [comment]
Example project: https://github.com/SFGrenade/MinXmakeBoostExample
Runs: https://github.com/SFGrenade/MinXmakeBoostExample/actions/runs/8786497833
Notes:
- Shared builds successfully, but crashes once any boost.serialization function is used
- Static has a bunch of `error LNK2019: unresolved external symbol` errors when building

**Comment by waruqi** [comment]
> "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -debug -pdb:build\windows\x64\debug\MinExample.pdb -out:build\windows\x64\debug\MinExample.exe build\.objs\MinExample\windows\x64\debug\src\main.cpp.obj
create ok!
compile_commands.json updated!
error: @programdir\core\main.lua:3[29](https://github.com/SFGrenade/MinXmakeBoostExample/actions/runs/8786497833/job/24109500933#step:14:30): @programdir\actions\build\main.lua:148: @programdir\modules\async\runjobs.lua:322: @programdir\actions\build\kinds\binary.lua:53: @programdir\modules\core\tools\link.lua:175:    Creating library build\windows\x64\debug\MinExample.lib and object build\windows\x64\debug\MinExample.exp
main.cpp.obj : error LNK2019: unresolved external symbol "public: __cdecl

missing boost links, maybe you need debug boost package when enabling serialization.

**Comment by waruqi** [comment]
maybe debug package issue

```console
xmake f -m debug -cvD --runtimes=MTd
```

it will install boost with debug/MTd, and set runtime link with `-sgd` suffix.

but the installed boost libs have not -sgd suffix, so xmake did not find them.

I don't know why, you need debug it's build configuration. https://github.com/xmake-io/xmake-repo/blob/8fd56611357ff8d95a2b09412e49bd15bf477418/packages/b/boost/xmake.lua#L257

**Comment by SFGrenade** [comment]
so after testing i can say that right now:
- [Linux just works](https://github.com/SFGrenade/MinXmakeBoostExample/actions/runs/8908392798)
- [MacOS seems to have general problems executing with shared/x86_64](https://github.com/SFGrenade/MinXmakeBoostExample/actions/runs/8908392797)
- [Windows (ARM excluded) has problems on execution with shared/MT](https://github.com/SFGrenade/MinXmakeBoostExample/actions/runs/8908392791)

**Comment by SFGrenade** [comment]
And with an actual library utilizing boost, tests conclude that:
- [Linux works just fine](https://github.com/SFGrenade/BoostNng-Cpp/actions/runs/8909092332)
- [MacOS still has the shared/x86_64 problem](https://github.com/SFGrenade/BoostNng-Cpp/actions/runs/8909092334)
- [Windows also still has the shared/MT problem (disregard static/x86/MD, that's NNG not wanting to do its job)](https://github.com/SFGrenade/BoostNng-Cpp/actions/runs/8909092327)

**Comment by SFGrenade** [comment]
gonna close it because similar to the protobuf issue
