### ISSUE TITLE
boost urls broken/outdated.

### ISSUE THREAD

**Issue by Glinrens-corner** [xmake-io/xmake-repo#386]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
trying to download boost 1.75.0 (the most recent version in this repository) fails.

### Expected behavior
The urls provided by the package point to current boost repositories. 

### Error output
xmake output: 
 > xmake config

note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> boost 1.75.0 
please input: y (y/n)
y
  => download https://github.com/xmake-mirror/boost/releases/download/boost-1.75.0/boost_1_75_0.tar.bz2 .. failed
  => download https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2 .. failed

we can also download these packages manually:
  - https://github.com/xmake-mirror/boost/releases/download/boost-1.75.0/boost_1_75_0.tar.bz2
  - https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2
to the local search directories: 
  - boost_1_75_0.tar.bz2
and we can run `xmake g --pkg_searchdirs=/xxx` to set the search directories.
error: download failed!

----------------------------------------------
https://github.com/xmake-mirror/boost/releases/download/boost-1.75.0/boost_1_75_0.tar.bz2
returns a 404 Page not found. 

https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2
returns a 403 Forbidden.

### Related Environment
I don't think this is necessary.

### Additional context
The root causes seem to be:
1. The xmake-mirror repository  does not contain the newest boost versions (1.72.0 is the latest). 

2. bintray is shutting down. Boost has moved to jfrog. See boostorg/boost#502 
the new link seems to be:
https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.bz2

**Comment by waruqi** [comment]
It has been fixed, https://github.com/xmake-io/xmake-repo/pull/387

and I will update boost mirror files.

**Comment by Glinrens-corner** [comment]
Thank you for the quick fix guys.
