### ISSUE TITLE
请求一个qt无边框库qwindowkit

### ISSUE THREAD

**Issue by Arteiimis** [xmake-io/xmake-repo#3889]
### 你在什么场景下需要该功能？

一个为数不多还在维护的qt无边框库[qwindowkit](https://github.com/stdware/qwindowkit.git)，个人在本地尝试添加添加xrepo支持，但是能力实在不足，请求管理者帮助，十分感谢

### 描述可能的解决方案

这个包有外部依赖，而且我在本地编译的时候（windows）会出现诡异的寻找linux头文件的情况，不知道为什么

**Comment by waruqi** [comment]
这种要搞进来，得先把它的依赖 [qmsetup](https://github.com/stdware/qmsetup) 弄进来。。这边人手有限，等有空的时候 会看下，你也可以先尝试弄下 qmsetup，应该会比直接搞 qwindowskit 简单些。。

另外，本地装修 gh cli 后，你可以用仓库的脚本，会自动生成一个包配置，稍微改改 on_test 就行了。。

```console
xmake l scripts/new.lua github:stdware/qmsetup
```

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/3892

**Comment by waruqi** [comment]
可以了
