### ISSUE TITLE
让gnu-gsl包支持Windows平台

### ISSUE THREAD

**Issue by huarkiou** [xmake-io/xmake-repo#3915]
### 你在什么场景下需要该功能？

目前仓库里面的gnu-gsl只支持linux和macos，但是实际上这个包在[Windows](https://www.gnu.org/software/gsl/#platforms)上也应该是可用的。

### 描述可能的解决方案

vcpkg上的[ports/gsl](https://github.com/microsoft/vcpkg/tree/c561d1ec136c79a8ff1e3ea125876e51006b8361/ports/gsl)是支持了windows的。
目前我直接把vcpkg上的复制过来弄了一份可以用的[gnu-gsl](https://github.com/huarkiou/xmake-repo/tree/dev/packages/g/gnu-gsl)。

### 描述你认为的候选方案

vcpkg的方案是直接为gnu-gsl写了一份cmakelists.txt，可惜我水平不够，没办法模仿着给这个库写一份xmake.lua。

**Comment by waruqi** [comment]
可以来个 pr 放开下 windows
