### ISSUE TITLE
package定义文件是否应该分版本独立文件

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake-repo#40]
比如一个包A的包定义文件分为：1.0_xmake.lua 、1.1_xmake.lua

情况比较复杂。如果该包本身就是使用xmake构建的，那么包定义文件可以很简单。

但如果该包是用其他构建方式构建的，那么随着版本的更替，构建方式、依赖关系都可能发生变化。如果全放到一个文件里是否会过于混乱。

**Comment by waruqi** [comment]
一个包的构建系统不太会经常随意更换，通常顶多某个版本时候，切到新的构建系统，更换个一两次顶多了，如果按每个版本xmake.lua独立，仓库包维护成本也相对变高，版本一多，一个包就要维护十几个xmake.lua，且部分都是冗余的。

目前这边维护这些包下来，单个xmake.lua已基本够用，如果确实遇到不同版本 构建方式差异大，通过if 分支判断下就行了

如果版本一多，维护上越来越复杂了，我会考虑丢弃这些包的部分低版本描述，只保留最新前10个版本，或者前10个典型的版本。。

毕竟不可能所有包的所有历史版本，都一个个维护进去，没这么多人力成本，仓库也会变得很臃肿，拉取变慢。

像vcpkg/homebrew都是仅维护当前最新一个版本的包。

**Comment by vkensou** [comment]
> 一个包的构建系统不太会经常随意更换，通常顶多某个版本时候，切到新的构建系统，更换个一两次顶多了，如果按每个版本xmake.lua独立，仓库包维护成本也相对变高，版本一多，一个包就要维护十几个xmake.lua，且部分都是冗余的。
> 
> 目前这边维护这些包下来，单个xmake.lua已基本够用，如果确实遇到不同版本 构建方式差异大，通过if 分支判断下就行了
> 
> 如果版本一多，维护上越来越复杂了，我会考虑丢弃这些包的部分低版本描述，只保留最新前10个版本，或者前10个典型的版本。。
> 
> 毕竟不可能所有包的所有历史版本，都一个个维护进去，没这么多人力成本，仓库也会变得很臃肿，拉取变慢。
> 
> 像vcpkg/homebrew都是仅维护当前最新一个版本的包。

不知像NPM、luarocks那样搭一个自动管理的网站成本有多大。
最好的情况还是包作者自己维护自己的包。C++这方面历史包袱太大了。

**Comment by waruqi** [comment]
所以xmake不可能对每个班全版本支持，虽然支持多版本管理，但毕竟我一个人精力有限，所以目前的情况只能折中下方案

1. 如果包作者支持对xmake的维护，提供了xmake.lua就最好了
2. 如果包作者用的还是自己的构建系统，但乐意提pr到xmake-repo来维护包构建描述，说明他本身也不太乐意经常变动构建系统，那么通常单个xmake.lua在xmake-repo里面也够用了。
3. 如果是第三方包，有其他用户帮忙贡献到xmake-repo维护，那也最好了，通常这些用户只对自己关注的版本进行支持，一般也不会太多，保留10个版本的描述基本够用，太多了也没必要
4. 如果是用户提issues需求需要我加入的新包，我通常默认只加最新版本，因为个人精力毕竟有限，但通常有时间我都会去加上，但不保证后期及时更新版本
5. 最后一种情况，就是用户自己自建私有仓库，或者工程xmake.lua直接定义自己需要的第三方包package描述，实现自己的定制化编译集成，也不需要依赖xmake-repo，那么自己想怎么整都行（当然，如果稳定了，我还是希望还是能够贡献到xmake-repo里去就最好了）

总之，虽然c++历史包袱确实很大， 但目前看并不是不能解决的，至少xmake一直在不断地改善这块。。

web这块包管理，我暂时没时间弄，如果你有兴趣可以帮忙整个，目前通过pr的方式直接在xmake-repo仓库管理也还可以，只是找包的时候不直观而已，但是github的搜索还是可以用用的

并且xmake也提供了`xmake require --search xxx` 来模糊匹配查找现有支持的包有哪些

**Comment by vkensou** [comment]
如果分版本独立文件，旧版本的定义其实是不需要维护的。旧版本只要没有错误，就不需要管它。只需要添加新版本的定义文件即可。这也是另一种对修改关闭，对扩展开放。
而且有一个好处，就是要查看该库有哪些版本，只需要遍历一遍文件，不需要加载文件。
至于之后库多了导致臃肿，维护变难。真到那时候应该考虑如何切换到WEB自动管理。

**Comment by waruqi** [comment]
> 如果分版本独立文件，旧版本的定义其实是不需要维护的。旧版本只要没有错误，就不需要管它。只需要添加新版本的定义文件即可。这也是另一种对修改关闭，对扩展开放。

关键是没人能保证旧版本一直会没问题，即使ci上通过了，还是会有很多意想不到的case需要维护和处理，现在有些包 我有时候还要时不时改进一下构建

另外，xmake也会不断的迭代升级来改进包的构建描述api，虽然会做到向下兼容，但是为了整体仓库保持风格一致，我还是会全部做一遍更新，如果做了局部重构，需要改动一些构建api的调用方式，那么新老版本不同的描述，我需要多双倍的改动和重测时间。

> 而且有一个好处，就是要查看该库有哪些版本，只需要遍历一遍文件，不需要加载文件。

不觉得这是好处，目前统一一个xmake.lua里面，我返回一次加载就可以完全所有版本列表，非常的快，改成那样，反而要多一个遍历，而且很多版本 完全是相同的构建系统和构建规则，不可能经常切构建系统，每个版本一个文件，反而冗余度更高，完全没必要

> 至于之后库多了导致臃肿，维护变难。真到那时候应该考虑如何切换到WEB自动管理。

目前现有基于git仓库的维护方式，已经很省事了，通过pr+issues也能很方便接受其他贡献者的提交。现有homebrew维护到现在也没见有什么大问题，至少这种方式已经验证是可行的，也方便支持去中心化的分布式私有仓库，只需要用户自己添加自己的其他git仓库就行。。

web管理即使做，也仅仅只是做展示+搜索来辅助，我不打算完全切过去，web的维护是不透明的，提交包 也不方便review和ci测试，如果全做起来，没那个精力，还不如利用现有github的服务。

总之，目前xmake-repo官方仓库，我不打算分版本独立xmake.lua文件，如果xmake.lua确实变的复杂不好维护了，我会废弃老版本，只维护新版本的包。

当然，这不代表xmake不支持分文件，xmake的includes以及import原本就是支持引入多文件管理package描述的，只是官方xmake-repo我不会这么干

如果用户自己的私有包仓库，或者内置在自己工程里面的package包，我管不着，用户可以自己觉得是否要分xmake.lua单独管理，只需要通过下面的方式，自己处理就行了

```lua
package("test")
    on_install(function (package)
        if package:version():gt("2.0") then
              import("install_2x", {alias = "install"})
        else
              import("install_1x", {alias = "install"})
        end
        install(package)
    end)
```

然后在当前package目录，放置install_2x.lua/install_1x.lua就行了

```lua
function main (package)
 -- do install
end
```

对于版本列表，也可以通过includes拆分


```lua
includes(path.join(os.scriptdir(), "xxxx_1x.lua"))
includes(path.join(os.scriptdir(), "xxxx_2x.lua"))
package("test")
    -- ..
package_end()
 ```

每个includes的xxxx.lua内部可以重入package("test")域，追加设置
xxxx_1x.lua

```lua
package("test")
    add_versions("1.0", ...)
```

xxxx_2x.lua

```lua
package("test")
    add_versions("2.0", ...)
```

你想怎么搞就怎么搞

**Comment by waruqi** [comment]
这个就先这样吧，反正package本身是支持份文件定义的。
