### ISSUE TITLE
部分Checks不支持 C++20 标准……

### ISSUE THREAD

**Issue by chen-qingyu** [xmake-io/xmake-repo#4052]
### 描述问题

我正在更新xmake-repo packages里的一个我写的项目[pyincpp](https://github.com/chen-qingyu/pyincpp)：https://github.com/xmake-io/xmake-repo/pull/4050

在本地用 `g++ -std=c++20 -Wall -Wextra -Wold-style-cast -Wpedantic -Werror` 编译测试通过并且无任何警告，而Checks总是有8个失败：8 failing and 57 successful checks，（test里配置了configs = {languages = "c++20"}），详情如下：

1. Android (Windows) / build (armeabi-v7a, r22, 29) (pull_request): `error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
2. Android / build (ubuntu-latest, armeabi-v7a, r22, 29) (pull_request): `error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
3. macOS (x86_64) / build (macos-12, x86_64, static) (pull_request): `error: object of type 'const const pyincpp::Str' cannot be compared because its 'operator<=>' is implicitly deleted`
4. Android / build (ubuntu-latest, armeabi-v7a, r22, 21) (pull_request): `error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
5. macOS (x86_64) / build (macos-12, x86_64, shared) (pull_request): `error: object of type 'const const pyincpp::Str' cannot be compared because its 'operator<=>' is implicitly deleted`
6. Android (Windows) / build (arm64-v8a, r22, 29) (pull_request): `error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
7. Android / build (ubuntu-latest, arm64-v8a, r22, 29) (pull_request): `error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
8. Android / build (ubuntu-latest, arm64-v8a, r22, 21) (pull_request): `error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`

可以看到，这八个失败的checks总共分为两个原因：

1. Android (r22) 是编译器找不到input_iterator这个concept的定义，而我是include了`<iterator>`这个头文件的，也用了`-std=c++20`，而且我还从一开始的简写形式换成了标准形式，都不行……而 Android (r26) 及以上就编译通过没有问题。
![image](https://github.com/xmake-io/xmake-repo/assets/44673219/b7451226-2b07-4210-a55d-0588f9939a16)

2. macOS (macos-12) 的是找不到默认的`operator<=>`实现，但是按照C++20标准，`operator<=>`可以`= default`，而macOS (macos-14) 及以上就编译通过没有问题。
![image](https://github.com/xmake-io/xmake-repo/assets/44673219/68db2a9d-2e2c-44a7-a3f2-51171d8d054d)

所以，我几乎可以肯定失败的这些编译器版本不能很好地支持C++20的标准……其实还有其他的比如不支持`constexpr vector::size()`以及`string_view`不支持迭代器构造，这些我都用另外的写法workaround了，但是上述两个C++20的特性确实需要……

### 期待的结果

Please update or remove the old target checks……
Android r22 -> r26
macos 12 -> 14

### 工程配置

```lua
    add_versions("v2.3.0", "e10640c03a6ae9365a299f57a68a5f2a873146b07f92fd33bc4f673e21d68072")
    ...
    on_test(function (package)
        assert(package:check_cxxsnippets({test = [[
            #include <cassert>
            using namespace pyincpp;
            void test() {
                Dict<Str, List<Int>> dict = {{"first", {"123", "456"}}, {"second", {"789"}}, {"third", {"12345678987654321", "5"}}};
                assert(dict.keys() == (Set<Str>{"first", "second", "third"}));
                assert(dict["third"][-1].factorial() == 120);
            }
        ]]}, {configs = {languages = "c++20"}, includes = "pyincpp.hpp"}))
    end)
```

### 附加信息和错误日志

1. Android (Windows) / build (armeabi-v7a, r22, 29) (pull_request): `C:\Users\runneradmin\AppData\Local\.xmake\packages\p\pyincpp\v2.3.0\29add14e6baa420b8b92e98d4358db93\include/utility.hpp:78:16: error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
2. Android / build (ubuntu-latest, armeabi-v7a, r22, 29) (pull_request): `/home/runner/.xmake/packages/p/pyincpp/v2.3.0/29add14e6baa420b8b92e98d4358db93/include/utility.hpp:78:16: error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
3. macOS (x86_64) / build (macos-12, x86_64, static) (pull_request): `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/operations.h:487:21: error: object of type 'const const pyincpp::Str' cannot be compared because its 'operator<=>' is implicitly deleted`
4. Android / build (ubuntu-latest, armeabi-v7a, r22, 21) (pull_request): `/home/runner/.xmake/packages/p/pyincpp/v2.3.0/29add14e6baa420b8b92e98d4358db93/include/utility.hpp:78:16: error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
5. macOS (x86_64) / build (macos-12, x86_64, shared) (pull_request): `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/operations.h:487:21: error: object of type 'const const pyincpp::Str' cannot be compared because its 'operator<=>' is implicitly deleted`
6. Android (Windows) / build (arm64-v8a, r22, 29) (pull_request): `C:\Users\runneradmin\AppData\Local\.xmake\packages\p\pyincpp\v2.3.0\9bcbd08524374df78cefe13f4d18e98b\include/utility.hpp:78:16: error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
7. Android / build (ubuntu-latest, arm64-v8a, r22, 29) (pull_request): `/home/runner/.xmake/packages/p/pyincpp/v2.3.0/9bcbd08524374df78cefe13f4d18e98b/include/utility.hpp:78:16: error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`
8. Android / build (ubuntu-latest, arm64-v8a, r22, 21) (pull_request): `/home/runner/.xmake/packages/p/pyincpp/v2.3.0/9bcbd08524374df78cefe13f4d18e98b/include/utility.hpp:78:16: error: no type named 'input_iterator' in namespace 'std'; did you mean 'input_iterator_tag'?
template <std::input_iterator InputIt>`

**Comment by waruqi** [comment]
参考下这个 patch，https://github.com/xmake-io/xmake-repo/pull/4010/files

现在 ci 支持自动跳过不支持的 case 了

**Comment by chen-qingyu** [comment]
> 参考下这个 patch，https://github.com/xmake-io/xmake-repo/pull/4010/files
> 
> 现在 ci 支持自动跳过不支持的 case 了

谢谢，试了下，这个应该有用……但是有点麻烦……要同时且只跳过android-r22和macos-12逻辑稍显复杂……
我估计其他使用C++20的库可能也会遇到各种各样旧版本不支持的问题……
不知道更新新版本是否可行，我尝试update了一下 CI 的配置，提了个 PR …… #4053
