### ISSUE TITLE
`xmake l scripts/test.lua` error

### ISSUE THREAD

**Issue by chen-qingyu** [xmake-io/xmake-repo#4061]
### Xmake Version

2.9.1

### Operating System Version and Architecture

Windows 10, Lua 5.4.6

### Describe Bug

Use `xmake l scripts/test.lua --shallow -vD zlib` error during startup testing：`error: field 'apis' is not callable (a nil value)`

It looks like this code error:
```lua
-- check package is supported?
function _check_package_is_supported()
    for _, names in pairs(core_package.apis()) do
        for _, name in ipairs(names) do
            if type(name) == "string" and name == "package.on_check" then
                return true
            end
        end
    end
end
```

Remove the parentheses after 'core_package. apis()' and it seems like can run it now. A PR #4062 was added.

### Expected Behavior

Can run tests.

### Project Configuration

`xmake l scripts/test.lua --shallow -vD zlib`

### Additional Information and Error Logs

xmake-repo on dev ≡  ~1 |  ~1 ➜ x xmake l scripts/test.lua --shallow -vD zlib   
{ 
  "zlib" 
}

C:\Users\YU\AppData\Local\Temp\.xmake\240518\xmake-repo\test
add local repository(local-repo): C:\Users\YU\Desktop\xmake-repo ok!
local repositories:
    local-repo C:\Users\YU\Desktop\xmake-repo 

global repositories:
    build-artifacts https://gitee.com/xmake-mirror/build-artifacts.git main
    xmake-repo https://gitee.com/tboox/xmake-repo.git master
    builtin-repo C:\Program Files\xmake\repository

4 repositories were found!
checking for platform ... windows
checking for architecture ... x64
checking for cl.exe ... D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.39.33523
checking for zig ... ok
checking for nim ... ok
checking for link.exe ... D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
configure
{
    plat = windows
    clean = true
    kind = static
    mode = release
    ndk_stdcxx = true
    vs = 2022
    ccache = true
    buildir = build
    arch = x64
    host = windows
}
error: field 'apis' is not callable (a nil value)

**Comment by star-hengxing** [comment]
更新一下：`xmake update -s dev`

**Comment by chen-qingyu** [comment]
> 更新一下：`xmake update -s dev`

OK
