### ISSUE TITLE
Add support for Fortran in OpenMP package

### ISSUE THREAD

**Issue by jbloino** [xmake-io/xmake-repo#4065]
### Is your feature request related to a problem? Please describe.

The current OpenMP package (`packages/o/openmp`) does not support Fortran compilers, in particular GFortran.

### Describe the solution you'd like

Add support for Fortran compilers.  Since most common Fortran compilers are part of compiler suites (GFortran, Intel Fortran, NVFortran), the changes would mostly consist in adding the suitable binary names.
This would be convenient to be able to compile Fortran programs.

### Describe alternatives you've considered

I have modified a local copy of `packages/o/openmp/xmake.lua` (see attached file [xmake.lua.zip](https://github.com/xmake-io/xmake-repo/files/15366117/xmake.lua.zip)).  This works in my project adding it as a local repository.  However, it would be more convenient to have such a feature integrated directly into the xmake repositories and may be useful to other users.

**Comment by waruqi** [comment]
you can open a pr to improve this package.
