### ISSUE TITLE
请求NumCpp包

### ISSUE THREAD

**Issue by KarryCharon** [xmake-io/xmake-repo#4079]
### 你在什么场景下需要该功能？

-

### 描述可能的解决方案

NumCpp 包地址 https://github.com/dpilger26/NumCpp

### 描述你认为的候选方案

-

### 其他信息

-

**Comment by star-hengxing** [comment]
https://github.com/xmake-io/xmake-repo/blob/dev/packages%2Fn%2Fnumcpp%2Fxmake.lua

**Comment by KarryCharon** [comment]
> https://github.com/xmake-io/xmake-repo/blob/dev/packages%2Fn%2Fnumcpp%2Fxmake.lua

原来如此, 我写的是 NumCpp 大写 需要写成 numcpp

**Comment by star-hengxing** [comment]
> > https://github.com/xmake-io/xmake-repo/blob/dev/packages%2Fn%2Fnumcpp%2Fxmake.lua
> 
> 原来如此, 我写的是 NumCpp 大写 需要写成 numcpp

xrepo 包强制全部小写。另外，也可以用 `xrepo search xxx`
