### ISSUE TITLE
opencv package support on windows

### ISSUE THREAD

**Issue by Heafei** [xmake-io/xmake-repo#41]
package “opencv”  are unsupported for windows/x64

**Comment by waruqi** [comment]
opencv库我还没时间弄Win版本，你可以切到vcpkg/conan上去集成opencv for win。。

conan/vcpkg的集成见文档：

https://xmake.io/#/zh-cn/package/remote_package?id=%e6%b7%bb%e5%8a%a0conan%e7%9a%84%e4%be%9d%e8%b5%96%e5%8c%85

https://xmake.io/#/zh-cn/package/remote_package?id=%e6%b7%bb%e5%8a%a0vcpkg%e7%9a%84%e4%be%9d%e8%b5%96%e5%8c%85

**Comment by waruqi** [comment]
我已经支持 opencv on windows了
