### ISSUE TITLE
请教如何为特定的库配置tripet（尤其是android/ios下的triplets）

### ISSUE THREAD

**Issue by fallending** [xmake-io/xmake-repo#413]
### 描述讨论详情

请教，如题；有没有详细的文档或不错的现有库配置参考呢？灰常感谢！！！

**Comment by fallending** [comment]
当前报错：
```
note: the following packages are unsupported for iphoneos/arm64!
  -> protobuf-cpp-local 2.6.1
  -> openssl 1.1.1k
```

**Comment by fallending** [comment]
- protobuf-cpp-local 是为了支持protobuf的老版本，而老版本的下载url模板和新版本不一致
- 还有一个问题，支持老版本的过程中，原protobuf-cpp的配置文件中的on_test就不兼容老的，如下：
```
on_test(function (package)
        print('sdfssdfsadfas=================')
        print(package.version())
        print(package.url_version())
        print(package.versions())
        print(package.version_str())
        print(package._VERSION)
        print(package._VERSION_STR)
        
        io.writefile("test.proto", [[
            syntax = "proto3";
            package test;
            message TestCase {
                string name = 4;
            }
            message Test {
                repeated TestCase case = 1;
            }
        ]])
        os.vrun("protoc test.proto --cpp_out=.")
        assert(package:check_cxxsnippets({test = io.readfile("test.pb.cc")}, {configs = {includedirs = {".", package:installdir("include")}, languages = "c++11"}}))
    end)
```
所以我想，这里package对象的介绍，有没有详细文档介绍，比如：如何获取当前包的version呢？

**Comment by xq114** [comment]
> 所以我想，这里package对象的介绍，有没有详细文档介绍，比如：如何获取当前包的version呢？

用`package:version()`

xmake-repo中已有的所有包都可作为参考，推荐使用编辑器的搜索功能，例如搜索version()。文档见 https://xmake.io/#/zh-cn/package/remote_package?id=%e6%b7%bb%e5%8a%a0%e5%8c%85%e5%88%b0%e4%bb%93%e5%ba%93

**Comment by xq114** [comment]
不想clone整个仓库可以在线看 https://github1s.com/xmake-io/xmake-repo

**Comment by waruqi** [comment]
> 当前报错：
> 
> ```
> note: the following packages are unsupported for iphoneos/arm64!
>   -> protobuf-cpp-local 2.6.1
>   -> openssl 1.1.1k
> ```

当前这两包没有配置上对ios的支持，你得自己改下  加上支持才行，on_install("iphoneos", ...

**Comment by waruqi** [comment]
> protobuf-cpp-local 是为了支持protobuf的老版本，而老版本的下载url模板和新版本不一致

通过 package:version() 动态修改 url 和 安装逻辑

目前package的接口文档还没时间加，不过有其他外国友人帮忙在 xmake docs的英文版上加了部分接口说明 可以看看

**Comment by fallending** [comment]
> > protobuf-cpp-local 是为了支持protobuf的老版本，而老版本的下载url模板和新版本不一致
> 
> 通过 package:version() 动态修改 url 和 安装逻辑
> 
> 目前package的接口文档还没时间加，不过有其他外国友人帮忙在 xmake docs的英文版上加了部分接口说明 可以看看
> 
> 另外这个 protobuf-cpp-local 确实很老，差异很大，建议单独开个package 独立维护好了

好的。老版本被使用的概率很小，所以我用local-repo吧，不提pr。

**Comment by fallending** [comment]
> > 当前报错：
> > ```
> > note: the following packages are unsupported for iphoneos/arm64!
> >   -> protobuf-cpp-local 2.6.1
> >   -> openssl 1.1.1k
> > ```
> 
> 当前这两包没有配置上对ios的支持，你得自己改下 加上支持才行，on_install("iphoneos", ...

on_install("iphoneos 和 on_install("@iphoneos 是什么区别呀？看到 xmake-repo 中有不少@为前缀的

**Comment by waruqi** [comment]
> on_install("iphoneos 和 on_install("@iphoneos 是什么区别呀？看到 xmake-repo 中有不少@为前缀的

"plat"
"plat@host"

`@` 后面的是 当前xmake运行的host系统，前面的是编译平台

**Comment by fallending** [comment]
> version()

thx~~ ```package:version()``` works fine!
