### ISSUE TITLE
openmp缺少shflags

### ISSUE THREAD

**Issue by Elite-stay** [xmake-io/xmake-repo#4137]
### Xmake 版本

2.8.9

### 操作系统版本和架构

Ubuntu 20.04

### 描述问题

依赖openmp的动态库构建时无法链接

### 期待的结果

依赖openmp的动态库可以构建成功

### 工程配置

见 [#5133 ](https://github.com/xmake-io/xmake/discussions/5133)

### 附加信息和错误日志

见 [#5133 ](https://github.com/xmake-io/xmake/discussions/5133)

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/4141
