### ISSUE TITLE
[opencv] opencv普通和debug模式均无法安装

### ISSUE THREAD

**Issue by Arteiimis** [xmake-io/xmake-repo#4238]
### Xmake 版本

2.9.2

### 操作系统版本和架构

win10

### 描述问题

opencv普通和debug模式均无法安装，大量protobuf报错

### 期待的结果

正常安装

### 工程配置

```lua
add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})

add_requires("spdlog", {configs = {debug = true}})
add_requires("opencv", {alias = "opencv", configs = {debug = true}})
set_languages("c++20")
set_runtimes("MD")

add_ldflags("/subsystem:console")

target("qt_opencv")
    add_rules("qt.widgetapp", "qt.quickapp")
    add_packages("opencv", "spdlog")	

    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/mainwindow.ui")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/mainwindow.h")

    set_toolchains("clang-cl")
target_end()
```

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake-repo/assets/94288976/da9386b0-4cfe-46bc-9be9-eff080dcf660)

**日志请见**：[install.txt](https://github.com/user-attachments/files/15536916/install.txt)

**Comment by waruqi** [comment]
```console
xrepo update-repo
xmake f -cvD
xmake 
```

再试试

**Comment by Arteiimis** [comment]
> ```
> xrepo update-repo
> xmake f -cvD
> xmake 
> ```
> 
> 再试试

非debug模式已经可以正常构建，debug模式依旧报大量protobuf错误

**Comment by waruqi** [comment]
> > ```
> > xrepo update-repo
> > xmake f -cvD
> > xmake 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 再试试
> 
> 非debug模式已经可以正常构建，debug模式依旧报大量protobuf错误

目前没更多 ci 资源压测 debug，也没人力对 debug 维护。。只能保证 release 下正常。。debug 下，可以自己提 pr 过来改进下包
