### ISSUE TITLE
请问，能不能做源呢，远程包下载好，用xmake.lua

### ISSUE THREAD

**Issue by xizhengchao** [xmake-io/xmake-repo#43]
https://github.com/mono/mono,这个非常有用的，就是不会做xmake.lua,希望作者有时间的话看看这个，这个是纯c的项目的。

**Comment by waruqi** [comment]
这个不是跑c#的么，放到xmake里面去引用做什么用？

**Comment by xizhengchao** [comment]
这个是可以嵌入到任何程序里的，嵌入式的方式，可以把c#当脚本来弄的。

**Comment by xizhengchao** [comment]
这个可引用静态库和动态库，然后在自己程序里嵌入进去的。

**Comment by waruqi** [comment]
那要在xmake.lua里面做什么？编译的时候在自定义脚本里面调用跑c#？

**Comment by xizhengchao** [comment]
就是编译出来就行了，里面有动态库，静态库等这些的，不用管c#的。它这个也是全平台的，除了xp，几乎所有都支持，包括安卓，ios这些。

**Comment by waruqi** [comment]
就是说 你是要用里面的库咯？ 等后两天 有时间 我看下  ，你也可以参考xmake-repo里面其他的xmake.lua写法扩展进去，也可以参考：https://github.com/Homebrew/linuxbrew-core/blob/aea1a6aeb7124edd1ba9dadb78d2968ee2a5cda7/Formula/mono.rb

**Comment by xizhengchao** [comment]
是的，就是用他的库，编译出来后，动态库和静态库都包含了，而且还带有其他的。就是不会弄这个的，才找老大你的。 这个还是挺有用的，嵌入式的方式，就是纯c的。

**Comment by waruqi** [comment]
那等下周有时间我看看

**Comment by waruqi** [comment]
我macosx/linux的加上了，https://github.com/xmake-io/xmake-repo/blob/master/packages/m/mono/xmake.lua

其他平台目前还没时间看，你可以自己先研究下，改下xmake.lua支持其他平台。
