### ISSUE TITLE
add_requires("protobuf-cpp") 没有下载最新版

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake-repo#44]
下载的是3.8.0，最新是3.12.3

文档：
> 当然，如果我们对当前的依赖包的版本没有特殊要求，那么可以直接这么写：
> add_requires("tbox", "libpng", "zlib")
> 这会使用已知的最新版本包，或者是master分支的源码编译的包

[https://xmake.io/#/zh-cn/manual/global_interfaces?id=add_requires]()

**Comment by playgithub** [comment]
看到了，我先学习一下

**Comment by playgithub** [comment]
改了xmake.lua
```lua
add_requires("protobuf-cpp 3.12.3")
```
```
error: unable to select version for range '3.12.3'
```

**Comment by waruqi** [comment]
仔细看下我刚说的

> 自己到 https://github.com/xmake-io/xmake-repo/blob/master/packages/p/protobuf-cpp/xmake.lua 提个pr更新下

**Comment by playgithub** [comment]
加了版本号，还是要通过`protobuf-cpp/xmake.lua`来实现版本好匹配？

**Comment by waruqi** [comment]
默认选最新的 也可以写死版本匹配

**Comment by playgithub** [comment]
那`add_requires("protobuf-cpp 3.12.3")`怎么不行？
```
error: unable to select version for range '3.12.3'
```

**Comment by waruqi** [comment]
你怎么就不理解呢？我觉得我已经说的很明白 让你提个pr到xmake-repo的protobuf包里面加上对应版本号和hash，连url都贴给你了

你说加了，加在哪里呢？我怎么没收到pr?  

只有xmake-repp仓库有protobuf 3.12.3版本，你项目的add_requires里面才能获取到这个版本


> 仔细看下我刚说的
> 
> > 自己到 https://github.com/xmake-io/xmake-repo/blob/master/packages/p/protobuf-cpp/xmake.lua 提个pr更新下

**Comment by playgithub** [comment]
刚学，xmake-repo仓库概念都没有，是不是像这样：

xmake-repo/packages/p/protobuf-cpp/xmake.lua
```
add_urls("https://github.com/protocolbuffers/protobuf/releases/download/v$(version)/protobuf-cpp-$(version).zip")
    add_versions("3.8.0", "91ea92a8c37825bd502d96af9054064694899c5c7ecea21b8d11b1b5e7e993b5")
cpp-$(version).zip")
    add_versions("3.12.3", "hash")
```

**Comment by waruqi** [comment]
我快醉了。。让你填hash，不是让你填 "hash" 字符串哈。。。你参考上面一行么，不是有例子么。。

add_versions("3.8.0", "91ea92a8c37825bd502d96af9054064694899c5c7ecea21b8d11b1b5e7e993b5")

前面版本，后面 sha256 hash值，我觉得很明了哈。。

**Comment by playgithub** [comment]
是的，我不知道是那种hash，所以意思了一下
文档里没找到，去cahce目录里试了一下，是sha256

**Comment by waruqi** [comment]
文档见：https://xmake.io/#/zh-cn/package/remote_package?id=add_versions

**Comment by playgithub** [comment]
> add_versions
> 用于设置每个源码包的版本和对应的sha256值，具体描述见：add_urls

**Comment by playgithub** [comment]
已PR

**Comment by waruqi** [comment]
已经merge，你本地执行下 xmake repo -u更新下repo，然后 执行 xmake f -c 试试

```console
xmake repo -u
xmake f -c
xmake
```

**Comment by playgithub** [comment]
```
λ xmake f -c
checking for the architecture ... x64
checking for the Microsoft Visual Studio (x64) version ... 2019
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> protobuf-cpp 3.12.3
please input: y (y/n)

  => downloading protobuf-cpp .. (1/curl) -
```
没问题

**Comment by playgithub** [comment]
地址没错[https://github.com/protocolbuffers/protobuf/releases/download/v3.12.3/protobuf-cpp-3.12.3.zip]()
如果开shadowsocks，用浏览器，一下就下载了
同样开shadowsocks，`xmake`一直下载不了

**Comment by waruqi** [comment]
xmake用的curl下载 怎么可能跟浏览器 用相同的代理，完全就没关系 ，请先确保curl的代理走了你的ss

**Comment by playgithub** [comment]
记得curl代理需要参数的，先这样，有机会研究一下

**Comment by playgithub** [comment]
> 已经merge，你本地执行下 xmake repo -u更新下repo，然后 执行 xmake f -c 试试
> 
> ```
> xmake repo -u
> xmake f -c
> xmake
> ```

`protobuf-cpp-3.12.3.zip`拷到cache目录，旧的删掉，`xmake`没问题
