### ISSUE TITLE
x265: Failed to Install x265 in NUMA Environment

### ISSUE THREAD

**Issue by KkemChen** [xmake-io/xmake-repo#4402]
### Xmake 版本

2.9.2

### 操作系统版本和架构

Ubuntu18.04

### 描述问题

x265在支持numa的环境下缺少 numa的syslinks，导致无法正确安装该包

### 期待的结果

修复改包

### 工程配置

add_requires("x265")

### 附加信息和错误日志

![FT7ABJ M (JV9VF7AA1PE(V](https://github.com/xmake-io/xmake-repo/assets/44298896/845ebd2e-1b64-4cc6-ad18-d34cdb395070)

![UIJ)QO~6CMZZHNXM)PCLMXN](https://github.com/xmake-io/xmake-repo/assets/44298896/8efd2f3b-6e54-44aa-93d1-96469bf9673a)

**Comment by star-hengxing** [comment]
I found that xrepo already has the numa package, the previous modification was not quite right. A robustness fix https://github.com/xmake-io/xmake-repo/pull/6096
