### ISSUE TITLE
无法修改 spdlog.fmt 的版本

### ISSUE THREAD

**Issue by yflin1** [xmake-io/xmake-repo#4409]
### Xmake 版本

v2.9.2+HEAD.6b6557c

### 操作系统版本和架构

Ubuntu 22.04

### 描述问题

使用 add_requireconfs() 修改 spdlog 依赖的 fmt 包的版本无效，配置安装时，还是在安装 fmt 最新版本 10.2.1 版

### 期待的结果

改为安装 fmt 8.1.1 版本

### 工程配置

xmake.lua 里配置如下：
`
add_requires("spdlog v1.10.0", {system = false, configs = {header_only = true, fmt_external=true}})
add_requireconfs("spdlog.fmt", {version = "8.1.1"})
`

### 附加信息和错误日志

`
    require(spdlog v1.10.0): v1.10.0
      -> dep(cmake): 3.25.0, system
      -> dep(fmt): 10.2.1
      -> version: v1.10.0
      -> syslinks: pthread
      -> license: MIT
      -> sysincludedirs: /home/xxx/.xmake/packages/s/spdlog/v1.10.0/b783a3bd9d304298a1d76322abd512a2/include
      -> defines: SPDLOG_FMT_EXTERNAL
`

**Comment by star-hengxing** [comment]
https://xmake.io/#/manual/global_interfaces?id=set-general-default-configuration

```lua
add_requireconfs("spdlog.fmt", {override = true, version = "8.1.1"})
```

**Comment by yflin1** [comment]
> https://xmake.io/#/manual/global_interfaces?id=set-general-default-configuration
> 
> ```lua
> add_requireconfs("spdlog.fmt", {override = true, version = "8.1.1"})
> ```

这个可以，生效了，非常感谢！！
