### ISSUE TITLE
pcl编译问题

### ISSUE THREAD

**Issue by zhangzhousuper** [xmake-io/xmake-repo#4425]
### Xmake 版本

xmake v2.9.2+master.872ddbd0c

### 操作系统版本和架构

win10

### 描述问题

安装pcl默认设置的时候是正常的，当加上vtk=true后会出现编译错误

### 期待的结果

成功链接

### 工程配置

add_rules("mode.debug", "mode.release")
add_requires("pcl",{configs = {vtk = true}})
add_requires("boost","vtk")
set_languages("c++20")
target("hello")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("boost","vtk")
    add_packages("pcl",{configs = {vtk = true}})

### 附加信息和错误日志

.xmake\cache\packages\2406\p\pcl\1.14.0\source\io\include\pcl\io\ply\ply_parser.h(101,31): error C2039: "function": 不是 "std" 的成员 [C:\Users\*\A
       ppData\Local\.xmake\cache\packages\2406\p\pcl\1.14.0\source\build_f426b0bb\io\pcl_io_ply.vcxproj]
         (编译源文件“../../io/src/ply/ply_parser.cpp”)
             C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\sstream(19,1):
             参见“std”的声明

**Comment by star-hengxing** [comment]
上游问题，需要做一个 patch
https://github.com/PointCloudLibrary/pcl/issues/5962
