### ISSUE TITLE
fmt,toml++,spdlog等依赖包均安装失败

### ISSUE THREAD

**Issue by zyf2008Neptune** [xmake-io/xmake-repo#4442]
### Xmake 版本

2.9.2

### 操作系统版本和架构

github action windows-latest

### 描述问题

依赖包安装失败，见日志

### 期待的结果

正确安装

### 工程配置

set_xmakever("2.9.2")

-- project
set_project("QUI")
set_version("0.3.3")
set_license("MIT")
set_languages("c++20")
set_optimize("faster")
set_warnings("allextra", "error")

-- allowed
set_allowedarchs("x64")
set_allowedmodes("debug", "releasedbg")

-- default
set_defaultarchs("x64")
set_defaultmode("releasedbg")

-- rules
add_rules("mode.debug", "mode.releasedbg")

-- packages

add_requires("fmt", "frozen", "toml++ 3.1.0")
add_requires("spdlog", { configs = { header_only = false } })
add_requires("commonlibsse-ng", { configs = { skyrim_vr = false }})
	
includes("res/package.lua")
includes("src")

### 附加信息和错误日志

Run xmake package -y
checking for platform ... windows
checking for architecture ... x[6](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:7)4
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.40.33811
  => download https://github.com/fmtlib/fmt/releases/download/10.2.1/fmt-10.2.1.zip .. ok
  => download https://github.com/serge-sans-paille/frozen/archive/refs/tags/1.1.1.tar.gz .. ok
  => download https://github.com/gabime/spdlog/archive/refs/tags/v1.14.1.zip .. ok
  => download https://github.com/marzer/tomlplusplus/archive/refs/tags/v3.4.0.tar.gz .. ok
  => install frozen 1.1.1 .. ok
  => download https://github.com/d99kris/rapidcsv/archive/refs/tags/v8.82.zip .. ok
  => install rapidcsv 8.82 .. ok
  => install fmt 10.2.1 .. failed

CMake Error at CMakeLists-- Configuring incomplete, errors occurred!
command:
    C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe
  to get the value of VCTargetsPath:
    MSBuild version 1[7](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:8).10.4+10fbfbf2e for .NET Framework
    Build started 6/21/2024 2:24:21 PM.
    
    Project "C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\f\fmt\10.2.1\source\build_f09ca0c0\CMakeFiles\3.29.6\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB[8](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:9)020: The build tools for v144 (Platform Toolset = 'v144') cannot be found. To build using the v144 build tools, please install v144 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\f\fmt\10.2.1\source\build_f0[9](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:10)ca0c0\CMakeFiles\3.29.6\VCTargetsPath.vcxproj]
    Done Building Project "C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\f\fmt\[10](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:11).2.1\source\build_f09ca0c0\CMakeFiles\3.29.6\VCTargetsPath.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.
    
    "C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\f\fmt\10.2.1\source\build_f09ca0c0\CMakeFiles\3.29.6\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) -> 
      C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for v[14](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:15)4 (Platform Toolset = 'v144') cannot be found. To build using the v144 build tools, please install v144 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\f\fmt\10.2.1\source\build_f09ca0c0\CMakeFiles\3.29.6\VCTargetsPath.vcxproj]
    
if you want to get more verbose errors, please see:
  -> C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\f\fmt\10.2.1\installdir.failed\logs\install.txt
  => install toml++ v3.4.0 .. failed

-- Configuring incomplete, errors occurred!
 Failed to run MSBuild command:
    C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe
  to get the value of VCTargetsPath:
    MSBuild version [17](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:18).10.4+10fbfbf2e for .NET Framework
    Build started 6/21/2024 2:24:21 PM.
    
    Project "C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\t\toml++\v3.4.0\source\build_17afd038\CMakeFiles\3.29.6\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files\Microsoft Visual Studio\[20](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:21)22\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for v144 (Platform Toolset = 'v144') cannot be found. To build using the v144 build tools, please install v144 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\t\toml++\v3.4.0\source\build_17afd038\CMakeFiles\3.29.6\VCTargetsPath.vcxproj]
    Done Building Project "C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\t\toml++\v3.4.0\source\build_17afd038\CMakeFiles\3.29.6\VCTargetsPath.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.
    
    "C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\t\toml++\v3.4.0\source\build_17afd038\CMakeFiles\3.29.6\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) -> 
      C:\Program Files\Microsoft Visual Studio\20[22](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:23)\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for v144 (Platform Toolset = 'v144') cannot be found. To build using the v144 build tools, please install v144 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\[24](https://github.com/zyf2008Neptune/skse-qui/actions/runs/9615172767/job/26521710123#step:7:25)06\t\toml++\v3.4.0\source\build_17afd038\CMakeFiles\3.29.6\VCTargetsPath.vcxproj]
    
if you want to get more verbose errors, please see:
  -> C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\t\toml++\v3.4.0\installdir.failed\logs\install.txt
  => install spdlog v1.14.1 .. failed

runv(C:\Program Files\CMake\bin\cmake -DSPDLOG_BUILD_TESTS=OFF -DSPDLOG_BUILD_EXAMPLE=OFF -DSPDLOG_BUILD_SHARED=OFF -DSPDLOG_USE_STD_FORMAT=OFF -DSPDLOG_FMT_EXTERNAL=OFF -DSPDLOG_FMT_EXTERNAL_HO=OFF -DSPDLOG_NO_EXCEPTIONS=OFF -DSPDLOG_WCHAR_SUPPORT=OFF -DCMAKE_INSTALL_PREFIX=C:\Users\runneradmin\AppData\Local\.xmake\packages\s\spdlog\v1.14.1\9be96d2054324a2eaff01eb842d42fe5 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Visual Studio 17 2022" -A x64 -DCMAKE_GENERATOR_TOOLSET=v144 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_COMPILE_PDB_OUTPUT_DIRECTORY=pdb -DCMAKE_POSITION_INDEPENDENT_CODE=ON "-DCMAKE_EXE_LINKER_FLAGS_RELEASE=  -nodefaultlib:msvcrt.lib" "-DCMAKE_C_FLAGS_RELEASE=  -MT" "-DCMAKE_STATIC_LINKER_FLAGS_RELEASE=  -nodefaultlib:msvcrt.lib" "-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=  -nodefaultlib:msvcrt.lib" "-DCMAKE_CXX_FLAGS_RELEASE=  -MT" C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\s\spdlog\v1.14.1\source) failed(-1)
if you want to get more verbose errors, please see:
  -> C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2406\s\spdlog\v1.14.1\installdir.failed\logs\install.txt
Error: The operation was canceled.

**Comment by star-hengxing** [comment]
Please update xmake.

https://github.com/xmake-io/xmake/issues/4772
