### ISSUE TITLE
xrepo install openssl : issue

### ISSUE THREAD

**Issue by raphael10-collab** [xmake-io/xmake-repo#4561]
### Xmake Version

2.9.3

### Operating System Version and Architecture

Ubuntu 23.10

### Describe Bug

    raphy@raohy:~$ xrepo search openssl
    The package names:
        openssl: 
          -> openssl-1.1.1-w: A robust, commercial-grade, and full-featured toolkit for TLS and SSL. (in xmake-repo)
          -> openssl3-3.0.7: A robust, commercial-grade, and full-featured toolkit for TLS and SSL. (in xmake-repo)
          -> boringssl-2022.06.13: BoringSSL is a fork of OpenSSL that is designed to meet Google's needs. (in xmake-repo)
          -> libressl-3.8.2: LibreSSL is a version of the TLS/crypto stack forked from OpenSSL in 2014, with goals of modernizing the codebase, improving security, and applying best practice development processes. (in xmake-repo)
    raphy@raohy:~$ 
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo install openssl3-3.0.7
    error: package(openssl3-3.0.7) not found!
    error: execv(/home/raphy/.local/bin/xmake require -j 10 --extra={system=false} openssl3-3.0.7) failed(255)
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo install openssl-1.1.1-w
    error: package(openssl-1.1.1-w) not found!
    error: execv(/home/raphy/.local/bin/xmake require -j 10 --extra={system=false} openssl-1.1.1-w) failed(255)
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo install libressl-3.8.2
    error: package(libressl-3.8.2) not found!
    error: execv(/home/raphy/.local/bin/xmake require -j 10 --extra={system=false} libressl-3.8.2) failed(255)
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo install boringssl-2022.06.13
    error: package(boringssl-2022.06.13) not found!
    error: execv(/home/raphy/.local/bin/xmake require -j 10 --extra={system=false} boringssl-2022.06.13) failed(255)
    raphy@raohy:~$ 

### Expected Behavior

xrepo install openssl without any issues

### Project Configuration

    raphy@raohy:~$ cat xmake.lua 
    set_languages("c99", "c++20")
    add_rules("mode.debug", "mode.release")
    
    --add_requires("cosmocc")
    
    add_syslinks("pthread")
    
    add_requires(
        "cosmocc",
        "wxWidgets",
        "curl",
        "leptonica",
        "tesseract",
        "PDFHummus::PDFWriter",
        --"Threads",
        "OpenSSL::SSL",
        "nng",
        "json-c",
        "sqlite3",
        "stfl",
        "xml2",
        "icui18n",
        "icuuc"
    )
    
    target("isdigits")
        set_kind("binary")
        --add_files("/home/raphy/isdigits/src/*.cpp")
        add_files("/home/raphy/Grasp/src/*.cpp")
    
        set_toolchains("@cosmocc")
    
    on_install(function (package)
         -- TODO
    end)

### Additional Information and Error Logs

 None

**Comment by star-hengxing** [comment]
`package name`-`lastest version`

Try `xrepo install openssl`

**Comment by raphael10-collab** [comment]
Yes! 
    
    raphy@raohy:~$ xrepo install openssl
    note: install or modify (m) these packages (pass -y to skip confirm)?
    in xmake-repo:
      -> openssl 1.1.1-w 
    please input: y (y/n/m)
    y
      => download https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1w.zip .. ok
      => install openssl 1.1.1-w .. ok
