### ISSUE TITLE
xrepo install libxml2 issue

### ISSUE THREAD

**Issue by raphael10-collab** [xmake-io/xmake-repo#4566]
### Xmake Version

2.9.3

### Operating System Version and Architecture

Ubuntu 23.10

### Describe Bug

    raphy@raohy:~$ xrepo search xml2
    The package names:
        xml2: 
          -> libxml2-2.10.3: The XML C parser and toolkit of Gnome. (in xmake-repo)
          -> tinyxml2-10.0.0: simple, small, efficient, C++ XML parser that can be easily integrating into other programs. (in xmake-repo)
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo install libxml2
    note: install or modify (m) these packages (pass -y to skip confirm)?
    in xmake-repo:
      -> libxml2 2.10.3 
    please input: y (y/n/m)
    y
      => install libxml2 2.10.3 .. failed
    
    /usr/bin/make  all-recursive
    make[1]: Entering directory '/home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/source'
    Making all in include
    make[2]: Entering directory '/home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/source/include'
    Making all in libxml
    make[3]: Entering directory '/home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/source/include/libxml'
    make[3]: Nothing to be done for 'all'.
    make[3]: Leaving directory '/home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/source/include/libxml'
    make[3]: Entering directory '/home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/source/include'
    make[3]: Nothing to be done for 'all-am'.
    make[3]: Leaving directory '/home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/source/include'
    make[2]: Leaving directory '/home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/source/include'
    Making all in .
    make[2]: Entering directory '/home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/source'
      CC       xmllint.o
      CC       libxml2_la-SAX.lo
      CC       libxml2_la-entities.lo
    if you want to get more verbose errors, please see:
      -> /home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/installdir.failed/logs/install.txt
    error: install failed!
    error: execv(/home/raphy/.local/bin/xmake require -j 10 --extra={system=false} libxml2) failed(255)
    raphy@raohy:~$ 

### Expected Behavior

Plain installation

### Project Configuration

    raphy@raohy:~$ cat xmake.lua 
    set_languages("c99", "c++20")
    add_rules("mode.debug", "mode.release")
    
    --add_requires("cosmocc")
    
    add_syslinks("pthread")
    
    add_requires(
        "cosmocc",
        "wxWidgets",
        "curl",
        "leptonica",
        "tesseract",
        "PDFHummus::PDFWriter",
        --"Threads",
        "OpenSSL::SSL",
        "nng",
        "json-c",
        "sqlite3",
        "stfl",
        "xml2",
        "icui18n",
        "icuuc"
    )
    
    target("isdigits")
        set_kind("binary")
        --add_files("/home/raphy/isdigits/src/*.cpp")
        add_files("/home/raphy/Grasp/src/*.cpp")
    
        set_toolchains("@cosmocc")
    
    on_install(function (package)
         -- TODO
    end)

### Additional Information and Error Logs

/home/raphy/.xmake/cache/packages/2407/l/libxml2/2.10.3/installdir.failed/logs/install.txt : 
[install.txt](https://github.com/user-attachments/files/16096612/install.txt)

**Comment by raphael10-collab** [comment]
May be I do something wrong : 

    raphy@raohy:~$ xrepo install libxml2
    note: install or modify (m) these packages (pass -y to skip confirm)?
    in xmake-repo:
      -> libxml2 2.13.2 
    please input: y (y/n/m)
    y
      => download https://download.gnome.org/sources/libxml2/2.13/libxml2-2.13.2.tar.xz .. ok
      => install libxml2 2.13.2 .. failed
    
    /usr/bin/make  all-recursive
    make[1]: Entering directory '/home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/source'
    Making all in include
    make[2]: Entering directory '/home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/source/include'
    Making all in libxml
    make[3]: Entering directory '/home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/source/include/libxml'
    make[3]: Nothing to be done for 'all'.
    make[3]: Leaving directory '/home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/source/include/libxml'
    Making all in private
    make[3]: Entering directory '/home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/source/include/private'
    make[3]: Nothing to be done for 'all'.
    make[3]: Leaving directory '/home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/source/include/private'
    make[3]: Entering directory '/home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/source/include'
    make[3]: Nothing to be done for 'all-am'.
    make[3]: Leaving directory '/home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/source/include'
    make[2]: Leaving directory '/home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/source/include'
    Making all in .
    if you want to get more verbose errors, please see:
      -> /home/raphy/.xmake/cache/packages/2409/l/libxml2/2.13.2/installdir.failed/logs/install.txt
    error: install failed!
    error: execv(/home/raphy/.local/bin/xmake require -j 10 --extra={system=false} libxml2) failed(255)

**Comment by star-hengxing** [comment]
You need to update xmake-repo first, `xrepo update-repo`
