### ISSUE TITLE
xrepo search libpdfio : no output

### ISSUE THREAD

**Issue by raphael10-collab** [xmake-io/xmake-repo#4615]
### Xmake Version

2.9.3

### Operating System Version and Architecture

Ubuntu 23.10

### Describe Bug

    raphy@raohy:~$ xrepo search libpdfio
    The package names:
    raphy@raohy:~$ xrepo search pdfio
    The package names:

### Expected Behavior

Being able to install libpdfio : 

https://github.com/michaelrsweet/pdfio

https://www.msweet.org/pdfio/

### Project Configuration

    raphy@raohy:~$ cat xmake.lua 
    set_languages("c99", "c++20")
    add_rules("mode.debug", "mode.release")
    
    add_requires("cosmocc")
    
    add_syslinks("pthread")
    
    add_requires(
        "cosmocc",
        "wxWidgets",
        "curl",
        "leptonica",
        "tesseract",
        "PDFHummus::PDFWriter",
        --"Threads",
        "OpenSSL::SSL",
        "nng",
        "json-c",
        "sqlite3",
        "stfl",
        "xml2",
        "icui18n",
        "icuuc"
    )
    
    target("isdigits")
        set_kind("binary")
        --add_files("/home/raphy/isdigits/src/*.cpp")
        add_files("/home/raphy/Grasp/src/*.cpp")
    
        set_toolchains("@cosmocc")
    
    on_install(function (package)
         -- TODO
    end)

### Additional Information and Error Logs

None

**Comment by star-hengxing** [comment]
Done https://github.com/xmake-io/xmake-repo/pull/4624

**Comment by raphael10-collab** [comment]
@star-hengxing I do not find it :  

    raphy@raohy:~$ xrepo search libpdfio
    The package names:
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo search lpdfio
    The package names:
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo search *pdfio
    The package names:
    raphy@raohy:~$

**Comment by star-hengxing** [comment]
Try `xmake repo -u`

**Comment by raphael10-collab** [comment]
raphy@raohy:~$ xmake repo -u
    updating repositories .. ok
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo search libpdfio
    The package names:
    raphy@raohy:~$

**Comment by star-hengxing** [comment]
`libpdfio` -> `pdfio`

**Comment by raphael10-collab** [comment]
raphy@raohy:~$ xrepo search pdfio
    The package names:
        pdfio: 
          -> pdfio-v1.3.0: PDFio is a simple C library for reading and writing PDF files. (in xmake-repo)
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo install pdfio
    note: install or modify (m) these packages (pass -y to skip confirm)?
    in xmake-repo:
      -> pdfio v1.3.0 
    please input: y (y/n/m)
    y
      => download https://github.com/michaelrsweet/pdfio/archive/refs/tags/v1.3.0.tar.gz .. ok
      => install pdfio v1.3.0 .. ok
