### ISSUE TITLE
xrepo search libicui18n : no output

### ISSUE THREAD

**Issue by raphael10-collab** [xmake-io/xmake-repo#4633]
### Xmake Version

2.9.3

### Operating System Version and Architecture

Ubuntu 23.10

### Describe Bug

    raphy@raohy:~$ xrepo search libicui18n
    The package names:
    raphy@raohy:~$ xrepo search icui18n
    The package names:
    raphy@raohy:~$ xrepo search licui18n
    The package names:
    raphy@raohy:~$ xrepo search *icui18n
    The package names:

### Expected Behavior

Being able to install the package

### Project Configuration

    set_languages("c99", "c++20")
    add_rules("mode.debug", "mode.release")
    
    add_requires("cosmocc")
    
    add_syslinks("pthread")
    
    add_requires(
        "tbox 1.6.*",
        "libtask",
        "libpng ~1.6",
        "cosmocc",
        "libwxWidgets",
        "curl",
        "leptonica",
        "tesseract",
        "PDFHummus::PDFWriter",
        "OpenSSL::SSL",
        "nng",
        "json-c",
        "sqlite3",
        --"stfl",
        --"libxml2",
        "icui18n",
        "icuuc",
        "libpdfio"
    )
    
    target("isdigits")
        set_kind("binary")
        --add_files("/home/raphy/isdigits/src/*.cpp")
        add_files("/home/raphy/Grasp/src/*.cpp")
    
        set_toolchains("@cosmocc")
    
    on_install(function (package)
         -- TODO
    end)

### Additional Information and Error Logs

None

**Comment by star-hengxing** [comment]
Please use `icu4c`

**Comment by raphael10-collab** [comment]
raphy@raohy:~$ xrepo search icu4c
    The package names:
        icu4c: 
          -> icu4c-75.1: C/C++ libraries for Unicode and globalization. (in xmake-repo)
    raphy@raohy:~$ 
    raphy@raohy:~$ xrepo install icu4c
