### ISSUE TITLE
Matplotplusplus build error

### ISSUE THREAD

**Issue by TabNahida** [xmake-io/xmake-repo#4669]
### Xmake 版本

v2.9.3

### 操作系统版本和架构

Windows 11 23H2

### 描述问题

When i am building a test project with matplotplusplus, it fail with symbol error. When I add cxxflags="/utf-8", it pass but fail to run. Then I switch to debug mode and the matplotplusplus does not pass the build.

### 期待的结果

Successfully show the plot image

### 工程配置

```lua
add_languages("cxx23")
add_requires("matplotplusplus", {config = {cxxflags="/utf-8", debug=true}})

target("test")
    set_kind("binary")
    add_files("test.cpp")
    add_packages("matplotplusplus")
target_end()
```

```cpp
#include <array>
#include <chrono>
#include <cmath>
#include <format>
#include <functional>
#include <iostream>
#include <matplot/matplot.h>
#include <print>

#define i64 long long

double dfn(double x, double y)
{
    return y;
}

int main()
{
    std::vector<i64> x_list(100);
    for (i64 i = 0; i < x_list.size(); i++)
    {
        x_list[i] = i;
    }
    std::vector<i64> y_list(100);
    y_list[0] = 0;
    for (i64 i = 1; i < y_list.size(); i++)
    {
        y_list[i] = dfn(x_list[i], y_list[i - 1]);
    }
    matplot::plot(x_list, y_list, "-o");
    matplot::hold(matplot::on);
    matplot::show();

    return 0;
}
```

```bash
xmake config -m debug
xmake run -d test
```

### 附加信息和错误日志

[install.txt](https://github.com/user-attachments/files/16245188/install.txt)

**Comment by star-hengxing** [comment]
Fixed https://github.com/xmake-io/xmake-repo/commit/eb5cd65377a79c4d4f9594bb7334d9e85faf3aae, `xmake repo -u`

**Comment by star-hengxing** [comment]
It should work now https://github.com/xmake-io/xmake/issues/5353
