### ISSUE TITLE
xmake-repo调试有点不方便

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake-repo#47]
调试的时候，常常会有小改动，每次都要：
1. commit
2. `xmake repo -u`

有点不方便
能不能直接以本地文件系统目录作为xmake-repo地址？不会妨碍`xmake repo -u`
PS: 现在如果有多个xmake-repo（就是通过"xmkae repo --add"添加的），`xmake repo -u`会更新哪一个？

**Comment by waruqi** [comment]
你直接add本地的不就好了

**Comment by playgithub** [comment]
add本地也要git仓库，那每次调试还是要`commit`和`xmake repo -u`

**Comment by waruqi** [comment]
> add本地也要git仓库，那每次调试还是要`commit`和`xmake repo -u`

为啥要git，我都是直接add local file path，也没啥么，都直接引用本地的了，干嘛还要去commit 和 repo -u

**Comment by playgithub** [comment]
https://xmake.io/#/zh-cn/manual/global_interfaces?id=add_repositories
`add_repositories("my-repo myrepo")`这样可以，调试方便了
就是如过改xmake-repo不是最方便

**Comment by waruqi** [comment]
> add_repositories("my-repo myrepo")这样可以，调试方便了

跟xmake repo --add 完全等效，都支持 git 和 local file path

**Comment by playgithub** [comment]
对
现在需求是这样的
1. 改`lib_aaa/xmake.lua`，比如加版本
2. `xmake`起作用，不需要`commit`和`xmake repo -u`
3. 需要版本管理和PR，可以直接`commit`, `push`，PR

也就是同时方便调试和PR

**Comment by waruqi** [comment]
我不是说了么 xmake repo --add 支持local path，把你本地clone下来的 xmake-repo 本地路径 add 进来不就好了， 原本就不需要 commit/xmake repo -u ，add了就直接生效了，优先用 add的repo。

**Comment by playgithub** [comment]
可以的，`xmake-repo`和add local file的目录接口兼容

**Comment by playgithub** [comment]
如果`xmake repo --add`使用了本地目录，那`xmake repo -u`会干什么？

**Comment by waruqi** [comment]
看xmake repo --help

>     -u, --update                     Update all local repositories from the
>                                     remote.
 
拉去remote仓库最新commit，对所有git repo 执行 git pull

**Comment by playgithub** [comment]
明白了，整体考虑的，谢谢
