### ISSUE TITLE
msbuild支持并行编译

### ISSUE THREAD

**Issue by ChrisCatCP** [xmake-io/xmake-repo#4709]
### 你在什么场景下需要该功能？

msbuild支持并行编译  默认貌似是不开启的   安装包的时候编译速度太慢了

### 描述可能的解决方案

https://zhuanlan.zhihu.com/p/667591876
1. add_cxflags("/MP")
2. msbuild /p:CL_MP=true /p:CL_MPCount=12 //12个cl并行编译

**Comment by star-hengxing** [comment]
可以通过 policy `"package.cmake_generator.ninja"` 切换到 ninja 编译

**Comment by ChrisCatCP** [comment]
> 可以通过 policy `package.cmake_generator.ninja` 切换到 ninja 编译

我知道 但是感觉这个特性可以加上  我刚才试了下 编译速度快很多

**Comment by ChrisCatCP** [comment]
> 可以通过 policy `package.cmake_generator.ninja` 切换到 ninja 编译

而且  不止cmake才用msbuild吧 package也可能用

**Comment by ChrisCatCP** [comment]
才发现 issues提错位置了
