### ISSUE TITLE
使用mingw 编译hidapi依赖出现错误

### ISSUE THREAD

**Issue by zkqgxlbjx** [xmake-io/xmake-repo#4749]
### Xmake 版本

2.9.3

### 操作系统版本和架构

Windows 10 LTSC 1809

### 描述问题

在执行xmake f -p mingw -m debug出现以下问题
the following packages are unsupported on mingw/x86_64:
  -> hidapi 0.14.0

### 期待的结果

hidapi 库是支持使用mingw编译的

### 工程配置

if is_os("windows") then
    add_requires("xmake::hidapi", { alias = "hidapi"})
else
    add_requires("xmake::hidapi", { alias = "hidapi"})
    add_requireconfs("hidapi.libusb", {system = false})
end

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
库支持，不代表包现在支持，可以提个 pr 过来支持上

https://github.com/xmake-io/xmake-repo/blob/05e5a1ecc9810f0ac53aaa095ae539fd346e23d1/packages/h/hidapi/xmake.lua#L21
