### ISSUE TITLE
`gtest` package is missing the `gtest_main` target

### ISSUE THREAD

**Issue by nasso** [xmake-io/xmake-repo#475]
## The problem

The `gtest` package is missing the `gtest_main` target, making it impossible to link a binary without a hand-written `main` function:

```
error: LINK : fatal error LNK1561: entry point must be defined
```

## Proposed solution

The original `CMakeLists.txt` [links](https://github.com/google/googletest/blob/master/googletest/CMakeLists.txt#L146) the `gtest_main` target to `gtest`, so I believe the best way to opt-in to `gtest_main` from an `xmake.lua` script would look like this:

```lua
add_packages("gtest", {links="gtest_main"})
```

I am currently trying to get this to work locally, unfortunately without success so far (I am new to xmake). If I manage to find a clean way to get it to work I will probably open a pull request. But for now, I don't have a solution, which is why I'm opening this issue.

**Comment by waruqi** [comment]
add gtest_main target in package("gtest")

maybe we can add a custom configuration. like this:

https://github.com/xmake-io/xmake-repo/blob/b9f1052739ad4d2ee13ef1a158e0e0f800e7c632/packages/f/ffmpeg/xmake.lua#L12

then use it in xmake.lua

```lua
add_requires("gtest", {configs = {main = true}})
target("test")
    ...
    add_packages("gtest")
```

**Comment by nasso** [comment]
I tried to do that but I leep getting the same link error about a missing entry point. I am on Windows and when I run `xmake` with `-v`, `gtest_main.lib` _is_ present in the list of arguments passed to `link.exe`.

**Comment by nasso** [comment]
I got it working, the issue I had was described in https://github.com/xmake-io/xmake/issues/1412.

Is this ok? I also added an option to enable/disable `gmock` (default = true?).

```lua
    on_load(function (package)
        package:set("links", {})

        if package:config("main") then
            package:add("links", "gtest_main")
        end

        if package:config("gmock") then
            package:add("links", "gmock")
        end

        package:add("links", "gtest")
    end)
```

If so, I will probably open a PR shortly.

**Comment by waruqi** [comment]
> I got it working, the issue I had was described in [xmake-io/xmake#1412](https://github.com/xmake-io/xmake/issues/1412). Users should be aware of this when using `gtest`, because this is a problem I've been stuck on since yesterday.
> 
> Is this ok? I also added an option to enable/disable `gmock` (default = true?).
> 
> ```lua
>     on_load(function (package)
>         package:set("links", {})
> 
>         if package:config("main") then
>             package:add("links", "gtest_main")
>         end
> 
>         if package:config("gmock") then
>             package:add("links", "gmock")
>         end
> 
>         package:add("links", "gtest")
>     end)
> ```
> 
> If so, I will probably open a PR shortly.

ok, you can use `set_default` to disable/enable compiling gmock target directly, like this

```lua
    on_install(function (package)
        io.writefile("xmake.lua", ([[
            target("gtest")
                set_kind("static")
                set_languages("cxx11")
                add_files("googletest/src/gtest-all.cc")
                add_includedirs("googletest/include", "googletest")
                add_headerfiles("googletest/include/(**.h)")
            target("gmock")
                set_kind("static")
                set_default(%s)
                set_languages("cxx11")
                add_files("googlemock/src/gmock-all.cc")
                add_includedirs("googlemock/include", "googlemock", "googletest/include", "googletest")
                add_headerfiles("googlemock/include/(**.h)")
        ]]):format(package:config("gmock") and "true" or "false"))
        import("package.tools.xmake").install(package)
    end)
```
