### ISSUE TITLE
升级libtorch到2.4

### ISSUE THREAD

**Issue by szdytom** [xmake-io/xmake-repo#4778]
### 你在什么场景下需要该功能？

https://github.com/pytorch/pytorch/releases/tag/v2.4.0

### 描述可能的解决方案

更新[libtorch/xmake.lua](https://github.com/xmake-io/xmake-repo/blob/master/packages/l/libtorch/xmake.lua)

**Comment by waruqi** [comment]
直接提 pr 过来
