### ISSUE TITLE
Autoconf有问题

### ISSUE THREAD

**Issue by u3IFw2wfJ** [xmake-io/xmake-repo#48]
执行`xmake l scripts/test.lua -v -D autoconf` 得到以下错误信息
![image](https://user-images.githubusercontent.com/32400590/86551882-37c5cc80-befb-11ea-9715-0da3827f6a06.png)
![image](https://user-images.githubusercontent.com/32400590/86551955-693e9800-befb-11ea-8266-ab08b51fc82f.png)

经查，`/home/bcui/.xmake/packages/a/autoconf/2.69/`目录下不存在76b7c3070d364167afbd2190b4d3d703文件夹
![image](https://user-images.githubusercontent.com/32400590/86552042-ad319d00-befb-11ea-9ce5-5c37ba06cdc4.png)

**Comment by waruqi** [comment]
你什么系统。我这里测试可以么。。你可以手动切到autoconf源码目录执行下./configure .. 这个命令看看 是否ok

**Comment by u3IFw2wfJ** [comment]
> 你什么系统。我这里测试可以么。。你可以手动切到autoconf源码目录执行下./configure .. 这个命令看看 是否ok

WSL2 Ubuntu, 去cache目录里手动configure是可以的，但是package目录下找不到相应的文件

**Comment by waruqi** [comment]
你先自己看下吧，回头有时间我看下

**Comment by u3IFw2wfJ** [comment]
解决了，m4的问题。不过autoconf装完automake却识别不到autoconf，是因为在测试的时候安装的位置的原因吗

xmake.lua脚本添加了
![image](https://user-images.githubusercontent.com/32400590/86561979-b54b0600-bf16-11ea-99c0-bdce8f049154.png)
autoconf安装成功：
![image](https://user-images.githubusercontent.com/32400590/86562014-cf84e400-bf16-11ea-98e5-e9845ec6e3c2.png)
安装automake提示找不到autoconf
![image](https://user-images.githubusercontent.com/32400590/86562066-e3304a80-bf16-11ea-85f6-b63c45b50fc2.png)

**Comment by waruqi** [comment]
automake/xmake.lua  里面得加上  add_deps autoconf的依赖，才能绑定path。目前我没加，用的还是系统autoconf，而不是你装的autoconf

**Comment by u3IFw2wfJ** [comment]
很蠢的问题，就单纯是没有m4，装一下就好了，或许autoconf应该加上m4的依赖

**Comment by waruqi** [comment]
嗯 后期可以完善下

**Comment by waruqi** [comment]
我 dev 上 autoconf 已经加上了 m4 的依赖，等xmake下个版本发布后就会merge到master
