### ISSUE TITLE
包python在Windows下安装失败

### ISSUE THREAD

**Issue by wsw0108** [xmake-io/xmake-repo#483]
### 描述问题

Windows 10下，python安装失败。

### 期待的结果

python能够安装成功。

### 错误信息

如果是xmake相关编译问题，请加上`-vD`参数运行，并给出完整编译输出信息以及执行的完整命令，例如：

```console
$ xmake -vD
Scanning the drive for archives:
1 file, 25695060 bytes (25 MiB)

Extracting archive: python-3.9.5.win64.zip
--
Path = python-3.9.5.win64.zip
Type = zip
Physical Size = 25695060

Everything is Ok

Folders: 42
Files: 3902
Size:       66511416
Compressed: 25695060
error: @programdir\core\sandbox\modules\os.lua:97: cannot move py.exe to D:\packages\xmake\p\python                    n\3.9.5\6b1016917a8d49d09144bff5b8663f83\bin\py.exe Unknown
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:796]: in function 'raise'
    [@programdir\core\sandbox\modules\os.lua:97]: in function 'mv'
    [F:\GitHub\xmake-repo\packages\p\python\xmake.lua:78]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:171]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:137]: in function 'action_install'
    [...modules\private\action\require\impl\install_packages.lua:350]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:208]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:201]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:365]:

  => install python 3.9.5 .. failed
error: @programdir\modules\private\async\runjobs.lua:232: ...\modules\private\action\require\impl\a                    actions\install.lua:253: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:796]: in function 'raise'
    [...\modules\private\action\require\impl\actions\install.lua:253]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:137]: in function 'action_install'
    [...modules\private\action\require\impl\install_packages.lua:350]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:208]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:201]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:365]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:796: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:232: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:201: in function 'cotask'
        @programdir\core\base\scheduler.lua:365: in function <@programdir\core\base\scheduler.lua:362>
error: execv(xmake require -f -y --build -v -D python) failed(-1)
```

如果日志太多，可以上传附件，但必须完整，否则一率标记为 Invalid。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.5
- xmake运行平台：Windows 10
- xmake目标平台：

### 其他信息

`xmake l .\scripts\test.lua -vD python`

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/blob/35f436f9b066eb26529f3ad56e7db43b242f60e1/packages/p/python/xmake.lua#L78

似乎这个地方 os.mv 失败了

你先本地改下脚本，改成 os.cp 试试呢，或者在里面的on_install调下看看

**Comment by wsw0108** [comment]
改成cp后，这一步过去了，但是安装依然不成功：
```
> checking for c includes(Python.h)
> checking for c funcs(PyModule_New)
> checking for c links(python3, python39, _tkinter)
> checking for c snippet(has_cfuncs)
py -3 -c "import sys"
Python 3 not found!
Installed Pythons found by py Launcher for Windows
 -2.7-64 *

Requested Python version (3) not installed, use -0 for available pythons
error: @programdir\core\sandbox\modules\os.lua:350: exec(py -3 -c "import sys") failed(103)
```

系统里有安装2.7.x的python版本。

**Comment by waruqi** [comment]
py.exe 找到 py2 上去了？可以看下本地 python cache dir 下 install.failed 目录里面 bin 下，有没有 py.exe 是不是缺失导致找系统 py.exe 了。。或者 url 的 tar 包下载解压看下

**Comment by wsw0108** [comment]
直接把那行注释掉了安装成功后，`xrepo env py -3`依然报错。
应该是py Launcher for Windows的某种搜索机制导致的。

**Comment by wsw0108** [comment]
https://github.com/python/cpython/blob/main/PC/launcher.c#L249

**Comment by waruqi** [comment]
VIRTUAL_ENV 这个，你在 on_load 里面，用 package:addenv("VIRTUAL_ENV", "xxxx") 指向 包 installdir 下对应 py 目录试试呢

**Comment by wsw0108** [comment]
> VIRTUAL_ENV 这个？，你在 on_load 里面，用 package:addenv("VIRTUAL_ENV", "xxxx") 指向 包 installdir 下对应 py 目录试试呢

试过了，python.exe得放在Scripts目录，不过依然没法运行`py -3 xxx`

**Comment by waruqi** [comment]
那为啥 ci 上，还有我这都 ok么 不注释 也能test 通过

**Comment by waruqi** [comment]
C:\Users\ruki>xrepo env -b python py -3
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

啥也不改也可以的么，安装也ok

**Comment by waruqi** [comment]
> 直接把那行注释掉了安装成功后，xrepo env py -3依然报错。

xrepo env 后面默认只能指定 package name 来加载，py 不是包，直接指定。xmake 不知道是哪个包，需要指定下绑定到哪个包环境 -b python

**Comment by wsw0108** [comment]
> > 直接把那行注释掉了安装成功后，xrepo env py -3依然报错。
> 
> xrepo env 后面默认只能指定 package name 来加载，py 不是包，直接指定。xmake 不知道是哪个包，需要指定下绑定到哪个包环境 -b python

我是在一个引用了python包的测试程序下跑的。
有-b这样的参数那更棒。

**Comment by wsw0108** [comment]
> C:\Users\ruki>xrepo env -b python py -3
> Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > >
> 
> 啥也不改也可以的么，安装也ok

试试这个环境变量？`$env:PYLAUNCH_DEBUG=1`

**Comment by waruqi** [comment]
> > C:\Users\ruki>xrepo env -b python py -3
> > Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
> > Type "help", "copyright", "credits" or "license" for more information.
> > > > >
> > 
> > 
> > 啥也不改也可以的么，安装也ok
> 
> 试试这个环境变量？`$env:PYLAUNCH_DEBUG=1`

可能是我之前系统有python 所以加载 py ok，我卸载后也不行。

**Comment by waruqi** [comment]
> > VIRTUAL_ENV 这个？，你在 on_load 里面，用 package:addenv("VIRTUAL_ENV", "xxxx") 指向 包 installdir 下对应 py 目录试试呢
> 
> 试过了，python.exe得放在Scripts目录，不过依然没法运行`py -3 xxx`。
> venv的python只能作为当前环境下的默认python解释器。
> 
> 可以hack，很丑：
> 
> 1. python.exe放Scripts一份
> 2. py.ini放bin
> 3. VIRTUAL_ENV环境
> 
> py.ini
> 
> ```
> [defaults]
> python3=venv # pythonX=path?
> ```
> 
> ```
> found configured value 'python3=venv' in D:\packages\xmake\p\python\3.9.5\6b1016917a8d49d09144bff5b8663f83\bin\py.ini
> search for Python version 'venv' found 'D:\packages\xmake\p\python\3.9.5\6b1016917a8d49d09144bff5b8663f83\Scripts\python.exe'
> run_child: about to run 'D:\packages\xmake\p\python\3.9.5\6b1016917a8d49d09144bff5b8663f83\Scripts\python.exe -c "import sys"'
> child process exit code: 0
> ```

目前看没啥好办法，只能 hack 下，丑就丑点了，至少可用，而且 python.exe 也不很大，多一份不会太占空间

**Comment by wsw0108** [comment]
可以写注册表，`HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7\InstallPath = C:\Python27`这样。
但是winos包只能读注册表。

**Comment by waruqi** [comment]
> 可以写注册表，`HKCU\SOFTWARE\Python\PythonCore\2.7\InstallPath = C:\Python27`这样。
> 但是winos包只能读注册表。

不要去写注册表，目前是跟系统环境强隔离的。整个 packages 删了就能干净卸载，跟注册表耦合，之后会有各种乱七八糟的逻辑。

**Comment by wsw0108** [comment]
> > 可以写注册表，`HKCU\SOFTWARE\Python\PythonCore\2.7\InstallPath = C:\Python27`这样。
> > 但是winos包只能读注册表。
> 
> 不要去写注册表，目前是跟系统环境强隔离的。整个 packages 删了就能干净卸载，跟注册表耦合，之后会有各种乱七八糟的逻辑。

hack的结果就是找到python的路径不太对，Scripts下的，不知道会有什么影响（不过在编译环境这块，我觉得没啥影响）

**Comment by waruqi** [comment]
> > > 可以写注册表，`HKCU\SOFTWARE\Python\PythonCore\2.7\InstallPath = C:\Python27`这样。
> > > 但是winos包只能读注册表。
> > 
> > 
> > 不要去写注册表，目前是跟系统环境强隔离的。整个 packages 删了就能干净卸载，跟注册表耦合，之后会有各种乱七八糟的逻辑。
> 
> hack的结果就是找到python的路径不太对，Scripts下的，不知道会有什么影响（不过在编译环境这块，我觉得没啥影响）

只要能找到就行了，而且通常编译，我看也很少用 launcher 么。。

**Comment by wsw0108** [comment]
那都感觉可以不做这个检查了

**Comment by waruqi** [comment]
> 那都感觉可以不做这个检查了

检查还是做的，不然还不如不装launch 装了也跑不了

可以搞个 config ，比如叫 launcher，默认可以不装，不装的时候可以不检查(尽管这个时候，实际还是带着的)

也可以人为选择启用，但如果启用状态，这个检查必须得做

@xq114 也可以了解下 看有没有更好的方案

**Comment by waruqi** [comment]
可以跟进下这个 patch ，分离 py launcher 和 python https://github.com/xmake-io/xmake-repo/pull/489
