### ISSUE TITLE
Please add yasm for win64

### ISSUE THREAD

**Issue by hh-wu** [xmake-io/xmake-repo#486]
### 你在什么场景下需要该功能？

windows下编译ffmepg需要libx264，x264需要yasm for win64.

### 描述可能的解决方案

直接下载yasm_win64.exe就行。

### 描述你认为的候选方案

nil

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by waruqi** [comment]
自己提个 pr 到 https://github.com/xmake-io/xmake-repo/blob/master/packages/y/yasm/xmake.lua 把  win yasm 加进去就行了，目前包都是用户自己按需帮忙维护的。  我这边弄估计要等好久了，得看时间安排。

**Comment by hh-wu** [comment]
@waruqi 
如何实现不解包？
``` lua
package("yasm")

    set_kind("binary")
    set_homepage("https://yasm.tortall.net/")
    set_description("Modular BSD reimplementation of NASM.")

    if is_host("windows") then
        if is_arch("x64") then
            set_urls("https://github.com/yasm/yasm/releases/download/$(version)/yasm-$(version)-win64.exe")
            add_versions("1.3.0", "D160B1D97266F3F28A71B4420A0AD2CD088A7977C2DD3B25AF155652D8D8D91F")
        else
            set_urls("https://github.com/yasm/yasm/releases/download/$(version)/yasm-$(version)-win32.exe")
            add_versions("1.3.0", "DB8EF9348AE858354CEE4CC2F99E0F36DE8A47A121DE4CFEEA5A16D45DD5AC1B")
        end
    else
        add_urls("https://www.tortall.net/projects/yasm/releases/yasm-$(version).tar.gz",
                "https://ftp.openbsd.org/pub/OpenBSD/distfiles/yasm-$(version).tar.gz")
        add_versions("1.3.0", "3dce6601b495f5b3d45b59f7d2492a340ee7e84b5beca17e48f862502bd5603f")
    end

    on_install("@windows", "@mingw", "@msys", function (package)
        os.cp("*.exe", package:installdir("bin"))
        os.cp(path.join("rdoff", "*.exe"), package:installdir("bin"))
    end)

    on_install("@linux", "@macosx", function (package)
        local configs = {"--disable-python"}
        if package:debug() then
            table.insert(configs, "--enable-debug")
        end
        import("package.tools.autoconf").install(package)
    end)

    on_test(function (package)
        os.vrun("yasm --version")
    end)
```
现在的问题是
```
error: ...modules\private\action\require\impl\actions\download.lua:160: cannot extract yasm-1.3.0-win64.exe
```

**Comment by waruqi** [comment]
不要直接下载 .exe，用zip包 
https://github.com/yasm/yasm/releases/download/v1.3.0/vsyasm-1.3.0-win32.zip

**Comment by hh-wu** [comment]
不行啊，他这玩意儿必须命名为vsyasm，还需要copy一堆文件。不行我就自建个仓库重新打包一下

**Comment by waruqi** [comment]
为什么要重新命名，走 os.cp 下不复杂吧，zip里面很多东西？

**Comment by hh-wu** [comment]
readme里面是这么写的。


The YASM version vsyasm.exe is designed specifically for use
with Visual Studio 2010. To tell Visual Studio where to find
vsyasm.exe, the environment variable YASMPATH can be set to 
the absolute path of the directory in which vsyasm.exe is
located (this path should include the final backslash). 

Alternatively you can find the directory (or directories) 
where the VC++ compiler binaries are located and put copies 
of the vsyasm.exe binary in these directories. The typical 
location on 64-bit Windows is:

C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin

On 32-bit Windows it is normally at:
  
C:\Program Files\Microsoft Visual Studio 10.0\VC\bin

Depending on your system you can use either the win32 or the
x64 version of vsyasm.exe, which must be named vsyasm.exe. 

To use the new custom tools facility in Visual Studio 2010, you
need to place a copy of three files - yasm.props, yasm.targets 
and yasm.xml - into a location where they can be found by the
Visual Studio build customisation processes.  There are several 
ways to do this:

  a. put these files in the MSBUILD customisation directory, 
  which is typically at:

    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations
  
  or:
  
    C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations

  b. put them in a convenient location and set this path in the 
     'Build Customisations Search Path' in the Visual Studio 
	 'Projects and Solutions|VC++ Project Settings' item in
	 the 'Tools|Options' menu; 

  c. put them in a convenient location and set this path in the 
     'Build Customisation dialogue (discussed later).

To use YASM in a project, right click on the project in the Solution 
Explorer and select 'Build Customisations..'. This will give you a 
dialog box that allows you to select YASM as an assembler (note that 
your assembler files need to have the extension '.asm').  If you have 
used option c. above, you will need to let the dialogue find them 
using the 'Find Existing' button below the dialogue.

To assemble a file with YASM, select the Property Page for the 
file and the select 'Yasm Assembler' in the Tool dialog entry. 
Then click 'Apply' and an additional property page entry will 
appear and enable YASM settings to be established.

**Comment by waruqi** [comment]
没懂，它说必须要命名 vsyasm 只是为了让 vs 能找到吧，所以约定了固定名字。

但 xmake 里面用，跟 vs 又没关系，只要 xmake 只要能找到 yasm.exe 路径，就能调用

难道改成 yasm.exe 直接运行它也会运行不起来么？

**Comment by xq114** [comment]
libx264用nasm就行

https://github.com/microsoft/vcpkg/blob/master/ports/x264/portfile.cmake

yasm本来就是模仿nasm写出来的，而且已经多年没有维护了，需要用到的地方换成nasm更好

**Comment by hh-wu** [comment]
> libx264用nasm就行
> 
> https://github.com/microsoft/vcpkg/blob/master/ports/x264/portfile.cmake
> 
> yasm本来就是模仿nasm写出来的，而且已经多年没有维护了，需要用到的地方换成nasm更好

你说得对，我刚发现这个问题……不过已经弄好了。

**Comment by hh-wu** [comment]
> 没懂，它说必须要命名 vsyasm 只是为了让 vs 能找到吧，所以约定了固定名字。
> 
> 但 xmake 里面用，跟 vs 又没关系，只要 xmake 只要能找到 yasm.exe 路径，就能调用
> 
> 难道改成 yasm.exe 直接运行它也会运行不起来么？

可以的，我测试过了没问题。
