### ISSUE TITLE
若干库的on_test中采用的c++版本过低导致无法通过测试

### ISSUE THREAD

**Issue by jyshaobing** [xmake-io/xmake-repo#4950]
### Xmake 版本

2.8.3

### 操作系统版本和架构

5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

re 依赖于abseil, abseil要求C++17
对于on_test相关的C++版本，是否有依赖的继承机制？
除此之外eigen的on_test中C++的版本也可能有问题

### 期待的结果

修复on_test中c++的版本配置

### 工程配置

clang-16环境无额外配置

### 附加信息和错误日志

![飞书20240816-152517](https://github.com/user-attachments/assets/123fb3b4-4cc5-4f06-b960-04d3fc766a83)

**Comment by star-hengxing** [comment]
这种问题，说明理由直接提个 pr 过来就行
