### ISSUE TITLE
wsl 下安装opencv失败

### ISSUE THREAD

**Issue by m1234n** [xmake-io/xmake-repo#4968]
### Xmake 版本

xmake v2.8.5+20231107

### 操作系统版本和架构

Ubuntu 22.04.3 LTS Wsl2 Win11 

### 描述问题

wsl下直接使用`xmake require`安装opencv失败
> xmake require -f  -vD opencv 

### 期待的结果

正确安装

### 工程配置

```
add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
set_languages("c++17")
add_requires("opencv")

target("Rasterizer")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("$(buildir)/../../")
    add_packages("opencv")
```

### 附加信息和错误日志

finding opencv from xmake ..
checking for xmake::opencv ... opencv 4.10.0
{ 
  links = { 
    "opencv_phase_unwrapping",
    "opencv_surface_matching",
    "opencv_saliency",
    "opencv_wechat_qrcode",
    "opencv_mcc",
    "opencv_face",
    "opencv_img_hash",
    "opencv_videostab",
    "opencv_structured_light",
    "opencv_intensity_transform",
    "opencv_ccalib",
    "opencv_line_descriptor",
    "opencv_stereo",
    "opencv_dnn_objdetect",
    "opencv_dnn_superres",
    "opencv_fuzzy",
    "opencv_hfs",
    "opencv_rapid",
    "opencv_bgsegm",
    "opencv_bioinspired",
    "opencv_rgbd",
    "opencv_dpm",
    "opencv_aruco",
    "opencv_reg",
    "opencv_tracking",
    "opencv_datasets",
    "opencv_xfeatures2d",
    "opencv_shape",
    "opencv_superres",
    "opencv_plot",
    "opencv_quality",
    "opencv_text",
    "opencv_optflow",
    "opencv_ximgproc",
    "opencv_xobjdetect",
    "opencv_xphoto",
    "opencv_stitching",
    "opencv_ml",
    "opencv_photo",
    "opencv_gapi",
    "opencv_objdetect",
    "opencv_highgui",
    "opencv_videoio",
    "opencv_video",
    "opencv_calib3d",
    "opencv_dnn",
    "opencv_features2d",
    "opencv_flann",
    "opencv_imgcodecs",
    "opencv_imgproc",
    "opencv_core",
    "libtiff",
    "libprotobuf",
    "libjpeg-turbo",
    "zlib",
    "libpng",
    "libwebp",
    "quirc",
    "ade" 
  },
  license = "Apache-2.0",
  syslinks = { 
    "pthread",
    "dl" 
  },
  static = true,
  sysincludedirs = { 
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/include/opencv4" 
  },
  linkdirs = { 
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/opencv4/3rdparty" 
  },
  libfiles = { 
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_phase_unwrapping.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_surface_matching.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_saliency.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_wechat_qrcode.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_mcc.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_face.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_img_hash.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_videostab.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_structured_light.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_intensity_transform.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_ccalib.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_line_descriptor.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_stereo.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_dnn_objdetect.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_dnn_superres.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_fuzzy.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_hfs.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_rapid.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_bgsegm.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_bioinspired.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_rgbd.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_dpm.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_aruco.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_reg.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_tracking.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_datasets.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_xfeatures2d.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_shape.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_superres.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_plot.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_quality.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_text.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_optflow.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_ximgproc.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_xobjdetect.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_xphoto.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_stitching.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_ml.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_photo.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_gapi.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_objdetect.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_highgui.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_videoio.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_video.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_calib3d.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_dnn.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_features2d.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_flann.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_imgcodecs.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_imgproc.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_core.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/opencv4/3rdparty/liblibtiff.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/opencv4/3rdparty/liblibprotobuf.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/opencv4/3rdparty/liblibjpeg-turbo.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/opencv4/3rdparty/libzlib.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/opencv4/3rdparty/liblibpng.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/opencv4/3rdparty/liblibwebp.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/opencv4/3rdparty/libquirc.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/opencv4/3rdparty/libade.a",
    "/home/m1234n/.xmake/packages/o/opencv/4.10.0/07fff2ddbc8647d392e888cc2a12d4a4/lib/libopencv_signal.a" 
  },
  version = "4.10.0" 
}

error: ...make/repositories/xmake-repo/packages/o/opencv/xmake.lua:267: method 'has_runtime' is not callable (a nil value)
stack traceback:
    [...make/repositories/xmake-repo/packages/o/opencv/xmake.lua:267]: in function 'script'
    [...dir/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call'
    [...dir/modules/private/action/require/impl/actions/test.lua:41]:
    [.../modules/private/action/require/impl/actions/install.lua:409]:

  => install opencv 4.10.0 .. failed
error: @programdir/core/main.lua:309: @programdir/modules/async/runjobs.lua:320: .../modules/private/action/require/impl/actions/install.lua:471: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:923]:
    [.../modules/private/action/require/impl/actions/install.lua:471]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:330]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/async/runjobs.lua:237]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:923: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:309: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
[err.log](https://github.com/user-attachments/files/16645363/err.log)

**Comment by star-hengxing** [comment]
xmake 2.8.7 引入了新 api `has_runtime`

**Comment by m1234n** [comment]
> xmake 2.8.7 引入了新 api `has_runtime`

谢谢，更新xmake后安装成功了
