### ISSUE TITLE
Request Adding vtk 9.3.1

### ISSUE THREAD

**Issue by wang-mengdi** [xmake-io/xmake-repo#5027]
### Is your feature request related to a problem? Please describe.

I'm trying to use vtkHDFWriter to output adaptive mesh data in my code. HDF5 is a good way to visualize adaptive mesh data for its capability of large and complex data structures.

### Describe the solution you'd like

Support latest vtk version 9.3.1 in https://github.com/xmake-io/xmake-repo/blob/dev/packages/v/vtk/xmake.lua

**Comment by waruqi** [comment]
you can open a pr to update it.

**Comment by star-hengxing** [comment]
Done https://github.com/xmake-io/xmake-repo/pull/5041
