### ISSUE TITLE
Improve cross ci

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake-repo#5141]
> The cross-compiling toolchain is outdated, and musl.cc is no longer maintained😵‍💫. Toward the end of the year, when the Linux ARM CI instance reaches GA, we might consider removing cross-compiling CI. Alternatively, we could use the aarch64-linux-gnu toolchain that comes with Debian/Ubuntu, or we could maintain our own cutting-edge musl cross-compiling toolchain.

_Originally posted by @c8ef in https://github.com/xmake-io/xmake-repo/issues/5090#issuecomment-2320193536_

**Comment by waruqi** [comment]
windows arm ci. https://github.com/xmake-io/xmake-repo/blob/c02fc3aff61a4d1f9a49d901232a0832348f92c6/.github/workflows/windows.yml#L15

**Comment by waruqi** [comment]
https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/#get-started-using-arm-hosted-runners-today

> We expect to begin offering Arm runners for open source projects by the end of the year

**Comment by star-hengxing** [comment]
https://github.com/xmake-io/xmake-repo/actions/runs/10812519041/job/29994350373?pr=5059
Any idea?

**Comment by star-hengxing** [comment]
> https://github.com/xmake-io/xmake-repo/actions/runs/10812519041/job/29994350373?pr=5059 Any idea?

https://github.com/xmake-io/xmake/issues/5639

**Comment by star-hengxing** [comment]
```console
wget https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz
--2024-11-19 00:49:22--  https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz
Resolving developer.arm.com (developer.arm.com)... 23.48.203.147, 23.48.203.146
Connecting to developer.arm.com (developer.arm.com)|23.48.203.147|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz [following]
--2024-11-19 00:49:23--  https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz
Resolving armkeil.blob.core.windows.net (armkeil.blob.core.windows.net)... 20.209.1[5](https://github.com/xmake-io/xmake-repo/actions/runs/11895771005/job/33171952707#step:4:6).139
Connecting to armkeil.blob.core.windows.net (armkeil.blob.core.windows.net)|20.209.15.139|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2024-11-19 00:49:23 ERROR 404: The specified blob does not exist..
```
