### ISSUE TITLE
在docker里面安装opencv失败，method 'has_runtime' is not callable

### ISSUE THREAD

**Issue by naonao-cola** [xmake-io/xmake-repo#5229]
### Xmake Version

2.9.5

### Operating System Version and Architecture

ubuntu:23.04

### Describe Bug

镜像来自这个ubuntu:23.04，
`
FROM ubuntu:23.04

# https://github.com/boostorg/mysql/blob/6d08247bab36da0cb9360f7c932620e167ec390b/tools/docker/build-gcc13.dockerfile#L13
ENV NAO_PATH /home/COLA

WORKDIR $NAO_PATH

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN \
    apt-get update && \
    apt-get --no-install-recommends -y install \
    software-properties-common \
    cmake \
    git \
    iputils-ping \
    gpg \
    curl \
    wget \
    make \
    gpg-agent \
    rar \
    ninja-build \
    unrar \
    xz-utils \
    valgrind \
    libssl-dev \
    ca-certificates \
    gcc-13 \
    7zip \
    unzip \
    g++-13 && \
    ln -s /usr/bin/g++-13 /usr/bin/g++ && \
    ln -s /usr/bin/gcc-13 /usr/bin/gcc && \
    g++ --version

RUN add-apt-repository ppa:xmake-io/xmake && apt-get update && apt-get install -y xmake && \
    git clone https://github.com/naonao-cola/cola.git

RUN cd cola && xmake --root -vD -y

CMD /bin/sh -c "/bin/bash"
`

<img width="1361" alt="449B89C66B445E12CE16E73E7A727779" src="https://github.com/user-attachments/assets/dc86737a-b97d-4ae1-b283-3439fad5ac47">

### Expected Behavior

安装opencv出错，去掉安装包里的第265行到274行，安装成功。且代码编译通过

### Project Configuration

`set_project("Cola")

set_version("0.0.1")
set_languages("c++20")
add_rules("mode.debug", "mode.release","mode.releasedbg")
add_requires("opencv 4.8.x",{system = false,configs={bundled = false,runtimes ="MT"}})
add_requires("eigen 3.4.x",{system = false})

-- set features on different platform
if is_plat("macosx") then
    add_defines("_ENABLE_LIKELY_")
elseif is_plat("linux") then
    add_defines("_ENABLE_LIKELY_")
    add_syslinks("pthread")
end

--自动更新vs解决方案结构
add_rules("plugin.vsxmake.autoupdate")
set_policy("build.cuda.devlink", true)
set_encodings("source:utf-8")

includes(
    "tutorial/xmake.lua"
    --"test/xmake.lua"
)`

### Additional Information and Error Logs

error: ...make/repositories/xmake-repo/packages/o/opencv/xmake.lua:267: method 'has_runtime' is not callable (a nil value)
555.4 stack traceback:
555.4
[...make/repositories/xmake-repo/packages/o/opencv/xmake.lua:267]: in function 'script'
555.4
[...dir/modules/private/action/require/impl/utils/filter.lua:114]: in function 'call'
555.4
[...dir/modules/private/action/require/impl/actions/test.lua:41]:
555.4
[.../modules/private/action/require/impl/actions/install.lua:412]:
555.4
555.4
→ install opencv 4.8.0 .. failed
555.4 error: @programdir/core/main.lua:314:@programdir/core/sandbox/modules/import/core/base/task.lua:65: @programdir/modules/async/runjobs.lua:320:
... /modules/private/action/require/impl/actions/install.lua:474: install failed!
555.4 stack traceback:
555.4
[C]: in function 'error'
555.4
[@programdir/core/base/os.lua:949]:
555.4
[.../modules/private/action/require/impl/actions/install.lua:4747: in function 'catch'
555.4
[@programdir/core/sandbox/modules/try.lua:123]: in function "try'
555.4
[.../modules/private/action/require/impl/actions/install.lua:333]:
555.4
[...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
555.4
[@programdir/modules/async/runjobs.lua:237]

**Comment by star-hengxing** [comment]
`has_runtime` 是 2.8.7 加的接口，更新 xmake 就行
