### ISSUE TITLE
Broken support of OpenMP with GFortran

### ISSUE THREAD

**Issue by jbloino** [xmake-io/xmake-repo#5255]
### Xmake Version

2.9.5

### Operating System Version and Architecture

macOS  Sonoma 14.6.1, Linux debian testing kernel 6.9.10

### Describe Bug

gfortran fails to link the OpenMP library at the final compilation stage, with all references to OpenMP primitives unresolved.
This problem was confirmed on mac OS X arm64 and Linux AMD 64.

### Expected Behavior

The compilation should work

### Project Configuration

xmake.lua
```
add_rules("mode.debug", "mode.release")
add_requires("openmp")

target("test_omp")
    set_kind("binary")
    add_packages("openmp")
    add_files("test_openmp.f90")
```

test_openmp.f90
```
program test_openmp
    integer, external :: omp_get_num_threads

    !$omp parallel
    print '("Number of threads: ",i0)', omp_get_num_threads()
    !$omp end parallel

end program test_openmp
```

### Additional Information and Error Logs

It seems that the problem is in the use of `result.fcldflags = "-fopenmp"` on l.77.
Replacing it with `result.ldflags = "-fopenmp"` fixes the problem (the "shared" case was not tested).

**Comment by waruqi** [comment]
try this patch. https://github.com/xmake-io/xmake/pull/5644

**Comment by jbloino** [comment]
Thank you!  After having updated with, `xmake update https://github.com/xmake-io/xmake.git#ldflags`, the OpenMP package now works with GFortran on both Linux and Mac ARM.
