### ISSUE TITLE
我需要一个新的库 libsvgtiny

### ISSUE THREAD

**Issue by xflcx1991** [xmake-io/xmake-repo#5377]
### 你在什么场景下需要该功能？

跨语言调用，需要纯c的svg库

### 描述可能的解决方案

为xrepo打包一个新库 Libsvgtiny
这是主页 https://www.netsurf-browser.org/projects/libsvgtiny/
他们没有用github

### 描述你认为的候选方案

无

### 其他信息

无

**Comment by star-hengxing** [comment]
https://archlinux.org/packages/extra/x86_64/libsvgtiny

- [ ] libdom 
- [ ] libwapcaplet
- [ ] libsvgtiny
