### ISSUE TITLE
Installing zmqpb 0.10.2 fails because of protobuf rules error

### ISSUE THREAD

**Issue by SFGrenade** [xmake-io/xmake-repo#5407]
### Xmake Version

v2.9.5 (commit: d30de52e)

### Operating System Version and Architecture

github CIs: ubuntu-latest, macos-13 & windows-latest

### Describe Bug

when installing dependencies of my project https://github.com/SFGrenade/System_Simulator the CI pipelines all fail at the step to install zmqpb with the message `error: @programdir\core\main.lua:329: @programdir\core\project\project.lua:920: @programdir\rules\protobuf\proto.lua:70: attempt to index a nil value (local 'sourcebatch')`

### Expected Behavior

i'd expect it to install just fine

### Project Configuration

https://github.com/SFGrenade/System_Simulator/blob/master/xmake.lua

https://github.com/SFGrenade/System_Simulator/blob/master/network_messages/xmake.lua

### Additional Information and Error Logs

https://github.com/SFGrenade/System_Simulator/actions/runs/11165821280

https://github.com/SFGrenade/System_Simulator/actions/runs/11165821270

https://github.com/SFGrenade/System_Simulator/actions/runs/11165821263

**Comment by waruqi** [comment]
try `xmake update -s dev`

**Comment by SFGrenade** [comment]
that made it work on macos:  
[Linux - apparently a bunch of portaudio undefined references](https://github.com/SFGrenade/System_Simulator/actions/runs/11176476090)  
[MacOSX - working now](https://github.com/SFGrenade/System_Simulator/actions/runs/11176476091)  
[Windows - still has the same `@programdir\rules\protobuf\proto.lua:70: attempt to index a nil value (local 'sourcebatch')`](https://github.com/SFGrenade/System_Simulator/actions/runs/11176476121)

**Comment by waruqi** [comment]
> windows

you can disable action cache and rerun it again. you still use old xmake.

> linux 

it's another issue. this issue has been solved.

**Comment by SFGrenade** [comment]
still errors out in the individual jobs that are already done: https://github.com/SFGrenade/System_Simulator/actions/runs/11178433818

**Comment by waruqi** [comment]
rerun ci again.

**Comment by SFGrenade** [comment]
from the ones already finished it seem to be good! (https://github.com/SFGrenade/System_Simulator/actions/runs/11178433818)
