### ISSUE TITLE
boost: add cmake support

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake-repo#5437]
### Is your feature request related to a problem? Please describe.

- Easy to support ios/android/wasm.
- Improve asan/debug build. https://github.com/xmake-io/xmake-repo/issues/4503

```lua
set_urls("https://github.com/boostorg/boost/releases/download/boost-$(version)/boost-$(version)-cmake.7z")
add_versions("1.86.0", "ee6e0793b5ec7d13e7181ec05d3b1aaa23615947295080e4b9930324488e078f")
```

### Describe the solution you'd like

Create new package `boost-cmake` or use `on_source` + `add_configs("cmake", {description = "Use cmake buildsystem", default = false, type = "boolean"})`

**Comment by SirLynix** [comment]
why not default to cmake for newer builds?

**Comment by star-hengxing** [comment]
I'm not sure if using cmake directly would break downstream users.
Msys2 has switched to cmake, but someone reported a bug https://github.com/msys2/MINGW-packages/issues/13608#issuecomment-2395075927

It's fine to build with cmake by default, but it's a good idea to leave a warning to remind the user that they can fallback to b2 and try building again.

**Comment by waruqi** [comment]
we can attempt to add `add_configs("cmake"` and set it to true (default) + warning first.

if it will be broken, we can set it(false) to fallback to b2.
