### ISSUE TITLE
packages with arch "native" won't show up in xrepo.xmake.io

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#5487]
### Xmake 版本

2.9.5

### 操作系统版本和架构

Windows 11

### 描述问题

![image](https://github.com/user-attachments/assets/5574d93b-f4a2-4740-bb51-3c632b9e3cd2)
![image](https://github.com/user-attachments/assets/e30a9eec-a001-40f0-be07-2d087a8407d8)
如图，pybind11支持windows|native，但在官方文档中却没有windows上的条目，容易产生误导以为不支持windows

### 期待的结果

scripts/packages.lua探测package的时候除了检测固定arch list之外还检测是否是native/cross

### 工程配置

/

### 附加信息和错误日志

/

**Comment by waruqi** [comment]
应该可以了 https://xrepo.xmake.io/#/packages/windows?id=pybind11-windows
