### ISSUE TITLE
Fail to install mysql

### ISSUE THREAD

**Issue by TabNahida** [xmake-io/xmake-repo#5883]
### Xmake Version

2.9.6

### Operating System Version and Architecture

Windows 11 23H2

### Describe Bug

I cannot install ``mysql`` in xrepo. I first found in ``add_requires("ormpp", {configs = {mysql = true}})``, and I tried to install mysql independently.

### Expected Behavior

Correctly install ``mysql`` and ``add_requires("ormpp", {configs = {mysql = true}})``

### Project Configuration

```bash
xrepo install mysql
```

### Additional Information and Error Logs

[mysql_fail.txt](https://github.com/user-attachments/files/17969426/mysql_fail.txt)

**Comment by star-hengxing** [comment]
切换到 ninja 构建试试，开启 policy `package.cmake_generator.ninja`

**Comment by TabNahida** [comment]
> 切换到 ninja 构建试试，开启 policy `package.cmake_generator.ninja`

OK, I succeed
