### ISSUE TITLE
求助增加 mongo-cxx-driver

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake-repo#589]
我在增加 mongo-cxx-drivier 时，windows下始终出错，无法成功。
但是，我用 xmake l scripts/test.lua -vD mongo-cxx-driver 里生成的 cmake 指令（见下），到 mongo-cxx-driver 目录下手工建立build子目录，然后在子目录下执行 cmake 配置后，在执行 "cmake --build ." 却能够编译成功

本地测试显示的cmake指令：
cmake .. -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_FLAGS="/Zc:__cplusplus" -DENABLE_UNINSTALL=OFF -DBUILD_VERSION="3.6.5" -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_CXX_FLAGS_DEBUG="/MT" -DCMAKE_CXX_FLAGS_RELEASE="/MT" -DCMAKE_C_FLAGS_DEBUG="/MT" -DCMAKE_C_FLAGS_RELEASE="/MT" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_PREFIX_PATH="D:\xmake\.xmake\packages\m\mongo-c-driver\1.19.0\76581d9c60ab4ea1be4ca6420065422b"

monggo-cxx-driver 的 xmake.lua 如下：
package("mongo-cxx-driver")

    set_homepage("http://mongoc.org/")
    set_description("The MongoDB C++ Driver.")
    set_license("Apache-2.0")

    add_urls("https://github.com/mongodb/mongo-cxx-driver/archive/r$(version).zip",
             "https://github.com/mongodb/mongo-cxx-driver.git")
    add_versions("3.6.5", "9a00ee0642b00bd8104e75f62f4494f778ee4e50cf0a79502796efa0e9d55ae0")

    add_deps("mongo-c-driver")

    on_install("windows", "linux", "macosx", function (package)
        local configs = {"-DCMAKE_CXX_STANDARD=17", 
                         '-DCMAKE_CXX_FLAGS="/Zc:__cplusplus"',
                         "-DENABLE_UNINSTALL=OFF",
                         "-DBUILD_SHARED_AND_STATIC_LIBS=OFF"
                         }
        table.insert(configs, "-DBUILD_VERSION=" .. package:version())
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        import("package.tools.cmake").install(package, configs)        
    end)

    on_test(function (package)
        -- assert(package:has_cfuncs("mongoc_init", {includes = "mongoc/mongoc.h"}))
    end)

**Comment by waruqi** [comment]
你先自己研究下吧，最近没啥时间看这个，可以自己打些patch 什么的。
