### ISSUE TITLE
Add `xrepo info <package>` test

### ISSUE THREAD

**Issue by Chi-EEE** [xmake-io/xmake-repo#5913]
### Is your feature request related to a problem? Please describe.

I'm trying to get the list of configs for the packages but errors show when I run `xrepo info` on some of the packages

### Describe the solution you'd like

Add `xrepo info <package>` test to verify that the command works

### Additional context

https://github.com/xmake-io/xmake-repo/pull/5910, https://github.com/xmake-io/xmake-repo/pull/5911, https://github.com/xmake-io/xmake-repo/pull/5921

```lua
package("package_with_broken_on_load")
    add_configs("hide_existing_package_error", {default = is_plat("windows"), type = "boolean"})

    if on_check then
        on_check(function (package)
            if package:is_plat("linux") then
                raise("This package does not support Linux for ... reasons.")
            end
        end)
    end

    on_load(function (package)
        if package:config("hide_existing_package_error") then -- CI does not check this
            add_syslinks("advapi32")
            raise("This package is broken on purpose.")
        end
    end)

    on_install(function (package)
    end)

    on_test(function (package)
    end)
```

CI is green but there is an error:
![image](https://github.com/user-attachments/assets/bb03c430-806d-4650-81cb-2300b54dba5a)

**Comment by Chi-EEE** [comment]
I mean add a test which uses `xrepo info` to test if the on_load method of the package works and if it fails, we know that using `xrepo info` does not work on the package and its information is not displayed

**Comment by Chi-EEE** [comment]
![itstool](https://github.com/user-attachments/assets/1dc5fd9d-2765-4174-82d3-91c150ff49c8)
![node-addon-api](https://github.com/user-attachments/assets/0213a451-80a9-4242-8615-6128078e7db1)
![xerces-c](https://github.com/user-attachments/assets/ae4e01a5-d656-4fe5-8f0c-c0503796ad90)

**Comment by waruqi** [comment]
you need set package config

```console
ruki-2:tmp ruki$ xrepo info -k shared libxml2[python,iconv]
The package info of project:
    require(cmake):
      -> description: A cross-platform family of tool designed to build, test and package softw
are
      -> version: 3.30.2
```

**Comment by Chi-EEE** [comment]
This request is unnecessary as the test script already tests on_load
