### ISSUE TITLE
希望能够添加 微软的cppwinrt库

### ISSUE THREAD

**Issue by cngege** [xmake-io/xmake-repo#6048]
### 你在什么场景下需要该功能？

仓库地址：https://github.com/microsoft/cppwinrt
WinRT 是 Windows 操作系统的一个组件，它提供了一种统一的方式来构建和调用应用程序编程接口。它主要用于构建UWP应用程序，使得应用可以在多种 Windows 设备上运行。

### 描述可能的解决方案

希望能够将此库添加到xrepo仓库中，使得xmake能够直接使用它

**Comment by star-hengxing** [comment]
应该已经包含在 windows sdk 里吧 `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0`

**Comment by cngege** [comment]
> 应该已经包含在 windows sdk 里吧 `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0`

确实，但是SDK中只有头文件，没有包含lib库文件

**Comment by cngege** [comment]
> 应该已经包含在 windows sdk 里吧 `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0`

- 刚刚研究明白，现在新版本使用winrt不需要cppwinrt.lib了，直接用onecore.lib就行，这玩意是系统库，可以直接链接完活
