### ISSUE TITLE
xmake can found "main" includes but not "subincludes" on imgui

### ISSUE THREAD

**Issue by fgsoftware1** [xmake-io/xmake-repo#6085]
### Xmake Version

2.9.7

### Operating System Version and Architecture

Windows 10

### Describe Bug

xmake can found ```imgui.h``` but not backend includes

### Expected Behavior

compile succefully

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")
add_requires("spdlog", "glad", "glfw")
add_requires("imgui", {opengl3, glfw})

add_defines("GLFW_INCLUDE_NONE")

set_languages("cxx17")

if is_mode("debug")
then
    set_optimize("none")
else 
    set_optimize("fastest")
end 

target("fge")
    set_kind("static")
    add_packages("spdlog", "glad", "glfw")

target("Sandbox")
    set_kind("binary")
    add_packages("fge", "glad", "glfw", "imgui")
    add_files("Sandbox.cpp")
```

### Additional Information and Error Logs

```
 Executing task: xmake build Sandbox 

[ 50%]: compiling.release Sandbox.cpp
error: Sandbox.cpp
Sandbox.cpp(4): fatal error C1083: Não é possível abrir arquivo incluir: 'imgui_impl_glfw.h': No such file or directory
```

**Comment by star-hengxing** [comment]
`add_requires("imgui", {opengl3, glfw})` -> `add_requires("imgui[glfw]")`

**Comment by SirLynix** [comment]
you didn't enable the backend in the right way, what you're doing is basically passing two nils values as a config to add_requires, which is the same as passing an empty table.
try
```lua
add_requires("imgui", { configs = { opengl3 = true, glfw = true })
```
or even simpler
```lua
add_requires("imgui[opengl3, glfw]")
```

**Comment by fgsoftware1** [comment]
> you didn't enable the backend in the right way, what you're doing is basically passing two nils values as a config to add_requires, which is the same as passing an empty table. try
> 
> ```lua
> add_requires("imgui", { configs = { opengl3 = true, glfw = true })
> ```
> 
> or even simpler
> 
> ```lua
> add_requires("imgui[opengl3, glfw]")
> ```

first works and second not and you missing a closing bracket at the end :)
