### ISSUE TITLE
Tell xmake to use fork instead of this repo?

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake-repo#64]
How do we tell xmake to use our forks of this repo *instead* of this repo?

 `add_repositories` works, except in the case where we are altering an existing package. In that case it seems that this main repo still has precedence.

**Comment by waruqi** [comment]
use add_repositories or `xmake repo --add myrepo url branch`, you can see https://xmake.io/#/package/remote_package?id=using-self-built-private-package-repository

**Comment by paul-reilly** [comment]
Unless I did something wrong, this `xmake-repo` repository still has priority/precedence when using `add_repositories`. Which is a problem if we are trying to change package that exists in the `xmake-repo` repository.

I noticed this when changing the luajit package. Changes were not detected so I had to temporarily create a differently named package, in my case `luajit-devpackage`.

**Comment by waruqi** [comment]
It works for me. The packages in the repo set with add_repositories will be used first.

you can run `xmake repo -l` to look at their order. 

find order:  local repo (myrepo) -> global repo (xmake-repo) -> (builtin repo)

```bash
$ xmake repo -l
local repositories:
    my-repo /Users/ruki/projects/personal/xmake-repo

global repositories:
    xmake-repo https://gitee.com/tboox/xmake-repo.git master
    builtin-repo /Users/ruki/.local/share/xmake/repository
```

**Comment by paul-reilly** [comment]
Ahh, that's good to know. It must have been how I was refreshing the project, because it initially used the luajit from this repo.

Is the correct way to run `xmake require --force` or should `xmake --rebuild` trigger this as well?

**Comment by waruqi** [comment]
If you have installed luajit before, you need to uninstall it first, and use `xmake f -c` to force reinstall it.

```console
xmake require --uninstall luajit
xmake f -c
```

**Comment by paul-reilly** [comment]
Ahh okay. This makes perfect sense now... so it uses package name + version and checks `installed -> additional repos -> main repo`.

I'd just like to say that you've done fantastic work here creating xmake! It's great that you are unifying use of different package managers and build systems under one roof. Thanks.
