### ISSUE TITLE
Trouble creating package that depends on another package

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake-repo#68]
I am trying to create a LuaSocket package. I have started on an [xmake build script](https://github.com/paul-reilly/luasocket/blob/xmake/xmake.lua) in a fork. I know I can build a package using the existing MSVC etc build scripts too.

Here is the project I am creating the LuaSocket package with locally, which pulls my fork:

https://github.com/paul-reilly/xmake-luasocket-package-test

The issue is that when building the simple test project there are `unresolved external symbol` errors because the LuaJIT libs cannot be found.

How do I deal with this issue? Can I find out the location of libs of other packages and the working directory of the build system at various points?

Thanks for any pointers.

**Comment by waruqi** [comment]
https://github.com/paul-reilly/luasocket/blob/cc1175f117aa57693228782a96756d8a235aae45/xmake.lua#L4

```lua
add_requires("luajit", { config = { kind = "shared" }})
```

It should be `configs = {shared = true}`

```lua
    add_packages("luajit", { kind = "shared"})
```

no this config `{kind = "shared"}`, only `add_packages("luajit")`

https://github.com/paul-reilly/xmake-luasocket-package-test/blob/0387a137c7ba2d219bcd2bc0bf57e6004ede8e9f/xmake.lua#L5

You have already added add_requires("luajit") to luasocket, there is no need to add it again

**Comment by waruqi** [comment]
>     set_basename("socket/core")

it is only used to set file base name, please use set_targetdir() to set the target directory.

https://github.com/waruqi/luasocket/blob/175ea32d9a3234893524462b478a7cc53239866b/xmake.lua#L47

```lua
target("luasocket")
   -- ...
   on_install(function(package)          <---------  is target, not package...
        cprint("${red}$(targetdir)")
        local prefix = is_host("linux") and "/lib" or "/"
        os.cp(package:targetdir() .. prefix .. "socket", package:installdir() .. "/socket")
        os.cp(package:targetdir() .. prefix .. "mime", package:installdir() .. "/mime")
        os.cp("src/*.lua", package:installdir())
        os.cp("src/luasocket.h", package:installdir() .. "/include")
        os.cp("src/compat.h", package:installdir() .. "/include")
    end)
```

This is target, `on_install(function(target) `,   not package()

**Comment by waruqi** [comment]
https://github.com/waruqi/luasocket/blob/175ea32d9a3234893524462b478a7cc53239866b/xmake.lua#L49-L51

??  We need not copy them, `package()/import("package.tools.xmake").install(package)` will install all targets file to the package install directory.

**Comment by waruqi** [comment]
https://github.com/waruqi/luasocket/blob/175ea32d9a3234893524462b478a7cc53239866b/xmake.lua#L52-L54

>         os.cp("src/*.lua", package:installdir())
        os.cp("src/luasocket.h", package:installdir() .. "/include")
        os.cp("src/compat.h", package:installdir() .. "/include")

Please use add_headerfiles("src/luasocket.h") and add_installfiles("src/*.lua")

**Comment by waruqi** [comment]
https://github.com/waruqi/luasocket/blob/xmake/xmake.lua

Please test the compilation and installation successfully locally before integrating into `package()`

```console
cd luasocket
xmake
xmake install -o /tmp/installdir
tree /tmp/installdir
```

**Comment by paul-reilly** [comment]
Thanks very much for the review, this is very helpful!

I have implemented most of the changes and moved the luasocket build script to the local package dir...

https://github.com/paul-reilly/xmake-luasocket-package-test

At the moment luajit is not building as a shared library (can't open luajit.lib when linking luajit.exe), so I have stuck with static linking. I have also left the target dirs and names as default and have removed the `on_install` completely to eliminate sources of potential errors.

>You have already added add_requires("luajit") to luasocket, there is no need to add it again

I added it because without it, the luajit headers are not found when building the test exe. Even with the changes and requiring luajit the build of the test exe is failing with linker errors because the luajit lib is not found, which are the same errors I was originally getting.

**Comment by waruqi** [comment]
> At the moment luajit is not building as a shared library (can't open luajit.lib when linking luajit.exe)

maybe need define -DLUA_BUILD_AS_DLL to export functions in package("luajit")/xmake-repo, luajit.lib will be generated.

**Comment by waruqi** [comment]
You can run `xmake repo -u` and try this patches again. https://github.com/paul-reilly/luasocket/compare/master...waruqi:master

**Comment by paul-reilly** [comment]
Thanks, that's it working with a static build now! It seems there is still an issue with the shared luajit target that I can see when trying a minimal luajit hello world:

```
add_rules("mode.debug", "mode.release")

--add_requires("luajit") -- <-- this works!
add_requires("luajit", { configs = { shared = true }}) -- <-- "Cannot open include file: 'lua.hpp'" on build

target("luajit-test")
    set_kind("binary")
    add_packages("luajit")
    add_files("src/*.cpp")
    
```
```cpp
#include <lua.hpp>

int main(int argc, char* argv[])
{
    auto L = luaL_newstate();
    luaL_openlibs(L);
    luaL_dostring(L, "print('hello, lua world!')");
    lua_close(L);
}
```

Although even when I'm deleting the local .xmake dir, the build dir, the lua\* cache dir and the lua\* package dirs it's not attempting to install the package when it's shared.

**Comment by waruqi** [comment]
It works for me. Please run `xmake -rv` and let me see the output.

```console
ruki-2:luajit ruki$ xmake -rv
[ 50%]: ccache compiling.release src/main.cpp
/usr/local/bin/ccache /usr/bin/xcrun -sdk macosx clang -c -I/Users/ruki/.xmake/packages/l/luajit/2.1.0-beta3/d3dc6b2df2a840f19913d983085569db/include/luajit -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -o build/.objs/luajit-test/macosx/x86_64/release/src/main.cpp.o src/main.cpp
[ 75%]: linking.release luajit-test
"/usr/bin/xcrun -sdk macosx clang++" -o build/macosx/x86_64/release/luajit-test build/.objs/luajit-test/macosx/x86_64/release/src/main.cpp.o -L/Users/ruki/.xmake/packages/l/luajit/2.1.0-beta3/d3dc6b2df2a840f19913d983085569db/lib -lluajit -ldl -arch x86_64 -mmacosx-version-min=10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -stdlib=libc++ -lz
[100%]: build ok!
```


```console
ruki-2:luajit ruki$ ls -l /Users/ruki/.xmake/packages/l/luajit/2.1.0-beta3/d3dc6b2df2a840f19913d983085569db/include/luajit/lua.hpp
-rw-r--r--  1 ruki  staff  135  5  2  2017 /Users/ruki/.xmake/packages/l/luajit/2.1.0-beta3/d3dc6b2df2a840f19913d983085569db/include/luajit/lua.hpp
```

**Comment by paul-reilly** [comment]
Of course. Here's a static build, followed by changing from static to shared in xmake.lua and an `xmake -rv`:
```
➜  luajit-test xmake -rv
checking for the Microsoft Visual Studio (x64) version ... 2019
in xmake-repo:
please input: y (y/n)
  => install luajit 2.1.0-beta3 .. ok
27.29110\bin\HostX64\x64\cl.exe ... ok
checking for the flags (-Ox -fp:fast) ... ok
checking for the ccache ... no
[ 50%]: compiling.release src\main.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\cl.exe" -c -Ox -fp:fast -IC:\Users\paul-\AppData\Local\.xmake\packages\l\luajit\2.1.0-beta3\d6b9fbbaa7fb4aafacfea8d355da3e80\include\luajit -nologo -Fobuild\.objs\luajit-test\windows\x64\release\src\main.cpp.obj src\main.cpp
checking for the flags (/sourceDependencies C:\Users\paul-\AppData\Local\Temp\.xmake\200916\_2B85CEA7C0944A408A8DA2C681044680.json) ... ok
[ 75%]: linking.release luajit-test.exe
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\link.exe" /opt:ref /opt:icf /ltcg -libpath:C:\Users\paul-\AppData\Local\.xmake\packages\l\luajit\2.1.0-beta3\d6b9fbbaa7fb4aafacfea8d355da3e80\lib luajit.lib -nologo -dynamicbase -nxcompat -machine:x64 -out:build\windows\x64\release\luajit-test.exe build\.objs\luajit-test\windows\x64\release\src\main.cpp.obj
[100%]: build ok!
➜  luajit-test xmake run
hello, lua world!
➜  luajit-test "changing shared = 'false' to 'true'"
changing shared = 'false' to 'true'
➜  luajit-test "changed"
changed
➜  luajit-test xmake -rv
checking for the Microsoft Visual Studio (x64) version ... 2019
checking for the C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\cl.exe ... ok
checking for the flags (-Ox -fp:fast) ... ok
checking for the ccache ... no
[ 50%]: compiling.release src\main.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\cl.exe" -c -Ox -fp:fast -IC:\dev\tools\vcpkg\installed\x64-windows\include 
-nologo -Fobuild\.objs\luajit-test\windows\x64\release\src\main.cpp.obj src\main.cpp
checking for the flags (/sourceDependencies C:\Users\paul-\AppData\Local\Temp\.xmake\200916\_2E59EC5D17634E708E456876170D54F0.json) ... ok
error: main.cpp
src\main.cpp(1): fatal error C1083: Cannot open include file: 'lua.hpp': No such file or directory
```

**Comment by waruqi** [comment]
➜  luajit-test "changing shared = 'false' to 'true'"
changing shared = 'false' to 'true'
➜  luajit-test "changed"
changed


Please run `xmake f -c` to force reinstall luajit with shared first



➜  luajit-test xmake -rv

**Comment by paul-reilly** [comment]
This is the result. It doesn't trigger a rebuild, I need to delete the existing cache and package for that to happen...
```
➜  luajit-test xmake f -cvD
checking for the cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\cl.exe
checking for the Microsoft Visual Studio (x64) version ... 2019
checking for the dmd ... no
checking for the ldc2 ... no
checking for the gdc ... no
checking for the unzip ... ok
checking for the git ... ok
checking for the gzip ... no
checking for the 7z ... ok
checking for the ping ... ok
pinging for the host(gitlab.com) ... 18 ms
pinging for the host(github.com) ... 28 ms
pinging for the host(gitee.com) ... 293 ms
finding luajit from xmake ..
checking for the xmake::luajit ... no
finding luajit from vcpkg ..
checking for the vcpkg directory ... C:\dev\tools\vcpkg
checking for the luajit ... 2.0.5-3
configure
{
    mode = release
    arch = x64
    debugger = windbgx
    proxy_pac = pac.lua
    ccache = true
    host = windows
    clean = true
    plat = windows
    theme = default
    vcpkg = C:\dev\tools\vcpkg
    kind = static
    buildir = build
    vs = 2019
    ndk_stdcxx = true
}
➜  luajit-test xmake -rv
checking for the link.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\cl.exe ... ok
checking for the flags (-Ox -fp:fast) ... ok
checking for the ccache ... no
[ 50%]: compiling.release src\main.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\cl.exe" -c -Ox -fp:fast -IC:\dev\tools\vcpkg\installed\x64-windows\include -nologo -Fobuild\.objs\luajit-test\windows\x64\release\src\main.cpp.obj src\main.cpp
checking for the flags (/sourceDependencies C:\Users\paul-\AppData\Local\Temp\.xmake\200916\_7310F89DF90E490081619174D5C22B70.json) ... ok
error: main.cpp
src\main.cpp(1): fatal error C1083: Cannot open include file: 'lua.hpp': No such file or directory

➜  luajit-test
```

**Comment by paul-reilly** [comment]
Actually a rebuild of the package is never retriggered as long as `shared = true` in the test app build file. Even if I delete:

- build dir
- local .xmake dir
- global .xmake cache luajit dir
- global .xmake package luajit dir

?

**Comment by waruqi** [comment]
I use your minimal test example to test and it works fine.

![Snip20200916_157](https://user-images.githubusercontent.com/151335/93305899-bc08ca00-f831-11ea-8bf0-f657ed649cc5.png)

The only problem encountered was during the installation of luajit, the execution of the luajit command in on_test failed. This is because the installdir/lib/luajit.dll path is not added to the PATH. After I fixed the problem, I re-run `xmake repo -u` and then execute `xmake f -c -vD` and `xmake`. It can be compiled normally.

```lua
add_requires("luajit", { configs = { shared = true }}) 

target("luajit-test")
    set_kind("binary")
    add_packages("luajit")
    add_files("src/*.cpp")
```

```c
#include <lua.hpp>

int main(int argc, char* argv[])
{
    auto L = luaL_newstate();
    luaL_openlibs(L);
    luaL_dostring(L, "print('hello, lua world!')");
    lua_close(L);
}
```

**Comment by waruqi** [comment]
> checking for the xmake::luajit ... no
finding luajit from vcpkg ..
checking for the vcpkg directory ... C:\dev\tools\vcpkg
checking for the luajit ... 2.0.5-3

I saw you log, luajit 2.0.5-3?  why not 2.1.0-beta3? 

Maybe xmake detected the luajit you installed on the system? 

Please set  `add_requires("luajit", { system = false, configs = { shared = true }})`, use system = false to disable detect the system luajit.

**Comment by paul-reilly** [comment]
Yes, you are correct!

It was using luajit from vcpkg! I don't have the static version, which explains why only the shared is failing. The missing include is because vcpkg has `luajit/lua.hpp` while xmake has `lua.hpp`. This explains why the vcpkg include dir was in the compile command too.

Thanks again for sticking with it!
