### ISSUE TITLE
是否可以通过gitee镜像下载库

### ISSUE THREAD

**Issue by klarkxy** [xmake-io/xmake-repo#696]
### 你在什么场景下需要该功能？

网络不稳定git clone github上的库会失败

### 描述可能的解决方案

增加一个换源的命令，换到gitee上，或者通过hub.fastgit.org上拉取

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by waruqi** [comment]
见 https://xmake.io/#/zh-cn/package/remote_package?id=%e8%ae%be%e7%bd%ae%e4%bb%a3%e7%90%86

**Comment by xq114** [comment]
这里文档有一点问题，windows上pac.lua的默认位置在~/AppData/Local/.xmake/pac.lua

**Comment by waruqi** [comment]
> 这里文档有一点问题，windows上pac.lua的默认位置在~/AppData/Local/.xmake/pac.lua

只是

**Comment by xq114** [comment]
> > 这里文档有一点问题，windows上pac.lua的默认位置在~/AppData/Local/.xmake/pac.lua
> 
> 只是文档没说清楚 ~/.xmake/pac.lua 在 xmake 里就是对应 appdata/local 这个路径，内部会自动转
> 
> `~` 在 xmake 中处理成跨平台的 home 路径获取，文档里面我直接提了 xmake 里面的路径表述，回头可以完善下文档
> 
> 用户也可以直接用 xmake l path.absolute '~' 看实际的路径位置

我还是第一次知道。。不过这么表示，不太好吧，大部分跨平台的CLI工具在windows上和linux上~都是直接指向用户的home文件夹的，powershell和cmd里面cd ~也是直接进入home文件夹，而不会进AppData/Local。这么约定非常容易引起误解，把~换成$(globaldir)这类的更能避免混淆，文档说明一下globaldir在linux上是home在windows上是AppData/Local

**Comment by waruqi** [comment]
> > > 这里文档有一点问题，windows上pac.lua的默认位置在~/AppData/Local/.xmake/pac.lua
> > 
> > 
> > 只是文档没说清楚 ~/.xmake/pac.lua 在 xmake 里就是对应 appdata/local 这个路径，内部会自动转
> > `~` 在 xmake 中处理成跨平台的 home 路径获取，文档里面我直接提了 xmake 里面的路径表述，回头可以完善下文档
> > 用户也可以直接用 xmake l path.absolute '~' 看实际的路径位置
> 
> 我还是第一次知道。。不过这么表示，不太好吧，大部分跨平台的CLI工具在windows上和linux上~都是直接指向用户的home文件夹的，powershell里面`cd ~`也是直接进入home文件夹，而不会进AppData/Local。这么约定非常容易引起误解，把`~`换成$(globaldir)这类的更能避免混淆，文档说明一下globaldir在linux上是home在windows上是AppData/Local

跟 globaldir 不一样，~ 就是 xmake 里面的 home 规范，globaldir 只是恰好在 ~/.xmake 下面

linux和win下 ~ 也是终端shell转义的到 home ，系统本身不支持这个写法

而 xmake 相当于一个内部隔离的沙盒转义，只要是 xmake 里面使用 home ，win上默认就是 localappdata  就跟 msys2 的 home 跟 cygwin 的 home ，都是各种约定的沙盒路径而已，都是各自的

如果有要完全访问其他终端系统的外部home，可以自己os.getenv 取 home 变量，但是 xmake 默认不会去依赖外面的 home，否则 msys2和 cygwin还有cmd下运行 xmake ，存储的 home 路径都各不相同，会出各种问题

xmake 要保证完全的一致性，不管在哪个终端环境和subsystem下运行。

而用 ~ ，只是为了方便路径操作，因为很多场合，要做路径透传和路径变换，拼接等等，用约定规范后的 ~ 处理，会非常方便简洁，而不是一堆的 homedir 取变量拼

**Comment by waruqi** [comment]
~ 是终端的东西，实际传入被调用的程序时候已经被转义到实际的路径，所以不会关心兼容性问题，

如果 ~ 搞成对外部终端的依赖，那反而各种不兼容了，ps, cygwin, msys2, cmd 下的 ~ 可以看下 基本都不一样, cmd 还不一定支持这么写
