### ISSUE TITLE
官方库只支持 debian 系 Linux 发布版吗

### ISSUE THREAD

**Issue by leaveye** [xmake-io/xmake-repo#724]
看到 libxv 包代码中对 Linux 平台的依赖里，使用

```lua
add_extsources("apt::libxv-dev")
```

非 apt 的发布版该怎么使用 `xrepo` ？比如 ArchLinux 。

**Comment by waruqi** [comment]
> 看到 libxv 包代码中对 Linux 平台的依赖里，使用
> 
> ```lua
> add_extsources("apt::libxv-dev")
> ```
> 
> 非 apt 的发布版该怎么使用 `xrepo` ？比如 ArchLinux 。

这不是依赖，官方库的包，只需要 xrepo install libxv 就能安装。

add_extsources 仅仅只是用于，xrepo install 和  xmake.lua/add_requires 集成安装 libxv 过程中，优先对系统 libxv 库的探测改进，。

也就是说，如果配置了 add_extsources ，那么 xmake / xrepo 会优先从 apt 中检测包源，如果系统上用户已经安装它，就会直接使用这个包，没必要额外安装了，如果还是检测不到，再走 官方仓库包安装。

如果，不想走官方包源安装，你可以自己指定  xrepo install conan::libxv vcpkg::libxv brew::libxv pacman::libxv 等各种其他包源安装。。文档有详细描述，仔细看下 https://xmake.io/#/zh-cn/package/remote_package?id=%e7%ac%ac%e4%b8%89%e6%96%b9%e4%be%9d%e8%b5%96%e5%8c%85%e5%ae%89%e8%a3%85

**Comment by leaveye** [comment]
响应好快，正在翻文档，刚好看到了这个命令的说明，才明白这不是必需依赖而是尝试策略。准备回来关问题，发现已经回复了。赞一个。
