### ISSUE TITLE
使用 cmake tool 编译 android armv7 架构时出错 

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake-repo#73]
xmake 2.3.7

尝试添加flatbuffers，但发现无法编译android armv7版本（armv8可以）。经查，发现xmake 的cmake工具在编译armv7时，给cmake的参数 “-DANDROID_ABI=armv7”错误，应该是 “-DANDROID_ABI=armeabi-v7a”，导致无法编译。（手工讲 xmake 生成的 cmake 编译命令里的 armv7 改成 armeabi-v7a 后可以顺利编译）

使用的xmake.lua如下：
package("flatbuffers")

    set_homepage("https://github.com/google/flatbuffers")
    set_description("FlatBuffers is a cross platform serialization library architected for maximum memory efficiency.")

    add_urls("https://github.com/google/flatbuffers.git")

    add_deps("cmake")

    on_load(function (package)
        if is_plat("windows", "linux", "macosx") then
            package:addenv("PATH", "bin")
        end
    end)

    on_install(function(package)
        local configs = {"-DFLATBUFFERS_BUILD_TESTS=OFF"}
        if is_plat("android", "iphoneos") then
            table.insert(configs, "-DFLATBUFFERS_BUILD_FLATC=OFF")
            table.insert(configs, "-DFLATBUFFERS_BUILD_FLATHASH=OFF")
        end
        import("package.tools.cmake").install(package, configs)
        if is_plat("macosx", "linux") then
            os.cp("build_*/flatc", package:installdir("bin"))
            os.cp("build_*/flathash", package:installdir("bin"))
        elseif is_plat("windows") then
            os.cp("build_*/flatc.exe", package:installdir("bin"))
            os.cp("build_*/flathash.exe", package:installdir("bin"))
        end
    end)

    on_test(function(package)
    end)

**Comment by fasiondog** [comment]
补充，上面的示例也无法编译 iphone 的版本

**Comment by waruqi** [comment]
是不是你的配置不对 或者缓存了？加 -c 清下试试呢

最近几个版本 android 默认都是 armeabi-v7a了 

https://github.com/xmake-io/xmake/blob/8184f42f9b96b5c0fdedc7b1161dfc43d9659dd2/xmake/platforms/android/xmake.lua#L50

另外平台用 on_install("android" 来分开。

**Comment by waruqi** [comment]
我这边测试确实传了armeabi-v7a ，你可以提个pr ，然后触发 ci 上测试下各个平台，我也方便看 errors

**Comment by waruqi** [comment]
另外，`    import("package.tools.cmake").install(package, configs, {buildir = "build"})` 可以指定到 build 目录，这样就不用 `build_*`了

**Comment by waruqi** [comment]
另外我测了下 iphoneos 也ok 一切正常。

**Comment by waruqi** [comment]
你可以clone xmake-repo后，在 xmake-repo里面测试，更加干净方便，不受缓存影响。每次都会触发重装。

我平常测新包都是这么测的，ci上也是。

```console
cd xmake-repo
xmake l scripts/test.lua -vD --shallow -p android flatbuffers
```

**Comment by fasiondog** [comment]
我明天再试下

**Comment by fasiondog** [comment]
搞明白了，原来的xmake andoird 支持的arch是 armv7，现在和cmake一致改成了armeabi-v7a。所在我原来在外面调用 xmake f -arch armv7 要改。

**Comment by waruqi** [comment]
这个也好几个版本的事了吧 我都改了好久了，为了跟android ndk的命名保持一致，当然之前armv7也兼容支持，只不过传入cmake的是后来新版本才写的 所以我没做兼容

**Comment by fasiondog** [comment]
嗯，之前没用到cmake，习惯了。另外，xmake l scripts/test.lua -vD --shallow -p iphoneos -a x86_64 flatbuffers ， iphone 用i386 和 x86_64 失败

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
#error Unsupported architecture

**Comment by waruqi** [comment]
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DFL
> ATBUFFERS_LOCALE_INDEPENDENT=0 -I/Users/ruki/.xmake/cache/packages/2009/z/zlib/master/source/zli
> b/include -I/Users/ruki/.xmake/cache/packages/2009/z/zlib/master/source/zlib/grpc  -arch x86_64
> -mios-simulator-version-min=13.2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/
> iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -std=c++11 -stdlib=libc++ -Wall
> -pedantic -Werror -Wextra -Wno-unused-parameter -isysroot /Applications/Xcode.app/Contents/Devel
> oper/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk   -Wold-style-cast -o CMakeFile
> s/flatbuffers.dir/src/idl_parser.cpp.o -c /Users/ruki/.xmake/cache/packages/2009/z/zlib/master/s
> ource/zlib/src/idl_parser.cpp
> 

xmake 会自动传递 iPhoneSimulator.platform sdk 给cmake，但是cmake自身有各种自动探测干扰，所以似乎最下面，cmake自己自动追加了 -isysroot iPhoneOS.platform sdk进去，所以编译的时候，部分代码找到 真机的sdk上去了，没去用模拟器的。

这个要花时间研究下 cmake 的一些配置参数了，看看能否完全进去对 isysroot的自动探测

mac上也是会这样，不过mac上的自动检测我禁用了，可以通过    envs.CMAKE_OSX_SYSROOT = "" 来禁用，但这个只针对mac的

ios的还不行，需要调下下面这块配置逻辑了，目前还不清楚cmake是根据啥自动追加的还是真机的sdk sysroot

你可以先自己看看，等有时间我再仔细研究下。


https://github.com/xmake-io/xmake/blob/d9b466eee4de846d35dbc1081728a5b635949da0/xmake/modules/package/tools/cmake.lua#L71-L94I

**Comment by waruqi** [comment]
看下这个 https://github.com/xmake-io/xmake-repo/pull/197 应该可以了

**Comment by fasiondog** [comment]
armv7/V8 之前都可以，只是这个问题后面实际是 ios模拟器 i386 和 x86_64 编译失败。今天试了下，模拟器还是不行。

**Comment by waruqi** [comment]
我看之前 xmake-repo 里面都没这个库，你是放在自己的repo里面测试的？目前ci上 还不会去测试 i386/x86_64 。回头我先ci上改改再测测。

**Comment by fasiondog** [comment]
> 
> 
> 我看之前 xmake-repo 里面都没这个库，你是放在自己的repo里面测试的？目前ci上 还不会去测试 i386/x86_64 。回头我先ci上改改再测测。

是的，自己repo里测的，一直没写test，后来忙着就忘了提交贡献了

**Comment by waruqi** [comment]
主要是现在透传给 cmake 的环境配置，在模拟器下，cmake 会自动追加 ios 的 sysroot sdk 路径：-isysroot /App
lications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk

导致编译干扰，得研究下如何避免让cmake自动追加 这个 isysroot 路径参数

**Comment by waruqi** [comment]
终于找到了修改设置的地方，https://cmake.org/cmake/help/v3.17/manual/cmake-toolchains.7.html#id25

我改进过了，dev，更新下再试试，我这边测试ok的了。

**Comment by fasiondog** [comment]
手工 xmake l scripts/test.lua -v -D --shallow flatbuffers 没问题。
可是，我在用的项目依赖某个库，这个库里依赖flatbuffers，在 xmake update dev 后，现在没法编译了 ：（
比较了下直接手工测试和项目实际使用中，xmake输出的cmake命令：
手工的如下：
/Users/ljh/.xmake/packages/c/cmake/3.18.4/d639b7d6e3244216b403b39df5101abf/bin/cmake
-DCMAKE_INSTALL_PREFIX=/Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers/build0/install -DCMAKE_INSTALL_LIBDIR=/Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers/build0/install/lib -DFLATBUFFERS_BUILD_TESTS=OFF -DFLATBUFFERS_BUILD_FLATC=OFF -DFLATBUFFERS_BUILD_FLATHASH=OFF -G "Unix Makefiles" "-DCMAKE_CXX_FLAGS=-arch armv7s -miphoneos-version-min=10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" "-DCMAKE_ASM_FLAGS=-arch armv7s -miphoneos-version-min=10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" -DCMAKE_STATIC_LINKER_FLAGS= "-DCMAKE_EXE_LINKER_FLAGS=-arch armv7s -ObjC -lstdc++ -fobjc-link-runtime -miphoneos-version-min=10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" "-DCMAKE_SHARED_LINKER_FLAGS=-arch armv7s -ObjC -lstdc++ -fobjc-link-runtime -miphoneos-version-min=10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_MACOSX_BUNDLE=NO -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER "-DCMAKE_C_FLAGS=-arch armv7s -miphoneos-version-min=10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" /Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers

而项目依赖里的输出：
/usr/local/bin/cmake -DCMAKE_INSTALL_PREFIX=/Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers/build0/install -DCMAKE_INSTALL_LIBDIR=/Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers/build0/install/lib -DFLATBUFFERS_BUILD_TESTS=OFF -DFLATBUFFERS_BUILD_FLATC=OFF -DFLATBUFFERS_BUILD_FLATHASH=OFF -G "Unix Makefiles" -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_C_FLAGS= -DCMAKE_CXX_FLAGS= -DCMAKE_ASM_FLAGS= -DCMAKE_STATIC_LINKER_FLAGS= -DCMAKE_EXE_LINKER_FLAGS= "-DCMAKE_SHARED_LINKER_FLAGS=-arch arm64 -ObjC -lstdc++ -fobjc-link-runtime -miphoneos-version-min=13.7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_MACOSX_BUNDLE=NO /Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers

对齐整理了下：
手工本地测试：
-DCMAKE_CXX_FLAGS=-arch armv7s 
-miphoneos-version-min=10 
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" 
-DCMAKE_ASM_FLAGS=-arch armv7s 
-miphoneos-version-min=10 
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" -DCMAKE_STATIC_LINKER_FLAGS= 
-DCMAKE_EXE_LINKER_FLAGS=-arch armv7s 
-ObjC -lstdc++ -fobjc-link-runtime -miphoneos-version-min=10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" 
-DCMAKE_SHARED_LINKER_FLAGS=-arch armv7s -ObjC -lstdc++ -fobjc-link-runtime 
-miphoneos-version-min=10 
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY 
-DCMAKE_MACOSX_BUNDLE=NO -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY 
-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER 
-DCMAKE_C_FLAGS=-arch armv7s 
-miphoneos-version-min=10 
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" 
/Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers

实际项目中依赖的依赖：
-DCMAKE_INSTALL_PREFIX=/Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers/build0/install -DCMAKE_INSTALL_LIBDIR=/Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers/build0/install/lib -DFLATBUFFERS_BUILD_TESTS=OFF -DFLATBUFFERS_BUILD_FLATC=OFF -DFLATBUFFERS_BUILD_FLATHASH=OFF -G "Unix Makefiles" -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY 
-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY 
-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER 
-DCMAKE_C_FLAGS= 
-DCMAKE_CXX_FLAGS= 
-DCMAKE_ASM_FLAGS= 
-DCMAKE_STATIC_LINKER_FLAGS= 
-DCMAKE_EXE_LINKER_FLAGS= 
-DCMAKE_SHARED_LINKER_FLAGS=-arch arm64 -ObjC -lstdc++ -fobjc-link-runtime 
-miphoneos-version-min=13.7 
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk" -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_MACOSX_BUNDLE=NO 
/Users/ljh/.xmake/cache/packages/2012/f/flatbuffers/master/source/flatbuffers

现在项目卡壳了，flatbuffers又报：
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported
      architecture
#error Unsupported architecture

另外请教下，怎么先回退xmake

**Comment by waruqi** [comment]
你可以源码编译装 checkout指定commit

https://xmake.io/#/zh-cn/guide/installation?id=源码编译安装

**Comment by waruqi** [comment]
不过话说 dev我没改啥 就是支持了之前你说的 模拟器装不了问题 就几行改动

 https://github.com/xmake-io/xmake/commit/7d18274bb0b10b0f89a0762cd98d72650f5d7036
而且我这 iphoneos x86_64 装这个库都测试过 完全ok的

**Comment by waruqi** [comment]
没太搞明白你刚说的，反正大概看了下，手工的是 armv7s ，工程依赖里面是 arm64，arch不一致，其他没啥问题，应该跟 dev  没啥关系才对。

**Comment by fasiondog** [comment]
应该不是 xmake 的问题，应该是我切换平台和 arch 时，有时候没有先 xmake f -c 下，都是直接xmake f 设置。我全部清理了下，现在正常了。

**Comment by waruqi** [comment]
那模拟器的问题解了么？

**Comment by fasiondog** [comment]
解了，可以关闭了，多谢
