### ISSUE TITLE
Add imgui-sfml to this repo

### ISSUE THREAD

**Issue by sam20908** [xmake-io/xmake-repo#768]
> Note: If it is a 'bug report' or 'feature request', please select the corresponding issue template, otherwise this issue will be not replied. 

### Describe the problem details
I'm considering checking out xmake to compare to CMake, and my project uses imgui-sfml, which isn't on here. It'd be great if it got added here.

imgui-sfml: https://github.com/eliasdaler/imgui-sfml

**Comment by waruqi** [comment]
done https://github.com/xmake-io/xmake-repo/pull/769
