### ISSUE TITLE
[ci] add windows-2022 image

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#796]
### 描述讨论详情

GitHub container 已经更新到 [vs2022 image](https://github.com/actions/virtual-environments)，测试的action也应增加vs2022的支持。但目前windows上跑的ci太多、时间太长，对于老的2016/2019我觉得可以只跑一部分ci，例如x64+MT+static/x64+MD+shared/x86+MT+static，一般只要这三个过了所有的ci测试都能过。

**Comment by waruqi** [comment]
2016去掉也没事 ，明年5月 github 会强制下掉的

**Comment by waruqi** [comment]
改成 2019 2022 了
