### ISSUE TITLE
希望添加sqlpp11和sqlpp11-connector-mysql库

### ISSUE THREAD

**Issue by firesxp007** [xmake-io/xmake-repo#802]
希望添加sqlpp11和sqlpp11-connector-mysql库

**Comment by waruqi** [comment]
sqlpp11 我加了 https://github.com/xmake-io/xmake-repo/pull/801

sqlpp11-connector-mysql 作者新版本已经废弃整合到 sqlpp1了。可以自己配置 启用，不过暂时要依赖 mysql 。。目前还不支持，有需要自己提 pr 改进。
