### ISSUE TITLE
Windows下使用sqlite3失败

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake-repo#9]
![default](https://user-images.githubusercontent.com/1145161/52469367-32f5cf80-2bc6-11e9-9f76-e5835fa38db4.png)
Windows下使用sqlite3失败，详见上述截图。xmake版本：2.2.3

**Comment by waruqi** [comment]
这个是2.2.3的问题 ，在dev/master上已经修复了，你可以试试

**Comment by fasiondog** [comment]
![default](https://user-images.githubusercontent.com/1145161/52470622-ab11c480-2bc9-11e9-8a20-24fd6259a29c.png)
安装了xmake-master，但会出现install failed。把AppData Roaming下的.xmake都删除后，仍旧安装失败。

**Comment by waruqi** [comment]
我这边测试ok，你加上-v -D 执行下，给我看下错误信息

**Comment by fasiondog** [comment]
![default](https://user-images.githubusercontent.com/1145161/52480515-ebcc0680-2be6-11e9-85f0-cc5652e6f6c7.png)

**Comment by fasiondog** [comment]
本地工程的.xmake删了也不行，提示目标平台冲突

**Comment by waruqi** [comment]
看了下，你这进入的x64_x86 cmd环境，在执行nmake编译sqlite3的时候，默认.o作为x64去编译了，但是link的时候，sqlite3自带的makefile.msc里面检测成x86去link了。。（我这边的x86_x64环境测试ok）

可以尝试不要自己进入vs cmd环境，xmake会自动切到对应的vs cmd环境中进行编译。。

在非vs环境的cmd下，直接编译试试

**Comment by waruqi** [comment]
我刚改进了下sqlite3的包，加上了 PLATFORM=x64的设置，强制指定arch编译，避免sqlite3/makefile.msc的错误检测。

你可以执行 xmake repo --add xmake-repo-dev https://github.com/xmake-io/xmake-repo dev
添加dev版本的repo，然后重新执行下编译试试

**Comment by fasiondog** [comment]
还有个问题，xmake-master会造成已有的本地依赖包找不到了，我这啥也没改，就找不到自己的hdf5依赖头文件了，只有删了重新安装xmake-2.2.3
![default](https://user-images.githubusercontent.com/1145161/52483250-56cd0b80-2bee-11e9-862d-a3bdd03812af.png)

**Comment by waruqi** [comment]
这块我会看下，最近重构升级了find_package，可能会有些影响，我调下看看

**Comment by waruqi** [comment]
关于后面这个问题，之后 https://github.com/xmake-io/xmake/issues/343 里面跟进吧

**Comment by waruqi** [comment]
> 还有个问题，xmake-master会造成已有的本地依赖包找不到了，我这啥也没改，就找不到自己的hdf5依赖头文件了，只有删了重新安装xmake-2.2.3
> ![default](https://user-images.githubusercontent.com/1145161/52483250-56cd0b80-2bee-11e9-862d-a3bdd03812af.png)

见 https://github.com/xmake-io/xmake/issues/343#issuecomment-461830013

**Comment by waruqi** [comment]
后面那个检测问题，我master上修复了

**Comment by fasiondog** [comment]
是不是直接下载release里的那个exe就可以了

> 
> 
> 后面那个检测问题，我master上修复了

是不是直接下载release里的那个exe就可以了

**Comment by waruqi** [comment]
是的

**Comment by fasiondog** [comment]
👍  3Q 老大神速
