### ISSUE TITLE
ubuntu 20.04 x64 下无法安装 libjpeg

### ISSUE THREAD

**Issue by walletiger** [xmake-io/xmake-repo#947]
xrepo install libjpeg
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> libjpeg v9d 
please input: y (y/n/m)
y
  => download https://www.ijg.org/files/jpegsrc.v9d.tar.gz .. failed

we can also download these packages manually:
  - https://www.ijg.org/files/jpegsrc.v9d.tar.gz
to the local search directories: 
  - jpegsrc.v9d.tar.gz
and we can run `xmake g --pkg_searchdirs=/xxx` to set the search directories.
error: unmatched checksum!
error: execv(xmake require -j 3 --extra={system=false} libjpeg) failed(255)

wget https://www.ijg.org/files/jpegsrc.v9d.tar.gz 可以成功， 也可以解压 ，但报告 checksum 不对， 换了不同机器 jpeg v9d, v9c 都是这样情况， 前一段时间是好的。

**Comment by waruqi** [comment]
那是因为前段时间  jpeg 官方源，强行覆盖更新了所有文件，shasum 变了，你需要更新下 xmake-repo 保证 shasum 同步

xrepo update-repo

**Comment by walletiger** [comment]
是这个问题， 已经解决， 感谢大佬 。

> 那是因为前段时间 jpeg 官方源，强行覆盖更新了所有文件，shasum 变了，你需要更新下 xmake-repo 保证 shasum 同步
> 
> xrepo update-repo
