### ISSUE TITLE
Binary files inside a package installed via cmake do not show up at install directory

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#96]
### Describe the bug
用`import("package.tools.cmake").install(package, configs)`装的包，`bin`文件夹在输出的安装目录消失了

### Expected behavior
安装目录下应该有`bin`，`include`，`lib`等文件夹

### Related Environment

- xmake version: 2.3.8
- os: Windows 10
- target platform: windows

### Additional context
简单测试可以用[cmake-project-template](https://github.com/kigster/cmake-project-template)

```lua
-- xmake.lua
package("cmake-template")
    set_homepage("https://github.com/kigster/cmake-project-template")
    set_description("CMake Template")
    add_urls("https://github.com/kigster/cmake-project-template.git")
    on_install(function (package)
        import("package.tools.cmake").install(package)
    end)
```
装完之后没有`bin`文件夹和相应的二进制文件

**Comment by waruqi** [comment]
这个是cmakelists决定的，xmake只是设置prefix目录给cmake，然后执行cmake编译安装，提取prefix目录下的bin lib等产物

但是有些cmake工程并没有配置install脚本，所以cmake编译后，xmake无法从prefix目录找到任何编译产物

可以使用cmake.build而不是cmake.install去安装包，并设置build输出目录，编译完成后，通过os.cp直接从build下提取bin文件


可以参考这个配置 

https://github.com/xmake-io/xmake-repo/blob/d7daeabf0456da1e3dfdd5113e69088b0e69ab2a/packages/b/box2d/xmake.lua#L17

**Comment by xq114** [comment]
> 这个是cmakelists决定的，xmake只是设置prefix目录给cmake，然后执行cmake编译安装，提取prefix目录下的bin lib等产物
> 
> 但是有些cmake工程并没有配置install脚本，所以cmake编译后，即使执行了 make install，实际上cmake没有安装任何产物到 prefix 目录，还是在 build 目录下随意放置，因此xmake无法从prefix目录找到任何编译产物
> 
> 但我们可以使用cmake.build而不是cmake.install去安装包，并设置build输出目录，编译完成后，通过os.cp直接从build下提取bin文件
> 
> 可以参考这个配置
> 
> https://github.com/xmake-io/xmake-repo/blob/d7daeabf0456da1e3dfdd5113e69088b0e69ab2a/packages/b/box2d/xmake.lua#L17-L23

CMakeLists.txt有install部分并且执行install后lib、include、share等文件夹都有，只有bin文件夹是缺失的，并且手动make install的结果是bin、lib、include都有。可以看这个更简单的例子

https://github.com/xq114/hello-cmake

```
-- xmake.lua
package(hello_cmake)
    set_homepage("https://github.com/xq114/hello-cmake")
    set_description("cmake test")
    add_urls("https://github.com/xq114/hello-cmake.git")
    on_install(function (package)
        import("package.tools.cmake").install(package)
    end)
```

其中CMakeLists.txt关于install的部分（33-37）
```
# add the install targets
install(TARGETS Tutorial DESTINATION bin)
install(FILES "${PROJECT_BINARY_DIR}/TutorialConfig.h"
  DESTINATION include
  )
```

xmake install的结果
![image](https://user-images.githubusercontent.com/42310255/97946468-814cf800-1dc5-11eb-8ae8-43b15ad44ce6.png)

cmake install的结果
![image](https://user-images.githubusercontent.com/42310255/97946630-02a48a80-1dc6-11eb-9507-a58074067053.png)

**Comment by waruqi** [comment]
哦，你说的bin啊，因为 xmake-repo 主要用于 库集成的，默认不会去装 bin 里面的东西，装了通常也不会用到，反而占用磁盘空间。。所以 xmake的 cmake.install 的 脚本里面我暂时没加 bin 的安装逻辑。。

这种根据实际包的需要，如果真的要 bin ，那就 执行完 cmake.install ，在 on_intall 里面额外 os.cp install/bin 下里面的文件到 installdir()

我刚也改进了dev版本，如果是 set_kind("binary") 的包（不过此类包不会集成lib，仅作为tools），还会额外安装 bin 目录，也可以 `cmake.install(package, configs, {binary = true})` 告诉 cmake 也安装 bin 产物
