### ISSUE TITLE
Can't pass additional setup information

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-repo#97]
### Describe the bug
Documentation
![image](https://user-images.githubusercontent.com/42310255/97947884-b52a1c80-1dc9-11eb-9057-1b2f7619030e.png)

But when I execute this command in a project directory I got an error like this
![image](https://user-images.githubusercontent.com/42310255/97947860-a17eb600-1dc9-11eb-8601-515ce575bb03.png)

### Expected behavior
xmake install the specified required package without error

### Error output
error: cannot deserialize "debug=true,config={s"... : (t):1: '<eof>' expected near '='

### Related Environment

Please provide compiling and running environment information:

- xmake version: 2.3.8
- os: Windows 10
- target platform: windows

**Comment by waruqi** [comment]
既然是国人就直接用中文吧，en文给你回好累的。

```console
xmake require --extra="{debug=true,config={small=true}}" tbox
```

文档笔误，应该要加个 {} 的。

或者也可以用最新的 xrepo 命令，更加简单点

```console
xrepo install -m debug -f "small=true" tbox
```
