### ISSUE TITLE
Thoughts on LuaJIT remote

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake-repo#982]
This issue is related to LuaJIT and the outdated version we use due to the main repo not creating a new release since 2017.

I have found https://github.com/openresty/luajit2 that seems to be maintaining a stable version and is up to date with the latest changes.

Should we switch to this fork or keep using the older official versions?

@SirLynix pinging as you are knowledgeable in Lua and the implementations

**Comment by waruqi** [comment]
You can use the official master version, e.g. add a fake version and add the github mirror url

add_version("2.1.1-20220207", "<commit number>")

or adf a new package, `openresty-luajit`

**Comment by waruqi** [comment]
you can also try `add_requires("luajit master")`
